// Code generated by ent, DO NOT EDIT.

package relationshipassertion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldUpdatedAt, v))
}

// Dimension applies equality check predicate on the "dimension" field. It's identical to DimensionEQ.
func Dimension(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldDimension, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldValue, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldSourceType, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldConfidence, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldReason, v))
}

// ValidFrom applies equality check predicate on the "valid_from" field. It's identical to ValidFromEQ.
func ValidFrom(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldValidFrom, v))
}

// SupersedesAssertionID applies equality check predicate on the "supersedes_assertion_id" field. It's identical to SupersedesAssertionIDEQ.
func SupersedesAssertionID(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldSupersedesAssertionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldUpdatedAt, v))
}

// DimensionEQ applies the EQ predicate on the "dimension" field.
func DimensionEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldDimension, v))
}

// DimensionNEQ applies the NEQ predicate on the "dimension" field.
func DimensionNEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldDimension, v))
}

// DimensionIn applies the In predicate on the "dimension" field.
func DimensionIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldDimension, vs...))
}

// DimensionNotIn applies the NotIn predicate on the "dimension" field.
func DimensionNotIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldDimension, vs...))
}

// DimensionGT applies the GT predicate on the "dimension" field.
func DimensionGT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldDimension, v))
}

// DimensionGTE applies the GTE predicate on the "dimension" field.
func DimensionGTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldDimension, v))
}

// DimensionLT applies the LT predicate on the "dimension" field.
func DimensionLT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldDimension, v))
}

// DimensionLTE applies the LTE predicate on the "dimension" field.
func DimensionLTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldDimension, v))
}

// DimensionContains applies the Contains predicate on the "dimension" field.
func DimensionContains(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContains(FieldDimension, v))
}

// DimensionHasPrefix applies the HasPrefix predicate on the "dimension" field.
func DimensionHasPrefix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasPrefix(FieldDimension, v))
}

// DimensionHasSuffix applies the HasSuffix predicate on the "dimension" field.
func DimensionHasSuffix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasSuffix(FieldDimension, v))
}

// DimensionEqualFold applies the EqualFold predicate on the "dimension" field.
func DimensionEqualFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEqualFold(FieldDimension, v))
}

// DimensionContainsFold applies the ContainsFold predicate on the "dimension" field.
func DimensionContainsFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContainsFold(FieldDimension, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContainsFold(FieldValue, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContainsFold(FieldSourceType, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldConfidence, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContainsFold(FieldReason, v))
}

// ValidFromEQ applies the EQ predicate on the "valid_from" field.
func ValidFromEQ(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldValidFrom, v))
}

// ValidFromNEQ applies the NEQ predicate on the "valid_from" field.
func ValidFromNEQ(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldValidFrom, v))
}

// ValidFromIn applies the In predicate on the "valid_from" field.
func ValidFromIn(vs ...time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldValidFrom, vs...))
}

// ValidFromNotIn applies the NotIn predicate on the "valid_from" field.
func ValidFromNotIn(vs ...time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldValidFrom, vs...))
}

// ValidFromGT applies the GT predicate on the "valid_from" field.
func ValidFromGT(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldValidFrom, v))
}

// ValidFromGTE applies the GTE predicate on the "valid_from" field.
func ValidFromGTE(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldValidFrom, v))
}

// ValidFromLT applies the LT predicate on the "valid_from" field.
func ValidFromLT(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldValidFrom, v))
}

// ValidFromLTE applies the LTE predicate on the "valid_from" field.
func ValidFromLTE(v time.Time) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldValidFrom, v))
}

// SupersedesAssertionIDEQ applies the EQ predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEQ(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDNEQ applies the NEQ predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDNEQ(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNEQ(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDIn applies the In predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIn(FieldSupersedesAssertionID, vs...))
}

// SupersedesAssertionIDNotIn applies the NotIn predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDNotIn(vs ...string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotIn(FieldSupersedesAssertionID, vs...))
}

// SupersedesAssertionIDGT applies the GT predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDGT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGT(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDGTE applies the GTE predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDGTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldGTE(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDLT applies the LT predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDLT(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLT(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDLTE applies the LTE predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDLTE(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldLTE(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDContains applies the Contains predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDContains(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContains(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDHasPrefix applies the HasPrefix predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDHasPrefix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasPrefix(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDHasSuffix applies the HasSuffix predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDHasSuffix(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldHasSuffix(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDIsNil applies the IsNil predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDIsNil() predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldIsNull(FieldSupersedesAssertionID))
}

// SupersedesAssertionIDNotNil applies the NotNil predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDNotNil() predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldNotNull(FieldSupersedesAssertionID))
}

// SupersedesAssertionIDEqualFold applies the EqualFold predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDEqualFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldEqualFold(FieldSupersedesAssertionID, v))
}

// SupersedesAssertionIDContainsFold applies the ContainsFold predicate on the "supersedes_assertion_id" field.
func SupersedesAssertionIDContainsFold(v string) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.FieldContainsFold(FieldSupersedesAssertionID, v))
}

// HasWorkspace applies the HasEdge predicate on the "workspace" edge.
func HasWorkspace() predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkspaceTable, WorkspaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceWith applies the HasEdge predicate on the "workspace" edge with a given conditions (other predicates).
func HasWorkspaceWith(preds ...predicate.RevenueWorkspace) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(func(s *sql.Selector) {
		step := newWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationship applies the HasEdge predicate on the "relationship" edge.
func HasRelationship() predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RelationshipTable, RelationshipColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipWith applies the HasEdge predicate on the "relationship" edge with a given conditions (other predicates).
func HasRelationshipWith(preds ...predicate.Relationship) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(func(s *sql.Selector) {
		step := newRelationshipStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasObservation applies the HasEdge predicate on the "observation" edge.
func HasObservation() predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ObservationTable, ObservationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasObservationWith applies the HasEdge predicate on the "observation" edge with a given conditions (other predicates).
func HasObservationWith(preds ...predicate.RelationshipObservation) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(func(s *sql.Selector) {
		step := newObservationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelationshipAssertion) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelationshipAssertion) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelationshipAssertion) predicate.RelationshipAssertion {
	return predicate.RelationshipAssertion(sql.NotPredicates(p))
}
