-- Account deletion (DELETE /v1/me) deletes the "users" row and relies on the
-- database to delete everything that the user owns. Every foreign key to
-- "users", and every foreign key to "revenue_workspaces", becomes
-- ON DELETE CASCADE.
--
-- Each constraint is added NOT VALID here: that takes a brief lock and does not
-- scan the table. The next migration validates the constraints in a separate
-- transaction, which scans without blocking reads or writes.
--
-- The Atlas diff also proposed unrelated drift (hand-written CHECK constraints,
-- indexes, and a column default that the Ent schema does not model). That drift
-- is deliberately left out.

ALTER TABLE "revenue_workspaces" DROP CONSTRAINT "revenue_workspaces_users_revenue_workspaces", ADD CONSTRAINT "revenue_workspaces_users_revenue_workspaces" FOREIGN KEY ("user_revenue_workspaces") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "action_outcomes" DROP CONSTRAINT "action_outcomes_revenue_workspaces_outcomes", ADD CONSTRAINT "action_outcomes_revenue_workspaces_outcomes" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "action_outcomes" DROP CONSTRAINT "action_outcomes_users_action_outcomes", ADD CONSTRAINT "action_outcomes_users_action_outcomes" FOREIGN KEY ("user_action_outcomes") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "action_proposals" DROP CONSTRAINT "action_proposals_users_action_proposals", ADD CONSTRAINT "action_proposals_users_action_proposals" FOREIGN KEY ("user_action_proposals") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "agent_approvals" DROP CONSTRAINT "agent_approvals_users_agent_approvals", ADD CONSTRAINT "agent_approvals_users_agent_approvals" FOREIGN KEY ("user_agent_approvals") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "agent_definitions" DROP CONSTRAINT "agent_definitions_users_agent_definitions", ADD CONSTRAINT "agent_definitions_users_agent_definitions" FOREIGN KEY ("user_agent_definitions") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "agent_session_events" DROP CONSTRAINT "agent_session_events_users_agent_session_events", ADD CONSTRAINT "agent_session_events_users_agent_session_events" FOREIGN KEY ("user_agent_session_events") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "agent_sessions" DROP CONSTRAINT "agent_sessions_users_agent_sessions", ADD CONSTRAINT "agent_sessions_users_agent_sessions" FOREIGN KEY ("user_agent_sessions") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "agent_tool_calls" DROP CONSTRAINT "agent_tool_calls_users_agent_tool_calls", ADD CONSTRAINT "agent_tool_calls_users_agent_tool_calls" FOREIGN KEY ("user_agent_tool_calls") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "agent_tool_result_blobs" DROP CONSTRAINT "agent_tool_result_blobs_users_agent_tool_result_blobs", ADD CONSTRAINT "agent_tool_result_blobs_users_agent_tool_result_blobs" FOREIGN KEY ("user_agent_tool_result_blobs") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "agent_turns" DROP CONSTRAINT "agent_turns_users_agent_turns", ADD CONSTRAINT "agent_turns_users_agent_turns" FOREIGN KEY ("user_agent_turns") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "approval_tokens" DROP CONSTRAINT "approval_tokens_users_approval_tokens", ADD CONSTRAINT "approval_tokens_users_approval_tokens" FOREIGN KEY ("user_approval_tokens") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "background_task_artifacts" DROP CONSTRAINT "background_task_artifacts_users_background_task_artifacts", ADD CONSTRAINT "background_task_artifacts_users_background_task_artifacts" FOREIGN KEY ("user_background_task_artifacts") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "background_task_run_events" DROP CONSTRAINT "background_task_run_events_users_background_task_run_events", ADD CONSTRAINT "background_task_run_events_users_background_task_run_events" FOREIGN KEY ("user_background_task_run_events") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "background_task_runs" DROP CONSTRAINT "background_task_runs_users_background_task_runs", ADD CONSTRAINT "background_task_runs_users_background_task_runs" FOREIGN KEY ("user_background_task_runs") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "background_task_schedule_states" DROP CONSTRAINT "background_task_schedule_state_2cee65f7000b363b766c694c83fc498a", ADD CONSTRAINT "background_task_schedule_state_2cee65f7000b363b766c694c83fc498a" FOREIGN KEY ("user_background_task_schedule_states") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "background_tasks" DROP CONSTRAINT "background_tasks_users_background_tasks", ADD CONSTRAINT "background_tasks_users_background_tasks" FOREIGN KEY ("user_background_tasks") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "capture_artifacts" DROP CONSTRAINT "capture_artifacts_users_capture_artifacts", ADD CONSTRAINT "capture_artifacts_users_capture_artifacts" FOREIGN KEY ("user_capture_artifacts") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "cloud_events" DROP CONSTRAINT "cloud_events_users_cloud_events", ADD CONSTRAINT "cloud_events_users_cloud_events" FOREIGN KEY ("user_cloud_events") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "commitment_dependencies" DROP CONSTRAINT "commitment_dependencies_revenu_92d2eb5a75a66294d280100b545c9de1", ADD CONSTRAINT "commitment_dependencies_revenu_92d2eb5a75a66294d280100b545c9de1" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "commitment_dependencies" DROP CONSTRAINT "commitment_dependencies_users_commitment_dependencies", ADD CONSTRAINT "commitment_dependencies_users_commitment_dependencies" FOREIGN KEY ("user_commitment_dependencies") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "commitment_events" DROP CONSTRAINT "commitment_events_revenue_workspaces_commitment_events", ADD CONSTRAINT "commitment_events_revenue_workspaces_commitment_events" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "commitment_events" DROP CONSTRAINT "commitment_events_users_commitment_events", ADD CONSTRAINT "commitment_events_users_commitment_events" FOREIGN KEY ("user_commitment_events") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "commitments" DROP CONSTRAINT "commitments_revenue_workspaces_commitments", ADD CONSTRAINT "commitments_revenue_workspaces_commitments" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "commitments" DROP CONSTRAINT "commitments_users_commitments", ADD CONSTRAINT "commitments_users_commitments" FOREIGN KEY ("user_commitments") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "connector_audit_events" DROP CONSTRAINT "connector_audit_events_users_connector_audit_events", ADD CONSTRAINT "connector_audit_events_users_connector_audit_events" FOREIGN KEY ("user_connector_audit_events") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "conversation_intelligence_artifacts" DROP CONSTRAINT "conversation_intelligence_arti_1e63f30e8e9419065fc343e9c96e8fcb", ADD CONSTRAINT "conversation_intelligence_arti_1e63f30e8e9419065fc343e9c96e8fcb" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "conversation_intelligence_artifacts" DROP CONSTRAINT "conversation_intelligence_arti_830936ebd4345e9acc8687a33c237c44", ADD CONSTRAINT "conversation_intelligence_arti_830936ebd4345e9acc8687a33c237c44" FOREIGN KEY ("user_conversation_intelligence_artifacts") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "credit_ledgers" DROP CONSTRAINT "credit_ledgers_users_ledger_entries", ADD CONSTRAINT "credit_ledgers_users_ledger_entries" FOREIGN KEY ("user_ledger_entries") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "entities" DROP CONSTRAINT "entities_revenue_workspaces_entities", ADD CONSTRAINT "entities_revenue_workspaces_entities" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "entities" DROP CONSTRAINT "entities_users_entities", ADD CONSTRAINT "entities_users_entities" FOREIGN KEY ("user_entities") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "entity_identifiers" DROP CONSTRAINT "entity_identifiers_revenue_workspaces_entity_identifiers", ADD CONSTRAINT "entity_identifiers_revenue_workspaces_entity_identifiers" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "entity_identifiers" DROP CONSTRAINT "entity_identifiers_users_entity_identifiers", ADD CONSTRAINT "entity_identifiers_users_entity_identifiers" FOREIGN KEY ("user_entity_identifiers") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "entity_resource_refs" DROP CONSTRAINT "entity_resource_refs_revenue_workspaces_entity_resource_refs", ADD CONSTRAINT "entity_resource_refs_revenue_workspaces_entity_resource_refs" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "entity_resource_refs" DROP CONSTRAINT "entity_resource_refs_users_entity_resource_refs", ADD CONSTRAINT "entity_resource_refs_users_entity_resource_refs" FOREIGN KEY ("user_entity_resource_refs") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "google_watches" DROP CONSTRAINT "google_watches_users_google_watches", ADD CONSTRAINT "google_watches_users_google_watches" FOREIGN KEY ("user_google_watches") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "llm_usages" DROP CONSTRAINT "llm_usages_users_llm_usages", ADD CONSTRAINT "llm_usages_users_llm_usages" FOREIGN KEY ("user_llm_usages") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "mail_body_caches" DROP CONSTRAINT "mail_body_caches_users_mail_body_caches", ADD CONSTRAINT "mail_body_caches_users_mail_body_caches" FOREIGN KEY ("user_mail_body_caches") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "mail_message_meta" DROP CONSTRAINT "mail_message_meta_users_mail_message_metas", ADD CONSTRAINT "mail_message_meta_users_mail_message_metas" FOREIGN KEY ("user_mail_message_metas") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "mail_signals" DROP CONSTRAINT "mail_signals_users_mail_signals", ADD CONSTRAINT "mail_signals_users_mail_signals" FOREIGN KEY ("user_mail_signals") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "mail_threads" DROP CONSTRAINT "mail_threads_users_mail_threads", ADD CONSTRAINT "mail_threads_users_mail_threads" FOREIGN KEY ("user_mail_threads") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "mcp_connections" DROP CONSTRAINT "mcp_connections_users_mcp_connections", ADD CONSTRAINT "mcp_connections_users_mcp_connections" FOREIGN KEY ("user_mcp_connections") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "meeting_minute_usages" DROP CONSTRAINT "meeting_minute_usages_users_meeting_minute_usages", ADD CONSTRAINT "meeting_minute_usages_users_meeting_minute_usages" FOREIGN KEY ("user_meeting_minute_usages") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "oauth_connections" DROP CONSTRAINT "oauth_connections_users_oauth_connections", ADD CONSTRAINT "oauth_connections_users_oauth_connections" FOREIGN KEY ("user_oauth_connections") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "person_attributes" DROP CONSTRAINT "person_attributes_revenue_workspaces_person_attributes", ADD CONSTRAINT "person_attributes_revenue_workspaces_person_attributes" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "person_attributes" DROP CONSTRAINT "person_attributes_users_person_attributes", ADD CONSTRAINT "person_attributes_users_person_attributes" FOREIGN KEY ("user_person_attributes") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "person_identities" DROP CONSTRAINT "person_identities_revenue_workspaces_person_identities", ADD CONSTRAINT "person_identities_revenue_workspaces_person_identities" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "person_identities" DROP CONSTRAINT "person_identities_users_person_identities", ADD CONSTRAINT "person_identities_users_person_identities" FOREIGN KEY ("user_person_identities") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "person_interaction_stats" DROP CONSTRAINT "person_interaction_stats_reven_1a676f2b23db32df6afc400873893086", ADD CONSTRAINT "person_interaction_stats_reven_1a676f2b23db32df6afc400873893086" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "person_merge_candidates" DROP CONSTRAINT "person_merge_candidates_revenu_4c3c0c54b5257649793ce552b278651a", ADD CONSTRAINT "person_merge_candidates_revenu_4c3c0c54b5257649793ce552b278651a" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "person_merge_candidates" DROP CONSTRAINT "person_merge_candidates_users_person_merge_candidates", ADD CONSTRAINT "person_merge_candidates_users_person_merge_candidates" FOREIGN KEY ("user_person_merge_candidates") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "person_suppressions" DROP CONSTRAINT "person_suppressions_revenue_workspaces_person_suppressions", ADD CONSTRAINT "person_suppressions_revenue_workspaces_person_suppressions" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "person_suppressions" DROP CONSTRAINT "person_suppressions_users_person_suppressions", ADD CONSTRAINT "person_suppressions_users_person_suppressions" FOREIGN KEY ("user_person_suppressions") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "policy_decision_snapshots" DROP CONSTRAINT "policy_decision_snapshots_revenue_workspaces_decisions", ADD CONSTRAINT "policy_decision_snapshots_revenue_workspaces_decisions" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "policy_decision_snapshots" DROP CONSTRAINT "policy_decision_snapshots_users_policy_decision_snapshots", ADD CONSTRAINT "policy_decision_snapshots_users_policy_decision_snapshots" FOREIGN KEY ("user_policy_decision_snapshots") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_assertions" DROP CONSTRAINT "relationship_assertions_revenu_cfd12cbb1ca73669db264b0dfd51c59b", ADD CONSTRAINT "relationship_assertions_revenu_cfd12cbb1ca73669db264b0dfd51c59b" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_assertions" DROP CONSTRAINT "relationship_assertions_users_relationship_assertions", ADD CONSTRAINT "relationship_assertions_users_relationship_assertions" FOREIGN KEY ("user_relationship_assertions") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_attention_items" DROP CONSTRAINT "relationship_attention_items_r_08f9696c627d891d88bc4d81e117365c", ADD CONSTRAINT "relationship_attention_items_r_08f9696c627d891d88bc4d81e117365c" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_attention_items" DROP CONSTRAINT "relationship_attention_items_users_relationship_attention_items", ADD CONSTRAINT "relationship_attention_items_users_relationship_attention_items" FOREIGN KEY ("user_relationship_attention_items") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_identities" DROP CONSTRAINT "relationship_identities_revenu_e0b8453ee8d90d15355391803ac140cc", ADD CONSTRAINT "relationship_identities_revenu_e0b8453ee8d90d15355391803ac140cc" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_identities" DROP CONSTRAINT "relationship_identities_users_relationship_identities", ADD CONSTRAINT "relationship_identities_users_relationship_identities" FOREIGN KEY ("user_relationship_identities") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_identity_candidates" DROP CONSTRAINT "relationship_identity_candidat_41655d93299b45606450cf3215342f9a", ADD CONSTRAINT "relationship_identity_candidat_41655d93299b45606450cf3215342f9a" FOREIGN KEY ("user_relationship_identity_candidates") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_identity_candidates" DROP CONSTRAINT "relationship_identity_candidat_5df84cd4e08a126f8e3acc4218500a7b", ADD CONSTRAINT "relationship_identity_candidat_5df84cd4e08a126f8e3acc4218500a7b" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_identity_decisions" DROP CONSTRAINT "relationship_identity_decision_3358c713811cac11a37178177aa2144a", ADD CONSTRAINT "relationship_identity_decision_3358c713811cac11a37178177aa2144a" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_identity_decisions" DROP CONSTRAINT "relationship_identity_decision_943cf3cec1c94f9e9dac9d6131b3f25b", ADD CONSTRAINT "relationship_identity_decision_943cf3cec1c94f9e9dac9d6131b3f25b" FOREIGN KEY ("user_relationship_identity_decisions") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_lineage_events" DROP CONSTRAINT "relationship_lineage_events_re_0c3d3b5af96265efa66a92bcab3fb986", ADD CONSTRAINT "relationship_lineage_events_re_0c3d3b5af96265efa66a92bcab3fb986" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_lineage_events" DROP CONSTRAINT "relationship_lineage_events_users_relationship_lineage_events", ADD CONSTRAINT "relationship_lineage_events_users_relationship_lineage_events" FOREIGN KEY ("user_relationship_lineage_events") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_observations" DROP CONSTRAINT "relationship_observations_reve_5c2e238af69e7038a10e95ab07491e9e", ADD CONSTRAINT "relationship_observations_reve_5c2e238af69e7038a10e95ab07491e9e" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_observations" DROP CONSTRAINT "relationship_observations_users_relationship_observations", ADD CONSTRAINT "relationship_observations_users_relationship_observations" FOREIGN KEY ("user_relationship_observations") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_participants" DROP CONSTRAINT "relationship_participants_reve_b92f91fcd1726b66d7b79eb4e2a03861", ADD CONSTRAINT "relationship_participants_reve_b92f91fcd1726b66d7b79eb4e2a03861" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_participants" DROP CONSTRAINT "relationship_participants_users_relationship_participants", ADD CONSTRAINT "relationship_participants_users_relationship_participants" FOREIGN KEY ("user_relationship_participants") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_persons" DROP CONSTRAINT "relationship_persons_revenue_workspaces_relationship_persons", ADD CONSTRAINT "relationship_persons_revenue_workspaces_relationship_persons" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_persons" DROP CONSTRAINT "relationship_persons_users_relationship_persons", ADD CONSTRAINT "relationship_persons_users_relationship_persons" FOREIGN KEY ("user_relationship_persons") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_projection_jobs" DROP CONSTRAINT "relationship_projection_jobs_r_ee99889c305a24c0a389fdce2a61ab71", ADD CONSTRAINT "relationship_projection_jobs_r_ee99889c305a24c0a389fdce2a61ab71" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_projection_jobs" DROP CONSTRAINT "relationship_projection_jobs_users_relationship_projection_jobs", ADD CONSTRAINT "relationship_projection_jobs_users_relationship_projection_jobs" FOREIGN KEY ("user_relationship_projection_jobs") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_review_acknowledgements" DROP CONSTRAINT "relationship_review_acknowledg_3c0c9190cb433935fda6a82e0a7cb36d", ADD CONSTRAINT "relationship_review_acknowledg_3c0c9190cb433935fda6a82e0a7cb36d" FOREIGN KEY ("user_relationship_review_acknowledgements") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_review_acknowledgements" DROP CONSTRAINT "relationship_review_acknowledg_e29235dbcf290bb98a53fdf68fa05970", ADD CONSTRAINT "relationship_review_acknowledg_e29235dbcf290bb98a53fdf68fa05970" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_source_status" DROP CONSTRAINT "relationship_source_status_rev_5d90ff6d5153f9ef9f937c47b30faac3", ADD CONSTRAINT "relationship_source_status_rev_5d90ff6d5153f9ef9f937c47b30faac3" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_source_status" DROP CONSTRAINT "relationship_source_status_users_relationship_source_statuses", ADD CONSTRAINT "relationship_source_status_users_relationship_source_statuses" FOREIGN KEY ("user_relationship_source_statuses") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_state_snapshots" DROP CONSTRAINT "relationship_state_snapshots_r_a605a2357bd8e0c0c5dcd8f742af075e", ADD CONSTRAINT "relationship_state_snapshots_r_a605a2357bd8e0c0c5dcd8f742af075e" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationship_state_snapshots" DROP CONSTRAINT "relationship_state_snapshots_users_relationship_state_snapshots", ADD CONSTRAINT "relationship_state_snapshots_users_relationship_state_snapshots" FOREIGN KEY ("user_relationship_state_snapshots") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationships" DROP CONSTRAINT "relationships_revenue_workspaces_relationships", ADD CONSTRAINT "relationships_revenue_workspaces_relationships" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "relationships" DROP CONSTRAINT "relationships_users_relationships", ADD CONSTRAINT "relationships_users_relationships" FOREIGN KEY ("user_relationships") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_action_revisions" DROP CONSTRAINT "revenue_action_revisions_users_revenue_action_revisions", ADD CONSTRAINT "revenue_action_revisions_users_revenue_action_revisions" FOREIGN KEY ("user_revenue_action_revisions") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_actions" DROP CONSTRAINT "revenue_actions_revenue_workspaces_actions", ADD CONSTRAINT "revenue_actions_revenue_workspaces_actions" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_actions" DROP CONSTRAINT "revenue_actions_users_revenue_actions", ADD CONSTRAINT "revenue_actions_users_revenue_actions" FOREIGN KEY ("user_revenue_actions") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_evidences" DROP CONSTRAINT "revenue_evidences_revenue_workspaces_evidences", ADD CONSTRAINT "revenue_evidences_revenue_workspaces_evidences" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_evidences" DROP CONSTRAINT "revenue_evidences_users_revenue_evidences", ADD CONSTRAINT "revenue_evidences_users_revenue_evidences" FOREIGN KEY ("user_revenue_evidences") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_leak_scans" DROP CONSTRAINT "revenue_leak_scans_revenue_workspaces_scans", ADD CONSTRAINT "revenue_leak_scans_revenue_workspaces_scans" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_leak_scans" DROP CONSTRAINT "revenue_leak_scans_users_revenue_leak_scans", ADD CONSTRAINT "revenue_leak_scans_users_revenue_leak_scans" FOREIGN KEY ("user_revenue_leak_scans") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_outbox_events" DROP CONSTRAINT "revenue_outbox_events_revenue_workspaces_outbox_events", ADD CONSTRAINT "revenue_outbox_events_revenue_workspaces_outbox_events" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_outbox_events" DROP CONSTRAINT "revenue_outbox_events_users_revenue_outbox_events", ADD CONSTRAINT "revenue_outbox_events_users_revenue_outbox_events" FOREIGN KEY ("user_revenue_outbox_events") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_trust_events" DROP CONSTRAINT "revenue_trust_events_revenue_workspaces_trust_events", ADD CONSTRAINT "revenue_trust_events_revenue_workspaces_trust_events" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_trust_events" DROP CONSTRAINT "revenue_trust_events_users_revenue_trust_events", ADD CONSTRAINT "revenue_trust_events_users_revenue_trust_events" FOREIGN KEY ("user_revenue_trust_events") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_workspace_members" DROP CONSTRAINT "revenue_workspace_members_revenue_workspaces_members", ADD CONSTRAINT "revenue_workspace_members_revenue_workspaces_members" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "revenue_workspace_members" DROP CONSTRAINT "revenue_workspace_members_users_revenue_workspace_members", ADD CONSTRAINT "revenue_workspace_members_users_revenue_workspace_members" FOREIGN KEY ("user_revenue_workspace_members") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "subscriptions" DROP CONSTRAINT "subscriptions_users_subscription", ADD CONSTRAINT "subscriptions_users_subscription" FOREIGN KEY ("user_subscription") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "tenant_evidence_keys" DROP CONSTRAINT "tenant_evidence_keys_revenue_workspaces_evidence_keys", ADD CONSTRAINT "tenant_evidence_keys_revenue_workspaces_evidence_keys" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "tenant_evidence_keys" DROP CONSTRAINT "tenant_evidence_keys_users_tenant_evidence_keys", ADD CONSTRAINT "tenant_evidence_keys_users_tenant_evidence_keys" FOREIGN KEY ("user_tenant_evidence_keys") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "voice_api_keys" DROP CONSTRAINT "voice_api_keys_users_voice_api_keys", ADD CONSTRAINT "voice_api_keys_users_voice_api_keys" FOREIGN KEY ("user_voice_api_keys") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "voice_sync_items" DROP CONSTRAINT "voice_sync_items_users_voice_sync_items", ADD CONSTRAINT "voice_sync_items_users_voice_sync_items" FOREIGN KEY ("user_voice_sync_items") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "workspace_feature_controls" DROP CONSTRAINT "workspace_feature_controls_revenue_workspaces_feature_controls", ADD CONSTRAINT "workspace_feature_controls_revenue_workspaces_feature_controls" FOREIGN KEY ("revenue_workspace_id") REFERENCES "revenue_workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE "workspace_feature_controls" DROP CONSTRAINT "workspace_feature_controls_users_workspace_feature_controls", ADD CONSTRAINT "workspace_feature_controls_users_workspace_feature_controls" FOREIGN KEY ("user_workspace_feature_controls") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
