// Code generated by ent, DO NOT EDIT.

package actionproposal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the actionproposal type in the database.
	Label = "action_proposal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldParamsJSON holds the string denoting the params_json field in the database.
	FieldParamsJSON = "params_json"
	// FieldFinancial holds the string denoting the financial field in the database.
	FieldFinancial = "financial"
	// FieldRationale holds the string denoting the rationale field in the database.
	FieldRationale = "rationale"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCorrelationID holds the string denoting the correlation_id field in the database.
	FieldCorrelationID = "correlation_id"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldOriginRunID holds the string denoting the origin_run_id field in the database.
	FieldOriginRunID = "origin_run_id"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldApprovedAt holds the string denoting the approved_at field in the database.
	FieldApprovedAt = "approved_at"
	// FieldExecutedAt holds the string denoting the executed_at field in the database.
	FieldExecutedAt = "executed_at"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldResultRef holds the string denoting the result_ref field in the database.
	FieldResultRef = "result_ref"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the actionproposal in the database.
	Table = "action_proposals"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "action_proposals"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_action_proposals"
)

// Columns holds all SQL columns for actionproposal fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTarget,
	FieldKind,
	FieldParamsJSON,
	FieldFinancial,
	FieldRationale,
	FieldStatus,
	FieldCorrelationID,
	FieldEntityID,
	FieldOriginRunID,
	FieldExpiresAt,
	FieldApprovedAt,
	FieldExecutedAt,
	FieldReason,
	FieldResultRef,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "action_proposals"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_action_proposals",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TargetValidator is a validator for the "target" field. It is called by the builders before save.
	TargetValidator func(string) error
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// ParamsJSONValidator is a validator for the "params_json" field. It is called by the builders before save.
	ParamsJSONValidator func(string) error
	// DefaultFinancial holds the default value on creation for the "financial" field.
	DefaultFinancial bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ActionProposal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByParamsJSON orders the results by the params_json field.
func ByParamsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParamsJSON, opts...).ToFunc()
}

// ByFinancial orders the results by the financial field.
func ByFinancial(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinancial, opts...).ToFunc()
}

// ByRationale orders the results by the rationale field.
func ByRationale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRationale, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCorrelationID orders the results by the correlation_id field.
func ByCorrelationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCorrelationID, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByOriginRunID orders the results by the origin_run_id field.
func ByOriginRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginRunID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByApprovedAt orders the results by the approved_at field.
func ByApprovedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedAt, opts...).ToFunc()
}

// ByExecutedAt orders the results by the executed_at field.
func ByExecutedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutedAt, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByResultRef orders the results by the result_ref field.
func ByResultRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultRef, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
