{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "oauth-consent.fullname" . }}
  labels:
    {{- include "oauth-consent.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "oauth-consent.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - { protocol: TCP, port: {{ .Values.port }} }
  egress:
    - ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
    - ports:
        - { protocol: TCP, port: 443 }
        - { protocol: TCP, port: 4445 }
    {{- range .Values.networkPolicy.postgresql.cidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
      ports:
        - protocol: TCP
          port: {{ $.Values.networkPolicy.postgresql.port }}
    {{- end }}
{{- end }}
