apiVersion: v1
kind: Service
metadata:
  name: {{ include "oauth-consent.fullname" . }}
  labels:
    {{- include "oauth-consent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "oauth-consent.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
