// Code generated by ent, DO NOT EDIT.

package backgroundtaskartifact

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldUpdatedAt, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldBody, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldRevision, v))
}

// UpdatedByRunID applies equality check predicate on the "updated_by_run_id" field. It's identical to UpdatedByRunIDEQ.
func UpdatedByRunID(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldUpdatedByRunID, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldContentType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLTE(FieldUpdatedAt, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldContainsFold(FieldBody, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLTE(FieldRevision, v))
}

// UpdatedByRunIDEQ applies the EQ predicate on the "updated_by_run_id" field.
func UpdatedByRunIDEQ(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDNEQ applies the NEQ predicate on the "updated_by_run_id" field.
func UpdatedByRunIDNEQ(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNEQ(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDIn applies the In predicate on the "updated_by_run_id" field.
func UpdatedByRunIDIn(vs ...string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldIn(FieldUpdatedByRunID, vs...))
}

// UpdatedByRunIDNotIn applies the NotIn predicate on the "updated_by_run_id" field.
func UpdatedByRunIDNotIn(vs ...string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNotIn(FieldUpdatedByRunID, vs...))
}

// UpdatedByRunIDGT applies the GT predicate on the "updated_by_run_id" field.
func UpdatedByRunIDGT(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGT(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDGTE applies the GTE predicate on the "updated_by_run_id" field.
func UpdatedByRunIDGTE(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGTE(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDLT applies the LT predicate on the "updated_by_run_id" field.
func UpdatedByRunIDLT(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLT(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDLTE applies the LTE predicate on the "updated_by_run_id" field.
func UpdatedByRunIDLTE(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLTE(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDContains applies the Contains predicate on the "updated_by_run_id" field.
func UpdatedByRunIDContains(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldContains(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDHasPrefix applies the HasPrefix predicate on the "updated_by_run_id" field.
func UpdatedByRunIDHasPrefix(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldHasPrefix(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDHasSuffix applies the HasSuffix predicate on the "updated_by_run_id" field.
func UpdatedByRunIDHasSuffix(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldHasSuffix(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDIsNil applies the IsNil predicate on the "updated_by_run_id" field.
func UpdatedByRunIDIsNil() predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldIsNull(FieldUpdatedByRunID))
}

// UpdatedByRunIDNotNil applies the NotNil predicate on the "updated_by_run_id" field.
func UpdatedByRunIDNotNil() predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNotNull(FieldUpdatedByRunID))
}

// UpdatedByRunIDEqualFold applies the EqualFold predicate on the "updated_by_run_id" field.
func UpdatedByRunIDEqualFold(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEqualFold(FieldUpdatedByRunID, v))
}

// UpdatedByRunIDContainsFold applies the ContainsFold predicate on the "updated_by_run_id" field.
func UpdatedByRunIDContainsFold(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldContainsFold(FieldUpdatedByRunID, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.FieldContainsFold(FieldContentType, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.BackgroundTask) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BackgroundTaskArtifact) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BackgroundTaskArtifact) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BackgroundTaskArtifact) predicate.BackgroundTaskArtifact {
	return predicate.BackgroundTaskArtifact(sql.NotPredicates(p))
}
