apiVersion: v1
kind: Service
metadata:
  name: {{ include "rowboat-www.fullname" . }}
  labels:
    {{- include "rowboat-www.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rowboat-www.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      {{- with .Values.service.nodePorts.http }}
      nodePort: {{ . }}
      {{- end }}
