package gqlapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"entgo.io/contrib/entgql"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent"
	"github.com/google/uuid"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id uuid.UUID) (ent.Noder, error) {
	return r.client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []uuid.UUID) ([]ent.Noder, error) {
	return r.client.Noders(ctx, ids)
}

// BackgroundTasks is the resolver for the backgroundTasks field.
func (r *queryResolver) BackgroundTasks(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *ent.BackgroundTaskWhereInput) (*ent.BackgroundTaskConnection, error) {
	panic(fmt.Errorf("not implemented: BackgroundTasks - backgroundTasks"))
}

// BackgroundTaskArtifacts is the resolver for the backgroundTaskArtifacts field.
func (r *queryResolver) BackgroundTaskArtifacts(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *ent.BackgroundTaskArtifactWhereInput) (*ent.BackgroundTaskArtifactConnection, error) {
	panic(fmt.Errorf("not implemented: BackgroundTaskArtifacts - backgroundTaskArtifacts"))
}

// BackgroundTaskRuns is the resolver for the backgroundTaskRuns field.
func (r *queryResolver) BackgroundTaskRuns(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *ent.BackgroundTaskRunWhereInput) (*ent.BackgroundTaskRunConnection, error) {
	panic(fmt.Errorf("not implemented: BackgroundTaskRuns - backgroundTaskRuns"))
}

// BackgroundTaskRunEvents is the resolver for the backgroundTaskRunEvents field.
func (r *queryResolver) BackgroundTaskRunEvents(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *ent.BackgroundTaskRunEventWhereInput) (*ent.BackgroundTaskRunEventConnection, error) {
	panic(fmt.Errorf("not implemented: BackgroundTaskRunEvents - backgroundTaskRunEvents"))
}

// BackgroundTaskScheduleStates is the resolver for the backgroundTaskScheduleStates field.
func (r *queryResolver) BackgroundTaskScheduleStates(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *ent.BackgroundTaskScheduleStateWhereInput) (*ent.BackgroundTaskScheduleStateConnection, error) {
	panic(fmt.Errorf("not implemented: BackgroundTaskScheduleStates - backgroundTaskScheduleStates"))
}

// LlmUsages is the resolver for the llmUsages field.
func (r *queryResolver) LlmUsages(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *ent.LLMUsageWhereInput) (*ent.LLMUsageConnection, error) {
	var opts []ent.LLMUsagePaginateOption
	if where != nil {
		opts = append(opts, ent.WithLLMUsageFilter(where.Filter))
	}
	return r.client.LLMUsage.Query().Paginate(ctx, after, first, before, last, opts...)
}

// McpConnections is the resolver for the mcpConnections field.
func (r *queryResolver) McpConnections(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *ent.MCPConnectionWhereInput) (*ent.MCPConnectionConnection, error) {
	var opts []ent.MCPConnectionPaginateOption
	if where != nil {
		opts = append(opts, ent.WithMCPConnectionFilter(where.Filter))
	}
	return r.client.MCPConnection.Query().Paginate(ctx, after, first, before, last, opts...)
}

// BillingSubscriptions is the resolver for the billingSubscriptions field.
func (r *queryResolver) BillingSubscriptions(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *ent.BillingSubscriptionWhereInput) (*ent.BillingSubscriptionConnection, error) {
	var opts []ent.BillingSubscriptionPaginateOption
	if where != nil {
		opts = append(opts, ent.WithBillingSubscriptionFilter(where.Filter))
	}
	return r.client.Subscription.Query().Paginate(ctx, after, first, before, last, opts...)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, where *ent.UserWhereInput) (*ent.UserConnection, error) {
	var opts []ent.UserPaginateOption
	if where != nil {
		opts = append(opts, ent.WithUserFilter(where.Filter))
	}
	return r.client.User.Query().Paginate(ctx, after, first, before, last, opts...)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
