#!/bin/sh
set -eu

ROWBOAT_WWW_PUBLIC_API_BASE_URL="${ROWBOAT_WWW_PUBLIC_API_BASE_URL:-${ROWBOATX_PUBLIC_API_BASE_URL:-${ROWBOATX_API_BASE_URL:-https://api.oppulence.io}}}"
ROWBOAT_WWW_API_PROXY_URL="${ROWBOAT_WWW_API_PROXY_URL:-${ROWBOATX_API_PROXY_URL:-${ROWBOATX_API_BASE_URL:-https://api.oppulence.io}}}"
ROWBOAT_WWW_PUBLIC_API_BASE_URL="${ROWBOAT_WWW_PUBLIC_API_BASE_URL%/}"
ROWBOAT_WWW_API_PROXY_URL="${ROWBOAT_WWW_API_PROXY_URL%/}"
ROWBOAT_WWW_PORT="${ROWBOAT_WWW_PORT:-${ROWBOATX_PORT:-8080}}"

export ROWBOAT_WWW_PUBLIC_API_BASE_URL
export ROWBOAT_WWW_API_PROXY_URL
export PORT="${ROWBOAT_WWW_PORT}"
export HOSTNAME=0.0.0.0

exec node server.js
