{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rowboat-api.fullname" . }}
  labels:
    {{- include "rowboat-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "rowboat-api.name" . }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
