apiVersion: v1
kind: Service
metadata:
  name: {{ include "rowboat-api.fullname" . }}
  labels:
    {{- include "rowboat-api.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rowboat-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: grpc
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
