-- RFC 031 Layer 1: cloud mail metadata index (no bodies). Thread- and
-- message-level metadata for scanned threads; the reply-state machine runs
-- on this. Bodies live only in the short-TTL cache (Layer 3); quotes in
-- revenue_evidences (Layer 4). Dropped when the user disconnects Gmail.

CREATE TABLE IF NOT EXISTS `mail_threads` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `provider` text NOT NULL DEFAULT ('gmail'), `provider_thread_id` text NOT NULL, `subject` text NULL, `counterparty_email` text NULL, `account_domain` text NULL, `labels` json NOT NULL, `reply_state` text NOT NULL DEFAULT ('quiet'), `last_direction` text NULL, `last_activity_at` datetime NULL, `message_count` integer NOT NULL DEFAULT (0), `outbound_count` integer NOT NULL DEFAULT (0), `inbound_count` integer NOT NULL DEFAULT (0), `relationship_id` uuid NULL, `user_mail_threads` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `mail_threads_relationships_mail_threads` FOREIGN KEY (`relationship_id`) REFERENCES `relationships` (`id`) ON DELETE SET NULL, CONSTRAINT `mail_threads_users_mail_threads` FOREIGN KEY (`user_mail_threads`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX IF NOT EXISTS `mailthread_provider_provider_thread_id_user_mail_threads` ON `mail_threads` (`provider`, `provider_thread_id`, `user_mail_threads`);
CREATE INDEX IF NOT EXISTS `mailthread_last_activity_at_user_mail_threads` ON `mail_threads` (`last_activity_at`, `user_mail_threads`);
CREATE TABLE IF NOT EXISTS `mail_message_meta` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `provider_message_id` text NOT NULL, `occurred_at` datetime NOT NULL, `direction` text NOT NULL, `from_addr` text NULL, `to_addr` text NULL, `subject` text NULL, `labels` json NOT NULL, `mail_thread_id` uuid NOT NULL, `user_mail_message_metas` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `mail_message_meta_mail_threads_messages` FOREIGN KEY (`mail_thread_id`) REFERENCES `mail_threads` (`id`) ON DELETE NO ACTION, CONSTRAINT `mail_message_meta_users_mail_message_metas` FOREIGN KEY (`user_mail_message_metas`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX IF NOT EXISTS `mailmessagemeta_provider_message_id_user_mail_message_metas` ON `mail_message_meta` (`provider_message_id`, `user_mail_message_metas`);
