-- RFC 030 revenue memory and outbound governance domain: workspace mapping,
-- relationships, evidence, commitments, the Revenue Action Queue with
-- revisions and immutable policy decision snapshots, append-only outcomes,
-- and the transactional outbox. Tables are ordered so foreign-key targets
-- exist before their dependents.

CREATE TABLE IF NOT EXISTS `revenue_workspaces` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `workos_org_id` text NULL, `outbound_organization_id` text NULL, `outbound_workspace_id` text NULL, `mode` text NOT NULL DEFAULT ('local'), `status` text NOT NULL DEFAULT ('active'), `last_verified_at` datetime NULL, `user_revenue_workspaces` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `revenue_workspaces_users_revenue_workspaces` FOREIGN KEY (`user_revenue_workspaces`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX IF NOT EXISTS `revenue_workspaces_outbound_workspace_id_key` ON `revenue_workspaces` (`outbound_workspace_id`);
CREATE TABLE IF NOT EXISTS `revenue_workspace_members` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `role` text NOT NULL DEFAULT ('member'), `outbound_account_id` text NULL, `status` text NOT NULL DEFAULT ('active'), `revenue_workspace_id` uuid NOT NULL, `user_revenue_workspace_members` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `revenue_workspace_members_revenue_workspaces_members` FOREIGN KEY (`revenue_workspace_id`) REFERENCES `revenue_workspaces` (`id`) ON DELETE NO ACTION, CONSTRAINT `revenue_workspace_members_users_revenue_workspace_members` FOREIGN KEY (`user_revenue_workspace_members`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX IF NOT EXISTS `revenueworkspacemember_revenue__f46244d2fcbd1226a029efb2ccf4c064` ON `revenue_workspace_members` (`revenue_workspace_id`, `user_revenue_workspace_members`);
CREATE TABLE IF NOT EXISTS `relationships` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `kind` text NOT NULL, `display_name` text NOT NULL, `primary_email` text NULL, `account_domain` text NULL, `outbound_lead_id` text NULL, `outbound_account_ref` text NULL, `resource_refs` json NOT NULL, `summary` text NULL, `last_touch_at` datetime NULL, `next_action_at` datetime NULL, `status` text NOT NULL DEFAULT ('active'), `revenue_workspace_id` uuid NOT NULL, `user_relationships` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `relationships_revenue_workspaces_relationships` FOREIGN KEY (`revenue_workspace_id`) REFERENCES `revenue_workspaces` (`id`) ON DELETE NO ACTION, CONSTRAINT `relationships_users_relationships` FOREIGN KEY (`user_relationships`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE INDEX IF NOT EXISTS `relationship_primary_email_revenue_workspace_id` ON `relationships` (`primary_email`, `revenue_workspace_id`);
CREATE INDEX IF NOT EXISTS `relationship_status_revenue_workspace_id` ON `relationships` (`status`, `revenue_workspace_id`);
CREATE TABLE IF NOT EXISTS `revenue_evidences` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `source` text NOT NULL, `source_account_id` text NULL, `source_record_id` text NOT NULL, `source_uri` text NULL, `content_hash` text NOT NULL, `excerpt` text NULL, `payload_ciphertext` blob NULL, `occurred_at` datetime NOT NULL, `observed_at` datetime NOT NULL, `external_evidence_refs` json NOT NULL, `revenue_workspace_id` uuid NOT NULL, `user_revenue_evidences` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `revenue_evidences_revenue_workspaces_evidences` FOREIGN KEY (`revenue_workspace_id`) REFERENCES `revenue_workspaces` (`id`) ON DELETE NO ACTION, CONSTRAINT `revenue_evidences_users_revenue_evidences` FOREIGN KEY (`user_revenue_evidences`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX IF NOT EXISTS `revenueevidence_source_source_r_9c29dc0e2c6e018629a5b95c5f67b4cf` ON `revenue_evidences` (`source`, `source_record_id`, `content_hash`, `revenue_workspace_id`);
CREATE TABLE IF NOT EXISTS `commitments` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `direction` text NOT NULL, `text` text NOT NULL, `status` text NOT NULL DEFAULT ('open'), `due_at` datetime NULL, `confidence` real NOT NULL, `user_confirmed` bool NOT NULL DEFAULT (false), `relationship_id` uuid NOT NULL, `revenue_workspace_id` uuid NOT NULL, `user_commitments` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `commitments_relationships_commitments` FOREIGN KEY (`relationship_id`) REFERENCES `relationships` (`id`) ON DELETE NO ACTION, CONSTRAINT `commitments_revenue_workspaces_commitments` FOREIGN KEY (`revenue_workspace_id`) REFERENCES `revenue_workspaces` (`id`) ON DELETE NO ACTION, CONSTRAINT `commitments_users_commitments` FOREIGN KEY (`user_commitments`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE TABLE IF NOT EXISTS `revenue_actions` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `action_type` text NOT NULL, `channel` text NOT NULL, `detector` text NOT NULL, `dedupe_key` text NOT NULL, `revision` integer NOT NULL DEFAULT (1), `revision_hash` text NOT NULL, `reason` text NOT NULL, `recipient_email` text NULL, `proposed_subject` text NULL, `proposed_message` text NULL, `sender_account_ref` text NULL, `assigned_user_id` uuid NULL, `priority_score` integer NOT NULL, `priority_components_json` text NULL, `queue_status` text NOT NULL DEFAULT ('open'), `policy_status` text NOT NULL DEFAULT ('pending'), `approval_status` text NOT NULL DEFAULT ('pending'), `execution_status` text NOT NULL DEFAULT ('pending'), `execution_owner` text NOT NULL DEFAULT ('rowboat'), `approved_revision` integer NULL, `approved_decision_id` uuid NULL, `approved_by` uuid NULL, `approved_at` datetime NULL, `execution_idempotency_key` text NULL, `execution_mode` text NOT NULL DEFAULT ('draft'), `provider_message_id` text NULL, `provider_thread_id` text NULL, `executed_at` datetime NULL, `execution_error` text NULL, `dismiss_reason` text NULL, `snoozed_until` datetime NULL, `due_at` datetime NULL, `handled_at` datetime NULL, `relationship_id` uuid NOT NULL, `revenue_workspace_id` uuid NOT NULL, `user_revenue_actions` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `revenue_actions_relationships_actions` FOREIGN KEY (`relationship_id`) REFERENCES `relationships` (`id`) ON DELETE NO ACTION, CONSTRAINT `revenue_actions_revenue_workspaces_actions` FOREIGN KEY (`revenue_workspace_id`) REFERENCES `revenue_workspaces` (`id`) ON DELETE NO ACTION, CONSTRAINT `revenue_actions_users_revenue_actions` FOREIGN KEY (`user_revenue_actions`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX IF NOT EXISTS `revenueaction_dedupe_key_revenue_workspace_id` ON `revenue_actions` (`dedupe_key`, `revenue_workspace_id`);
CREATE INDEX IF NOT EXISTS `revenueaction_queue_status_priority_score_revenue_workspace_id` ON `revenue_actions` (`queue_status`, `priority_score`, `revenue_workspace_id`);
CREATE TABLE IF NOT EXISTS `revenue_action_revisions` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `revision` integer NOT NULL, `revision_hash` text NOT NULL, `action_type` text NOT NULL, `channel` text NOT NULL, `recipient_email` text NULL, `reason` text NULL, `proposed_subject` text NULL, `proposed_message` text NULL, `sender_account_ref` text NULL, `assigned_user_id` uuid NULL, `created_by` uuid NULL, `revenue_action_id` uuid NOT NULL, `user_revenue_action_revisions` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `revenue_action_revisions_revenue_actions_revisions` FOREIGN KEY (`revenue_action_id`) REFERENCES `revenue_actions` (`id`) ON DELETE NO ACTION, CONSTRAINT `revenue_action_revisions_users_revenue_action_revisions` FOREIGN KEY (`user_revenue_action_revisions`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX IF NOT EXISTS `revenueactionrevision_revision_revenue_action_id` ON `revenue_action_revisions` (`revision`, `revenue_action_id`);
CREATE TABLE IF NOT EXISTS `policy_decision_snapshots` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `action_revision` integer NOT NULL, `revision_hash` text NOT NULL, `status` text NOT NULL, `outbound_lead_id` text NULL, `verification_json` text NULL, `suppression_json` text NULL, `research_json` text NULL, `crm_json` text NULL, `reason_codes` json NOT NULL, `evidence_refs` json NOT NULL, `evaluated_at` datetime NOT NULL, `expires_at` datetime NOT NULL, `response_hash` text NOT NULL, `revenue_action_id` uuid NOT NULL, `revenue_workspace_id` uuid NOT NULL, `user_policy_decision_snapshots` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `policy_decision_snapshots_revenue_actions_decisions` FOREIGN KEY (`revenue_action_id`) REFERENCES `revenue_actions` (`id`) ON DELETE NO ACTION, CONSTRAINT `policy_decision_snapshots_revenue_workspaces_decisions` FOREIGN KEY (`revenue_workspace_id`) REFERENCES `revenue_workspaces` (`id`) ON DELETE NO ACTION, CONSTRAINT `policy_decision_snapshots_users_policy_decision_snapshots` FOREIGN KEY (`user_policy_decision_snapshots`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE TABLE IF NOT EXISTS `action_outcomes` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `kind` text NOT NULL, `source` text NOT NULL, `source_event_id` text NOT NULL, `occurred_at` datetime NOT NULL, `metadata_json` text NULL, `revenue_action_id` uuid NOT NULL, `revenue_workspace_id` uuid NOT NULL, `user_action_outcomes` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `action_outcomes_revenue_actions_outcomes` FOREIGN KEY (`revenue_action_id`) REFERENCES `revenue_actions` (`id`) ON DELETE NO ACTION, CONSTRAINT `action_outcomes_revenue_workspaces_outcomes` FOREIGN KEY (`revenue_workspace_id`) REFERENCES `revenue_workspaces` (`id`) ON DELETE NO ACTION, CONSTRAINT `action_outcomes_users_action_outcomes` FOREIGN KEY (`user_action_outcomes`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX IF NOT EXISTS `actionoutcome_source_source_event_id_revenue_action_id` ON `action_outcomes` (`source`, `source_event_id`, `revenue_action_id`);
CREATE TABLE IF NOT EXISTS `revenue_outbox_events` (`id` uuid NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `event_type` text NOT NULL, `schema_version` integer NOT NULL DEFAULT (1), `action_id` uuid NULL, `correlation_id` text NULL, `causation_id` text NULL, `idempotency_key` text NOT NULL, `payload_json` text NULL, `occurred_at` datetime NOT NULL, `delivery_status` text NOT NULL DEFAULT ('pending'), `attempts` integer NOT NULL DEFAULT (0), `next_attempt_at` datetime NULL, `last_error` text NULL, `revenue_workspace_id` uuid NOT NULL, `user_revenue_outbox_events` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `revenue_outbox_events_revenue_workspaces_outbox_events` FOREIGN KEY (`revenue_workspace_id`) REFERENCES `revenue_workspaces` (`id`) ON DELETE NO ACTION, CONSTRAINT `revenue_outbox_events_users_revenue_outbox_events` FOREIGN KEY (`user_revenue_outbox_events`) REFERENCES `users` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX IF NOT EXISTS `revenue_outbox_events_idempotency_key_key` ON `revenue_outbox_events` (`idempotency_key`);
CREATE INDEX IF NOT EXISTS `revenueoutboxevent_delivery_status_next_attempt_at` ON `revenue_outbox_events` (`delivery_status`, `next_attempt_at`);
CREATE TABLE IF NOT EXISTS `commitment_evidences` (`commitment_id` uuid NOT NULL, `revenue_evidence_id` uuid NOT NULL, PRIMARY KEY (`commitment_id`, `revenue_evidence_id`), CONSTRAINT `commitment_evidences_commitment_id` FOREIGN KEY (`commitment_id`) REFERENCES `commitments` (`id`) ON DELETE CASCADE, CONSTRAINT `commitment_evidences_revenue_evidence_id` FOREIGN KEY (`revenue_evidence_id`) REFERENCES `revenue_evidences` (`id`) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS `relationship_evidences` (`relationship_id` uuid NOT NULL, `revenue_evidence_id` uuid NOT NULL, PRIMARY KEY (`relationship_id`, `revenue_evidence_id`), CONSTRAINT `relationship_evidences_relationship_id` FOREIGN KEY (`relationship_id`) REFERENCES `relationships` (`id`) ON DELETE CASCADE, CONSTRAINT `relationship_evidences_revenue_evidence_id` FOREIGN KEY (`revenue_evidence_id`) REFERENCES `revenue_evidences` (`id`) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS `revenue_action_evidences` (`revenue_action_id` uuid NOT NULL, `revenue_evidence_id` uuid NOT NULL, PRIMARY KEY (`revenue_action_id`, `revenue_evidence_id`), CONSTRAINT `revenue_action_evidences_revenue_action_id` FOREIGN KEY (`revenue_action_id`) REFERENCES `revenue_actions` (`id`) ON DELETE CASCADE, CONSTRAINT `revenue_action_evidences_revenue_evidence_id` FOREIGN KEY (`revenue_evidence_id`) REFERENCES `revenue_evidences` (`id`) ON DELETE CASCADE);
