// Code generated by ent, DO NOT EDIT.

package creditledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldID, id))
}

// Delta applies equality check predicate on the "delta" field. It's identical to DeltaEQ.
func Delta(v int) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldDelta, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldReason, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldRequestID, v))
}

// Ts applies equality check predicate on the "ts" field. It's identical to TsEQ.
func Ts(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldTs, v))
}

// DeltaEQ applies the EQ predicate on the "delta" field.
func DeltaEQ(v int) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldDelta, v))
}

// DeltaNEQ applies the NEQ predicate on the "delta" field.
func DeltaNEQ(v int) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldDelta, v))
}

// DeltaIn applies the In predicate on the "delta" field.
func DeltaIn(vs ...int) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldDelta, vs...))
}

// DeltaNotIn applies the NotIn predicate on the "delta" field.
func DeltaNotIn(vs ...int) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldDelta, vs...))
}

// DeltaGT applies the GT predicate on the "delta" field.
func DeltaGT(v int) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldDelta, v))
}

// DeltaGTE applies the GTE predicate on the "delta" field.
func DeltaGTE(v int) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldDelta, v))
}

// DeltaLT applies the LT predicate on the "delta" field.
func DeltaLT(v int) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldDelta, v))
}

// DeltaLTE applies the LTE predicate on the "delta" field.
func DeltaLTE(v int) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldDelta, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldContainsFold(FieldReason, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v uuid.UUID) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldRequestID, v))
}

// TsEQ applies the EQ predicate on the "ts" field.
func TsEQ(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldEQ(FieldTs, v))
}

// TsNEQ applies the NEQ predicate on the "ts" field.
func TsNEQ(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNEQ(FieldTs, v))
}

// TsIn applies the In predicate on the "ts" field.
func TsIn(vs ...time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldIn(FieldTs, vs...))
}

// TsNotIn applies the NotIn predicate on the "ts" field.
func TsNotIn(vs ...time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldNotIn(FieldTs, vs...))
}

// TsGT applies the GT predicate on the "ts" field.
func TsGT(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGT(FieldTs, v))
}

// TsGTE applies the GTE predicate on the "ts" field.
func TsGTE(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldGTE(FieldTs, v))
}

// TsLT applies the LT predicate on the "ts" field.
func TsLT(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLT(FieldTs, v))
}

// TsLTE applies the LTE predicate on the "ts" field.
func TsLTE(v time.Time) predicate.CreditLedger {
	return predicate.CreditLedger(sql.FieldLTE(FieldTs, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CreditLedger {
	return predicate.CreditLedger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CreditLedger {
	return predicate.CreditLedger(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CreditLedger) predicate.CreditLedger {
	return predicate.CreditLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CreditLedger) predicate.CreditLedger {
	return predicate.CreditLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CreditLedger) predicate.CreditLedger {
	return predicate.CreditLedger(sql.NotPredicates(p))
}
