// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agentdefinition"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agentsession"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/user"
	"github.com/google/uuid"
)

// AgentDefinitionCreate is the builder for creating a AgentDefinition entity.
type AgentDefinitionCreate struct {
	config
	mutation *AgentDefinitionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentDefinitionCreate) SetCreatedAt(v time.Time) *AgentDefinitionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableCreatedAt(v *time.Time) *AgentDefinitionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentDefinitionCreate) SetUpdatedAt(v time.Time) *AgentDefinitionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableUpdatedAt(v *time.Time) *AgentDefinitionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *AgentDefinitionCreate) SetSlug(v string) *AgentDefinitionCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AgentDefinitionCreate) SetName(v string) *AgentDefinitionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetInstructions sets the "instructions" field.
func (_c *AgentDefinitionCreate) SetInstructions(v string) *AgentDefinitionCreate {
	_c.mutation.SetInstructions(v)
	return _c
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableInstructions(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetInstructions(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *AgentDefinitionCreate) SetModel(v string) *AgentDefinitionCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableModel(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AgentDefinitionCreate) SetProvider(v string) *AgentDefinitionCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableProvider(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetLimitsJSON sets the "limits_json" field.
func (_c *AgentDefinitionCreate) SetLimitsJSON(v string) *AgentDefinitionCreate {
	_c.mutation.SetLimitsJSON(v)
	return _c
}

// SetNillableLimitsJSON sets the "limits_json" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableLimitsJSON(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetLimitsJSON(*v)
	}
	return _c
}

// SetEnabledTools sets the "enabled_tools" field.
func (_c *AgentDefinitionCreate) SetEnabledTools(v []string) *AgentDefinitionCreate {
	_c.mutation.SetEnabledTools(v)
	return _c
}

// SetToolsJSON sets the "tools_json" field.
func (_c *AgentDefinitionCreate) SetToolsJSON(v string) *AgentDefinitionCreate {
	_c.mutation.SetToolsJSON(v)
	return _c
}

// SetNillableToolsJSON sets the "tools_json" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableToolsJSON(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetToolsJSON(*v)
	}
	return _c
}

// SetSubagentRefs sets the "subagent_refs" field.
func (_c *AgentDefinitionCreate) SetSubagentRefs(v []string) *AgentDefinitionCreate {
	_c.mutation.SetSubagentRefs(v)
	return _c
}

// SetChannelBindings sets the "channel_bindings" field.
func (_c *AgentDefinitionCreate) SetChannelBindings(v string) *AgentDefinitionCreate {
	_c.mutation.SetChannelBindings(v)
	return _c
}

// SetNillableChannelBindings sets the "channel_bindings" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableChannelBindings(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetChannelBindings(*v)
	}
	return _c
}

// SetConnectorReqs sets the "connector_reqs" field.
func (_c *AgentDefinitionCreate) SetConnectorReqs(v []string) *AgentDefinitionCreate {
	_c.mutation.SetConnectorReqs(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *AgentDefinitionCreate) SetSource(v string) *AgentDefinitionCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableSource(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetForkedFrom sets the "forked_from" field.
func (_c *AgentDefinitionCreate) SetForkedFrom(v string) *AgentDefinitionCreate {
	_c.mutation.SetForkedFrom(v)
	return _c
}

// SetNillableForkedFrom sets the "forked_from" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableForkedFrom(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetForkedFrom(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *AgentDefinitionCreate) SetRevision(v int) *AgentDefinitionCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableRevision(v *int) *AgentDefinitionCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetSourceFormat sets the "source_format" field.
func (_c *AgentDefinitionCreate) SetSourceFormat(v string) *AgentDefinitionCreate {
	_c.mutation.SetSourceFormat(v)
	return _c
}

// SetNillableSourceFormat sets the "source_format" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableSourceFormat(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetSourceFormat(*v)
	}
	return _c
}

// SetRawSource sets the "raw_source" field.
func (_c *AgentDefinitionCreate) SetRawSource(v string) *AgentDefinitionCreate {
	_c.mutation.SetRawSource(v)
	return _c
}

// SetNillableRawSource sets the "raw_source" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableRawSource(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetRawSource(*v)
	}
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *AgentDefinitionCreate) SetContentHash(v string) *AgentDefinitionCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableContentHash(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetContentHash(*v)
	}
	return _c
}

// SetManagedBy sets the "managed_by" field.
func (_c *AgentDefinitionCreate) SetManagedBy(v string) *AgentDefinitionCreate {
	_c.mutation.SetManagedBy(v)
	return _c
}

// SetNillableManagedBy sets the "managed_by" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableManagedBy(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetManagedBy(*v)
	}
	return _c
}

// SetAgentSyncState sets the "agent_sync_state" field.
func (_c *AgentDefinitionCreate) SetAgentSyncState(v string) *AgentDefinitionCreate {
	_c.mutation.SetAgentSyncState(v)
	return _c
}

// SetNillableAgentSyncState sets the "agent_sync_state" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableAgentSyncState(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetAgentSyncState(*v)
	}
	return _c
}

// SetAgentSyncError sets the "agent_sync_error" field.
func (_c *AgentDefinitionCreate) SetAgentSyncError(v string) *AgentDefinitionCreate {
	_c.mutation.SetAgentSyncError(v)
	return _c
}

// SetNillableAgentSyncError sets the "agent_sync_error" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableAgentSyncError(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetAgentSyncError(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentDefinitionCreate) SetID(v uuid.UUID) *AgentDefinitionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableID(v *uuid.UUID) *AgentDefinitionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *AgentDefinitionCreate) SetUserID(id uuid.UUID) *AgentDefinitionCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AgentDefinitionCreate) SetUser(v *User) *AgentDefinitionCreate {
	return _c.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the AgentSession entity by IDs.
func (_c *AgentDefinitionCreate) AddSessionIDs(ids ...uuid.UUID) *AgentDefinitionCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the AgentSession entity.
func (_c *AgentDefinitionCreate) AddSessions(v ...*AgentSession) *AgentDefinitionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// Mutation returns the AgentDefinitionMutation object of the builder.
func (_c *AgentDefinitionCreate) Mutation() *AgentDefinitionMutation {
	return _c.mutation
}

// Save creates the AgentDefinition in the database.
func (_c *AgentDefinitionCreate) Save(ctx context.Context) (*AgentDefinition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentDefinitionCreate) SaveX(ctx context.Context) *AgentDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentDefinitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentDefinitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentDefinitionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentdefinition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agentdefinition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := agentdefinition.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := agentdefinition.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.SourceFormat(); !ok {
		v := agentdefinition.DefaultSourceFormat
		_c.mutation.SetSourceFormat(v)
	}
	if _, ok := _c.mutation.ManagedBy(); !ok {
		v := agentdefinition.DefaultManagedBy
		_c.mutation.SetManagedBy(v)
	}
	if _, ok := _c.mutation.AgentSyncState(); !ok {
		v := agentdefinition.DefaultAgentSyncState
		_c.mutation.SetAgentSyncState(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agentdefinition.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentDefinitionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentDefinition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentDefinition.updated_at"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "AgentDefinition.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := agentdefinition.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AgentDefinition.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agentdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LimitsJSON(); ok {
		if err := agentdefinition.LimitsJSONValidator(v); err != nil {
			return &ValidationError{Name: "limits_json", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.limits_json": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ToolsJSON(); ok {
		if err := agentdefinition.ToolsJSONValidator(v); err != nil {
			return &ValidationError{Name: "tools_json", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.tools_json": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ChannelBindings(); ok {
		if err := agentdefinition.ChannelBindingsValidator(v); err != nil {
			return &ValidationError{Name: "channel_bindings", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.channel_bindings": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "AgentDefinition.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := agentdefinition.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "AgentDefinition.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := agentdefinition.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceFormat(); !ok {
		return &ValidationError{Name: "source_format", err: errors.New(`ent: missing required field "AgentDefinition.source_format"`)}
	}
	if v, ok := _c.mutation.SourceFormat(); ok {
		if err := agentdefinition.SourceFormatValidator(v); err != nil {
			return &ValidationError{Name: "source_format", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.source_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ManagedBy(); !ok {
		return &ValidationError{Name: "managed_by", err: errors.New(`ent: missing required field "AgentDefinition.managed_by"`)}
	}
	if v, ok := _c.mutation.ManagedBy(); ok {
		if err := agentdefinition.ManagedByValidator(v); err != nil {
			return &ValidationError{Name: "managed_by", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.managed_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AgentSyncState(); !ok {
		return &ValidationError{Name: "agent_sync_state", err: errors.New(`ent: missing required field "AgentDefinition.agent_sync_state"`)}
	}
	if v, ok := _c.mutation.AgentSyncState(); ok {
		if err := agentdefinition.AgentSyncStateValidator(v); err != nil {
			return &ValidationError{Name: "agent_sync_state", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.agent_sync_state": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AgentDefinition.user"`)}
	}
	return nil
}

func (_c *AgentDefinitionCreate) sqlSave(ctx context.Context) (*AgentDefinition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentDefinitionCreate) createSpec() (*AgentDefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentDefinition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentdefinition.Table, sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentdefinition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agentdefinition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(agentdefinition.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agentdefinition.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Instructions(); ok {
		_spec.SetField(agentdefinition.FieldInstructions, field.TypeString, value)
		_node.Instructions = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(agentdefinition.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(agentdefinition.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.LimitsJSON(); ok {
		_spec.SetField(agentdefinition.FieldLimitsJSON, field.TypeString, value)
		_node.LimitsJSON = value
	}
	if value, ok := _c.mutation.EnabledTools(); ok {
		_spec.SetField(agentdefinition.FieldEnabledTools, field.TypeJSON, value)
		_node.EnabledTools = value
	}
	if value, ok := _c.mutation.ToolsJSON(); ok {
		_spec.SetField(agentdefinition.FieldToolsJSON, field.TypeString, value)
		_node.ToolsJSON = value
	}
	if value, ok := _c.mutation.SubagentRefs(); ok {
		_spec.SetField(agentdefinition.FieldSubagentRefs, field.TypeJSON, value)
		_node.SubagentRefs = value
	}
	if value, ok := _c.mutation.ChannelBindings(); ok {
		_spec.SetField(agentdefinition.FieldChannelBindings, field.TypeString, value)
		_node.ChannelBindings = value
	}
	if value, ok := _c.mutation.ConnectorReqs(); ok {
		_spec.SetField(agentdefinition.FieldConnectorReqs, field.TypeJSON, value)
		_node.ConnectorReqs = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(agentdefinition.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.ForkedFrom(); ok {
		_spec.SetField(agentdefinition.FieldForkedFrom, field.TypeString, value)
		_node.ForkedFrom = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(agentdefinition.FieldRevision, field.TypeInt, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.SourceFormat(); ok {
		_spec.SetField(agentdefinition.FieldSourceFormat, field.TypeString, value)
		_node.SourceFormat = value
	}
	if value, ok := _c.mutation.RawSource(); ok {
		_spec.SetField(agentdefinition.FieldRawSource, field.TypeString, value)
		_node.RawSource = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(agentdefinition.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.ManagedBy(); ok {
		_spec.SetField(agentdefinition.FieldManagedBy, field.TypeString, value)
		_node.ManagedBy = value
	}
	if value, ok := _c.mutation.AgentSyncState(); ok {
		_spec.SetField(agentdefinition.FieldAgentSyncState, field.TypeString, value)
		_node.AgentSyncState = value
	}
	if value, ok := _c.mutation.AgentSyncError(); ok {
		_spec.SetField(agentdefinition.FieldAgentSyncError, field.TypeString, value)
		_node.AgentSyncError = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentdefinition.UserTable,
			Columns: []string{agentdefinition.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_agent_definitions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentdefinition.SessionsTable,
			Columns: []string{agentdefinition.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentDefinition.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentDefinitionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentDefinitionCreate) OnConflict(opts ...sql.ConflictOption) *AgentDefinitionUpsertOne {
	_c.conflict = opts
	return &AgentDefinitionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentDefinition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentDefinitionCreate) OnConflictColumns(columns ...string) *AgentDefinitionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentDefinitionUpsertOne{
		create: _c,
	}
}

type (
	// AgentDefinitionUpsertOne is the builder for "upsert"-ing
	//  one AgentDefinition node.
	AgentDefinitionUpsertOne struct {
		create *AgentDefinitionCreate
	}

	// AgentDefinitionUpsert is the "OnConflict" setter.
	AgentDefinitionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentDefinitionUpsert) SetUpdatedAt(v time.Time) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateUpdatedAt() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldUpdatedAt)
	return u
}

// SetSlug sets the "slug" field.
func (u *AgentDefinitionUpsert) SetSlug(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateSlug() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldSlug)
	return u
}

// SetName sets the "name" field.
func (u *AgentDefinitionUpsert) SetName(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateName() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldName)
	return u
}

// SetInstructions sets the "instructions" field.
func (u *AgentDefinitionUpsert) SetInstructions(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldInstructions, v)
	return u
}

// UpdateInstructions sets the "instructions" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateInstructions() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldInstructions)
	return u
}

// ClearInstructions clears the value of the "instructions" field.
func (u *AgentDefinitionUpsert) ClearInstructions() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldInstructions)
	return u
}

// SetModel sets the "model" field.
func (u *AgentDefinitionUpsert) SetModel(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateModel() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *AgentDefinitionUpsert) ClearModel() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldModel)
	return u
}

// SetProvider sets the "provider" field.
func (u *AgentDefinitionUpsert) SetProvider(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateProvider() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldProvider)
	return u
}

// ClearProvider clears the value of the "provider" field.
func (u *AgentDefinitionUpsert) ClearProvider() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldProvider)
	return u
}

// SetLimitsJSON sets the "limits_json" field.
func (u *AgentDefinitionUpsert) SetLimitsJSON(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldLimitsJSON, v)
	return u
}

// UpdateLimitsJSON sets the "limits_json" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateLimitsJSON() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldLimitsJSON)
	return u
}

// ClearLimitsJSON clears the value of the "limits_json" field.
func (u *AgentDefinitionUpsert) ClearLimitsJSON() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldLimitsJSON)
	return u
}

// SetEnabledTools sets the "enabled_tools" field.
func (u *AgentDefinitionUpsert) SetEnabledTools(v []string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldEnabledTools, v)
	return u
}

// UpdateEnabledTools sets the "enabled_tools" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateEnabledTools() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldEnabledTools)
	return u
}

// ClearEnabledTools clears the value of the "enabled_tools" field.
func (u *AgentDefinitionUpsert) ClearEnabledTools() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldEnabledTools)
	return u
}

// SetToolsJSON sets the "tools_json" field.
func (u *AgentDefinitionUpsert) SetToolsJSON(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldToolsJSON, v)
	return u
}

// UpdateToolsJSON sets the "tools_json" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateToolsJSON() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldToolsJSON)
	return u
}

// ClearToolsJSON clears the value of the "tools_json" field.
func (u *AgentDefinitionUpsert) ClearToolsJSON() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldToolsJSON)
	return u
}

// SetSubagentRefs sets the "subagent_refs" field.
func (u *AgentDefinitionUpsert) SetSubagentRefs(v []string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldSubagentRefs, v)
	return u
}

// UpdateSubagentRefs sets the "subagent_refs" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateSubagentRefs() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldSubagentRefs)
	return u
}

// ClearSubagentRefs clears the value of the "subagent_refs" field.
func (u *AgentDefinitionUpsert) ClearSubagentRefs() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldSubagentRefs)
	return u
}

// SetChannelBindings sets the "channel_bindings" field.
func (u *AgentDefinitionUpsert) SetChannelBindings(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldChannelBindings, v)
	return u
}

// UpdateChannelBindings sets the "channel_bindings" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateChannelBindings() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldChannelBindings)
	return u
}

// ClearChannelBindings clears the value of the "channel_bindings" field.
func (u *AgentDefinitionUpsert) ClearChannelBindings() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldChannelBindings)
	return u
}

// SetConnectorReqs sets the "connector_reqs" field.
func (u *AgentDefinitionUpsert) SetConnectorReqs(v []string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldConnectorReqs, v)
	return u
}

// UpdateConnectorReqs sets the "connector_reqs" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateConnectorReqs() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldConnectorReqs)
	return u
}

// ClearConnectorReqs clears the value of the "connector_reqs" field.
func (u *AgentDefinitionUpsert) ClearConnectorReqs() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldConnectorReqs)
	return u
}

// SetSource sets the "source" field.
func (u *AgentDefinitionUpsert) SetSource(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateSource() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldSource)
	return u
}

// SetForkedFrom sets the "forked_from" field.
func (u *AgentDefinitionUpsert) SetForkedFrom(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldForkedFrom, v)
	return u
}

// UpdateForkedFrom sets the "forked_from" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateForkedFrom() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldForkedFrom)
	return u
}

// ClearForkedFrom clears the value of the "forked_from" field.
func (u *AgentDefinitionUpsert) ClearForkedFrom() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldForkedFrom)
	return u
}

// SetRevision sets the "revision" field.
func (u *AgentDefinitionUpsert) SetRevision(v int) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateRevision() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *AgentDefinitionUpsert) AddRevision(v int) *AgentDefinitionUpsert {
	u.Add(agentdefinition.FieldRevision, v)
	return u
}

// SetSourceFormat sets the "source_format" field.
func (u *AgentDefinitionUpsert) SetSourceFormat(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldSourceFormat, v)
	return u
}

// UpdateSourceFormat sets the "source_format" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateSourceFormat() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldSourceFormat)
	return u
}

// SetRawSource sets the "raw_source" field.
func (u *AgentDefinitionUpsert) SetRawSource(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldRawSource, v)
	return u
}

// UpdateRawSource sets the "raw_source" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateRawSource() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldRawSource)
	return u
}

// ClearRawSource clears the value of the "raw_source" field.
func (u *AgentDefinitionUpsert) ClearRawSource() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldRawSource)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *AgentDefinitionUpsert) SetContentHash(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateContentHash() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldContentHash)
	return u
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *AgentDefinitionUpsert) ClearContentHash() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldContentHash)
	return u
}

// SetManagedBy sets the "managed_by" field.
func (u *AgentDefinitionUpsert) SetManagedBy(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldManagedBy, v)
	return u
}

// UpdateManagedBy sets the "managed_by" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateManagedBy() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldManagedBy)
	return u
}

// SetAgentSyncState sets the "agent_sync_state" field.
func (u *AgentDefinitionUpsert) SetAgentSyncState(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldAgentSyncState, v)
	return u
}

// UpdateAgentSyncState sets the "agent_sync_state" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateAgentSyncState() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldAgentSyncState)
	return u
}

// SetAgentSyncError sets the "agent_sync_error" field.
func (u *AgentDefinitionUpsert) SetAgentSyncError(v string) *AgentDefinitionUpsert {
	u.Set(agentdefinition.FieldAgentSyncError, v)
	return u
}

// UpdateAgentSyncError sets the "agent_sync_error" field to the value that was provided on create.
func (u *AgentDefinitionUpsert) UpdateAgentSyncError() *AgentDefinitionUpsert {
	u.SetExcluded(agentdefinition.FieldAgentSyncError)
	return u
}

// ClearAgentSyncError clears the value of the "agent_sync_error" field.
func (u *AgentDefinitionUpsert) ClearAgentSyncError() *AgentDefinitionUpsert {
	u.SetNull(agentdefinition.FieldAgentSyncError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AgentDefinition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(agentdefinition.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AgentDefinitionUpsertOne) UpdateNewValues() *AgentDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(agentdefinition.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(agentdefinition.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentDefinition.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AgentDefinitionUpsertOne) Ignore() *AgentDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentDefinitionUpsertOne) DoNothing() *AgentDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentDefinitionCreate.OnConflict
// documentation for more info.
func (u *AgentDefinitionUpsertOne) Update(set func(*AgentDefinitionUpsert)) *AgentDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentDefinitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentDefinitionUpsertOne) SetUpdatedAt(v time.Time) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateUpdatedAt() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *AgentDefinitionUpsertOne) SetSlug(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateSlug() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *AgentDefinitionUpsertOne) SetName(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateName() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateName()
	})
}

// SetInstructions sets the "instructions" field.
func (u *AgentDefinitionUpsertOne) SetInstructions(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetInstructions(v)
	})
}

// UpdateInstructions sets the "instructions" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateInstructions() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateInstructions()
	})
}

// ClearInstructions clears the value of the "instructions" field.
func (u *AgentDefinitionUpsertOne) ClearInstructions() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearInstructions()
	})
}

// SetModel sets the "model" field.
func (u *AgentDefinitionUpsertOne) SetModel(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateModel() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AgentDefinitionUpsertOne) ClearModel() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearModel()
	})
}

// SetProvider sets the "provider" field.
func (u *AgentDefinitionUpsertOne) SetProvider(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateProvider() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *AgentDefinitionUpsertOne) ClearProvider() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearProvider()
	})
}

// SetLimitsJSON sets the "limits_json" field.
func (u *AgentDefinitionUpsertOne) SetLimitsJSON(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetLimitsJSON(v)
	})
}

// UpdateLimitsJSON sets the "limits_json" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateLimitsJSON() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateLimitsJSON()
	})
}

// ClearLimitsJSON clears the value of the "limits_json" field.
func (u *AgentDefinitionUpsertOne) ClearLimitsJSON() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearLimitsJSON()
	})
}

// SetEnabledTools sets the "enabled_tools" field.
func (u *AgentDefinitionUpsertOne) SetEnabledTools(v []string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetEnabledTools(v)
	})
}

// UpdateEnabledTools sets the "enabled_tools" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateEnabledTools() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateEnabledTools()
	})
}

// ClearEnabledTools clears the value of the "enabled_tools" field.
func (u *AgentDefinitionUpsertOne) ClearEnabledTools() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearEnabledTools()
	})
}

// SetToolsJSON sets the "tools_json" field.
func (u *AgentDefinitionUpsertOne) SetToolsJSON(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetToolsJSON(v)
	})
}

// UpdateToolsJSON sets the "tools_json" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateToolsJSON() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateToolsJSON()
	})
}

// ClearToolsJSON clears the value of the "tools_json" field.
func (u *AgentDefinitionUpsertOne) ClearToolsJSON() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearToolsJSON()
	})
}

// SetSubagentRefs sets the "subagent_refs" field.
func (u *AgentDefinitionUpsertOne) SetSubagentRefs(v []string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetSubagentRefs(v)
	})
}

// UpdateSubagentRefs sets the "subagent_refs" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateSubagentRefs() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateSubagentRefs()
	})
}

// ClearSubagentRefs clears the value of the "subagent_refs" field.
func (u *AgentDefinitionUpsertOne) ClearSubagentRefs() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearSubagentRefs()
	})
}

// SetChannelBindings sets the "channel_bindings" field.
func (u *AgentDefinitionUpsertOne) SetChannelBindings(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetChannelBindings(v)
	})
}

// UpdateChannelBindings sets the "channel_bindings" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateChannelBindings() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateChannelBindings()
	})
}

// ClearChannelBindings clears the value of the "channel_bindings" field.
func (u *AgentDefinitionUpsertOne) ClearChannelBindings() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearChannelBindings()
	})
}

// SetConnectorReqs sets the "connector_reqs" field.
func (u *AgentDefinitionUpsertOne) SetConnectorReqs(v []string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetConnectorReqs(v)
	})
}

// UpdateConnectorReqs sets the "connector_reqs" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateConnectorReqs() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateConnectorReqs()
	})
}

// ClearConnectorReqs clears the value of the "connector_reqs" field.
func (u *AgentDefinitionUpsertOne) ClearConnectorReqs() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearConnectorReqs()
	})
}

// SetSource sets the "source" field.
func (u *AgentDefinitionUpsertOne) SetSource(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateSource() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateSource()
	})
}

// SetForkedFrom sets the "forked_from" field.
func (u *AgentDefinitionUpsertOne) SetForkedFrom(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetForkedFrom(v)
	})
}

// UpdateForkedFrom sets the "forked_from" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateForkedFrom() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateForkedFrom()
	})
}

// ClearForkedFrom clears the value of the "forked_from" field.
func (u *AgentDefinitionUpsertOne) ClearForkedFrom() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearForkedFrom()
	})
}

// SetRevision sets the "revision" field.
func (u *AgentDefinitionUpsertOne) SetRevision(v int) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *AgentDefinitionUpsertOne) AddRevision(v int) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateRevision() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateRevision()
	})
}

// SetSourceFormat sets the "source_format" field.
func (u *AgentDefinitionUpsertOne) SetSourceFormat(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetSourceFormat(v)
	})
}

// UpdateSourceFormat sets the "source_format" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateSourceFormat() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateSourceFormat()
	})
}

// SetRawSource sets the "raw_source" field.
func (u *AgentDefinitionUpsertOne) SetRawSource(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetRawSource(v)
	})
}

// UpdateRawSource sets the "raw_source" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateRawSource() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateRawSource()
	})
}

// ClearRawSource clears the value of the "raw_source" field.
func (u *AgentDefinitionUpsertOne) ClearRawSource() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearRawSource()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *AgentDefinitionUpsertOne) SetContentHash(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateContentHash() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *AgentDefinitionUpsertOne) ClearContentHash() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearContentHash()
	})
}

// SetManagedBy sets the "managed_by" field.
func (u *AgentDefinitionUpsertOne) SetManagedBy(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetManagedBy(v)
	})
}

// UpdateManagedBy sets the "managed_by" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateManagedBy() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateManagedBy()
	})
}

// SetAgentSyncState sets the "agent_sync_state" field.
func (u *AgentDefinitionUpsertOne) SetAgentSyncState(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetAgentSyncState(v)
	})
}

// UpdateAgentSyncState sets the "agent_sync_state" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateAgentSyncState() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateAgentSyncState()
	})
}

// SetAgentSyncError sets the "agent_sync_error" field.
func (u *AgentDefinitionUpsertOne) SetAgentSyncError(v string) *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetAgentSyncError(v)
	})
}

// UpdateAgentSyncError sets the "agent_sync_error" field to the value that was provided on create.
func (u *AgentDefinitionUpsertOne) UpdateAgentSyncError() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateAgentSyncError()
	})
}

// ClearAgentSyncError clears the value of the "agent_sync_error" field.
func (u *AgentDefinitionUpsertOne) ClearAgentSyncError() *AgentDefinitionUpsertOne {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearAgentSyncError()
	})
}

// Exec executes the query.
func (u *AgentDefinitionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentDefinitionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentDefinitionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AgentDefinitionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AgentDefinitionUpsertOne.ID is not supported by MySQL driver. Use AgentDefinitionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AgentDefinitionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AgentDefinitionCreateBulk is the builder for creating many AgentDefinition entities in bulk.
type AgentDefinitionCreateBulk struct {
	config
	err      error
	builders []*AgentDefinitionCreate
	conflict []sql.ConflictOption
}

// Save creates the AgentDefinition entities in the database.
func (_c *AgentDefinitionCreateBulk) Save(ctx context.Context) ([]*AgentDefinition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentDefinition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentDefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentDefinitionCreateBulk) SaveX(ctx context.Context) []*AgentDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentDefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentDefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentDefinition.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentDefinitionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentDefinitionCreateBulk) OnConflict(opts ...sql.ConflictOption) *AgentDefinitionUpsertBulk {
	_c.conflict = opts
	return &AgentDefinitionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentDefinition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentDefinitionCreateBulk) OnConflictColumns(columns ...string) *AgentDefinitionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentDefinitionUpsertBulk{
		create: _c,
	}
}

// AgentDefinitionUpsertBulk is the builder for "upsert"-ing
// a bulk of AgentDefinition nodes.
type AgentDefinitionUpsertBulk struct {
	create *AgentDefinitionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AgentDefinition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(agentdefinition.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AgentDefinitionUpsertBulk) UpdateNewValues() *AgentDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(agentdefinition.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(agentdefinition.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentDefinition.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AgentDefinitionUpsertBulk) Ignore() *AgentDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentDefinitionUpsertBulk) DoNothing() *AgentDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentDefinitionCreateBulk.OnConflict
// documentation for more info.
func (u *AgentDefinitionUpsertBulk) Update(set func(*AgentDefinitionUpsert)) *AgentDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentDefinitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentDefinitionUpsertBulk) SetUpdatedAt(v time.Time) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateUpdatedAt() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *AgentDefinitionUpsertBulk) SetSlug(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateSlug() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *AgentDefinitionUpsertBulk) SetName(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateName() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateName()
	})
}

// SetInstructions sets the "instructions" field.
func (u *AgentDefinitionUpsertBulk) SetInstructions(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetInstructions(v)
	})
}

// UpdateInstructions sets the "instructions" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateInstructions() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateInstructions()
	})
}

// ClearInstructions clears the value of the "instructions" field.
func (u *AgentDefinitionUpsertBulk) ClearInstructions() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearInstructions()
	})
}

// SetModel sets the "model" field.
func (u *AgentDefinitionUpsertBulk) SetModel(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateModel() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AgentDefinitionUpsertBulk) ClearModel() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearModel()
	})
}

// SetProvider sets the "provider" field.
func (u *AgentDefinitionUpsertBulk) SetProvider(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateProvider() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *AgentDefinitionUpsertBulk) ClearProvider() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearProvider()
	})
}

// SetLimitsJSON sets the "limits_json" field.
func (u *AgentDefinitionUpsertBulk) SetLimitsJSON(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetLimitsJSON(v)
	})
}

// UpdateLimitsJSON sets the "limits_json" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateLimitsJSON() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateLimitsJSON()
	})
}

// ClearLimitsJSON clears the value of the "limits_json" field.
func (u *AgentDefinitionUpsertBulk) ClearLimitsJSON() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearLimitsJSON()
	})
}

// SetEnabledTools sets the "enabled_tools" field.
func (u *AgentDefinitionUpsertBulk) SetEnabledTools(v []string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetEnabledTools(v)
	})
}

// UpdateEnabledTools sets the "enabled_tools" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateEnabledTools() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateEnabledTools()
	})
}

// ClearEnabledTools clears the value of the "enabled_tools" field.
func (u *AgentDefinitionUpsertBulk) ClearEnabledTools() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearEnabledTools()
	})
}

// SetToolsJSON sets the "tools_json" field.
func (u *AgentDefinitionUpsertBulk) SetToolsJSON(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetToolsJSON(v)
	})
}

// UpdateToolsJSON sets the "tools_json" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateToolsJSON() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateToolsJSON()
	})
}

// ClearToolsJSON clears the value of the "tools_json" field.
func (u *AgentDefinitionUpsertBulk) ClearToolsJSON() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearToolsJSON()
	})
}

// SetSubagentRefs sets the "subagent_refs" field.
func (u *AgentDefinitionUpsertBulk) SetSubagentRefs(v []string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetSubagentRefs(v)
	})
}

// UpdateSubagentRefs sets the "subagent_refs" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateSubagentRefs() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateSubagentRefs()
	})
}

// ClearSubagentRefs clears the value of the "subagent_refs" field.
func (u *AgentDefinitionUpsertBulk) ClearSubagentRefs() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearSubagentRefs()
	})
}

// SetChannelBindings sets the "channel_bindings" field.
func (u *AgentDefinitionUpsertBulk) SetChannelBindings(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetChannelBindings(v)
	})
}

// UpdateChannelBindings sets the "channel_bindings" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateChannelBindings() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateChannelBindings()
	})
}

// ClearChannelBindings clears the value of the "channel_bindings" field.
func (u *AgentDefinitionUpsertBulk) ClearChannelBindings() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearChannelBindings()
	})
}

// SetConnectorReqs sets the "connector_reqs" field.
func (u *AgentDefinitionUpsertBulk) SetConnectorReqs(v []string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetConnectorReqs(v)
	})
}

// UpdateConnectorReqs sets the "connector_reqs" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateConnectorReqs() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateConnectorReqs()
	})
}

// ClearConnectorReqs clears the value of the "connector_reqs" field.
func (u *AgentDefinitionUpsertBulk) ClearConnectorReqs() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearConnectorReqs()
	})
}

// SetSource sets the "source" field.
func (u *AgentDefinitionUpsertBulk) SetSource(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateSource() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateSource()
	})
}

// SetForkedFrom sets the "forked_from" field.
func (u *AgentDefinitionUpsertBulk) SetForkedFrom(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetForkedFrom(v)
	})
}

// UpdateForkedFrom sets the "forked_from" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateForkedFrom() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateForkedFrom()
	})
}

// ClearForkedFrom clears the value of the "forked_from" field.
func (u *AgentDefinitionUpsertBulk) ClearForkedFrom() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearForkedFrom()
	})
}

// SetRevision sets the "revision" field.
func (u *AgentDefinitionUpsertBulk) SetRevision(v int) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *AgentDefinitionUpsertBulk) AddRevision(v int) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateRevision() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateRevision()
	})
}

// SetSourceFormat sets the "source_format" field.
func (u *AgentDefinitionUpsertBulk) SetSourceFormat(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetSourceFormat(v)
	})
}

// UpdateSourceFormat sets the "source_format" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateSourceFormat() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateSourceFormat()
	})
}

// SetRawSource sets the "raw_source" field.
func (u *AgentDefinitionUpsertBulk) SetRawSource(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetRawSource(v)
	})
}

// UpdateRawSource sets the "raw_source" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateRawSource() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateRawSource()
	})
}

// ClearRawSource clears the value of the "raw_source" field.
func (u *AgentDefinitionUpsertBulk) ClearRawSource() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearRawSource()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *AgentDefinitionUpsertBulk) SetContentHash(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateContentHash() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *AgentDefinitionUpsertBulk) ClearContentHash() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearContentHash()
	})
}

// SetManagedBy sets the "managed_by" field.
func (u *AgentDefinitionUpsertBulk) SetManagedBy(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetManagedBy(v)
	})
}

// UpdateManagedBy sets the "managed_by" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateManagedBy() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateManagedBy()
	})
}

// SetAgentSyncState sets the "agent_sync_state" field.
func (u *AgentDefinitionUpsertBulk) SetAgentSyncState(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetAgentSyncState(v)
	})
}

// UpdateAgentSyncState sets the "agent_sync_state" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateAgentSyncState() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateAgentSyncState()
	})
}

// SetAgentSyncError sets the "agent_sync_error" field.
func (u *AgentDefinitionUpsertBulk) SetAgentSyncError(v string) *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.SetAgentSyncError(v)
	})
}

// UpdateAgentSyncError sets the "agent_sync_error" field to the value that was provided on create.
func (u *AgentDefinitionUpsertBulk) UpdateAgentSyncError() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.UpdateAgentSyncError()
	})
}

// ClearAgentSyncError clears the value of the "agent_sync_error" field.
func (u *AgentDefinitionUpsertBulk) ClearAgentSyncError() *AgentDefinitionUpsertBulk {
	return u.Update(func(s *AgentDefinitionUpsert) {
		s.ClearAgentSyncError()
	})
}

// Exec executes the query.
func (u *AgentDefinitionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AgentDefinitionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentDefinitionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentDefinitionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
