// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtask"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskartifact"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskrun"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskrunevent"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskschedulestate"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/user"
	"github.com/google/uuid"
)

// BackgroundTaskUpdate is the builder for updating BackgroundTask entities.
type BackgroundTaskUpdate struct {
	config
	hooks    []Hook
	mutation *BackgroundTaskMutation
}

// Where appends a list predicates to the BackgroundTaskUpdate builder.
func (_u *BackgroundTaskUpdate) Where(ps ...predicate.BackgroundTask) *BackgroundTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackgroundTaskUpdate) SetUpdatedAt(v time.Time) *BackgroundTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *BackgroundTaskUpdate) SetSlug(v string) *BackgroundTaskUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableSlug(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *BackgroundTaskUpdate) SetName(v string) *BackgroundTaskUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableName(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetInstructions sets the "instructions" field.
func (_u *BackgroundTaskUpdate) SetInstructions(v string) *BackgroundTaskUpdate {
	_u.mutation.SetInstructions(v)
	return _u
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableInstructions(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetInstructions(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *BackgroundTaskUpdate) SetActive(v bool) *BackgroundTaskUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableActive(v *bool) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetTriggersJSON sets the "triggers_json" field.
func (_u *BackgroundTaskUpdate) SetTriggersJSON(v string) *BackgroundTaskUpdate {
	_u.mutation.SetTriggersJSON(v)
	return _u
}

// SetNillableTriggersJSON sets the "triggers_json" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableTriggersJSON(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetTriggersJSON(*v)
	}
	return _u
}

// ClearTriggersJSON clears the value of the "triggers_json" field.
func (_u *BackgroundTaskUpdate) ClearTriggersJSON() *BackgroundTaskUpdate {
	_u.mutation.ClearTriggersJSON()
	return _u
}

// SetModel sets the "model" field.
func (_u *BackgroundTaskUpdate) SetModel(v string) *BackgroundTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableModel(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *BackgroundTaskUpdate) ClearModel() *BackgroundTaskUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *BackgroundTaskUpdate) SetProvider(v string) *BackgroundTaskUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableProvider(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *BackgroundTaskUpdate) ClearProvider() *BackgroundTaskUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// SetExecutionTarget sets the "execution_target" field.
func (_u *BackgroundTaskUpdate) SetExecutionTarget(v string) *BackgroundTaskUpdate {
	_u.mutation.SetExecutionTarget(v)
	return _u
}

// SetNillableExecutionTarget sets the "execution_target" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableExecutionTarget(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetExecutionTarget(*v)
	}
	return _u
}

// SetTaskCreatedAt sets the "task_created_at" field.
func (_u *BackgroundTaskUpdate) SetTaskCreatedAt(v time.Time) *BackgroundTaskUpdate {
	_u.mutation.SetTaskCreatedAt(v)
	return _u
}

// SetNillableTaskCreatedAt sets the "task_created_at" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableTaskCreatedAt(v *time.Time) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetTaskCreatedAt(*v)
	}
	return _u
}

// ClearTaskCreatedAt clears the value of the "task_created_at" field.
func (_u *BackgroundTaskUpdate) ClearTaskCreatedAt() *BackgroundTaskUpdate {
	_u.mutation.ClearTaskCreatedAt()
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *BackgroundTaskUpdate) SetLastAttemptAt(v time.Time) *BackgroundTaskUpdate {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableLastAttemptAt(v *time.Time) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// ClearLastAttemptAt clears the value of the "last_attempt_at" field.
func (_u *BackgroundTaskUpdate) ClearLastAttemptAt() *BackgroundTaskUpdate {
	_u.mutation.ClearLastAttemptAt()
	return _u
}

// SetLastRunID sets the "last_run_id" field.
func (_u *BackgroundTaskUpdate) SetLastRunID(v string) *BackgroundTaskUpdate {
	_u.mutation.SetLastRunID(v)
	return _u
}

// SetNillableLastRunID sets the "last_run_id" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableLastRunID(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetLastRunID(*v)
	}
	return _u
}

// ClearLastRunID clears the value of the "last_run_id" field.
func (_u *BackgroundTaskUpdate) ClearLastRunID() *BackgroundTaskUpdate {
	_u.mutation.ClearLastRunID()
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *BackgroundTaskUpdate) SetLastRunAt(v time.Time) *BackgroundTaskUpdate {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableLastRunAt(v *time.Time) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *BackgroundTaskUpdate) ClearLastRunAt() *BackgroundTaskUpdate {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetLastRunSummary sets the "last_run_summary" field.
func (_u *BackgroundTaskUpdate) SetLastRunSummary(v string) *BackgroundTaskUpdate {
	_u.mutation.SetLastRunSummary(v)
	return _u
}

// SetNillableLastRunSummary sets the "last_run_summary" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableLastRunSummary(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetLastRunSummary(*v)
	}
	return _u
}

// ClearLastRunSummary clears the value of the "last_run_summary" field.
func (_u *BackgroundTaskUpdate) ClearLastRunSummary() *BackgroundTaskUpdate {
	_u.mutation.ClearLastRunSummary()
	return _u
}

// SetLastRunError sets the "last_run_error" field.
func (_u *BackgroundTaskUpdate) SetLastRunError(v string) *BackgroundTaskUpdate {
	_u.mutation.SetLastRunError(v)
	return _u
}

// SetNillableLastRunError sets the "last_run_error" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableLastRunError(v *string) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetLastRunError(*v)
	}
	return _u
}

// ClearLastRunError clears the value of the "last_run_error" field.
func (_u *BackgroundTaskUpdate) ClearLastRunError() *BackgroundTaskUpdate {
	_u.mutation.ClearLastRunError()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *BackgroundTaskUpdate) SetRevision(v int) *BackgroundTaskUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableRevision(v *int) *BackgroundTaskUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *BackgroundTaskUpdate) AddRevision(v int) *BackgroundTaskUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *BackgroundTaskUpdate) SetUserID(id uuid.UUID) *BackgroundTaskUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BackgroundTaskUpdate) SetUser(v *User) *BackgroundTaskUpdate {
	return _u.SetUserID(v.ID)
}

// SetArtifactID sets the "artifact" edge to the BackgroundTaskArtifact entity by ID.
func (_u *BackgroundTaskUpdate) SetArtifactID(id uuid.UUID) *BackgroundTaskUpdate {
	_u.mutation.SetArtifactID(id)
	return _u
}

// SetNillableArtifactID sets the "artifact" edge to the BackgroundTaskArtifact entity by ID if the given value is not nil.
func (_u *BackgroundTaskUpdate) SetNillableArtifactID(id *uuid.UUID) *BackgroundTaskUpdate {
	if id != nil {
		_u = _u.SetArtifactID(*id)
	}
	return _u
}

// SetArtifact sets the "artifact" edge to the BackgroundTaskArtifact entity.
func (_u *BackgroundTaskUpdate) SetArtifact(v *BackgroundTaskArtifact) *BackgroundTaskUpdate {
	return _u.SetArtifactID(v.ID)
}

// AddRunIDs adds the "runs" edge to the BackgroundTaskRun entity by IDs.
func (_u *BackgroundTaskUpdate) AddRunIDs(ids ...uuid.UUID) *BackgroundTaskUpdate {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the BackgroundTaskRun entity.
func (_u *BackgroundTaskUpdate) AddRuns(v ...*BackgroundTaskRun) *BackgroundTaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// AddRunEventIDs adds the "run_events" edge to the BackgroundTaskRunEvent entity by IDs.
func (_u *BackgroundTaskUpdate) AddRunEventIDs(ids ...uuid.UUID) *BackgroundTaskUpdate {
	_u.mutation.AddRunEventIDs(ids...)
	return _u
}

// AddRunEvents adds the "run_events" edges to the BackgroundTaskRunEvent entity.
func (_u *BackgroundTaskUpdate) AddRunEvents(v ...*BackgroundTaskRunEvent) *BackgroundTaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunEventIDs(ids...)
}

// AddScheduleStateIDs adds the "schedule_states" edge to the BackgroundTaskScheduleState entity by IDs.
func (_u *BackgroundTaskUpdate) AddScheduleStateIDs(ids ...uuid.UUID) *BackgroundTaskUpdate {
	_u.mutation.AddScheduleStateIDs(ids...)
	return _u
}

// AddScheduleStates adds the "schedule_states" edges to the BackgroundTaskScheduleState entity.
func (_u *BackgroundTaskUpdate) AddScheduleStates(v ...*BackgroundTaskScheduleState) *BackgroundTaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScheduleStateIDs(ids...)
}

// Mutation returns the BackgroundTaskMutation object of the builder.
func (_u *BackgroundTaskUpdate) Mutation() *BackgroundTaskMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BackgroundTaskUpdate) ClearUser() *BackgroundTaskUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearArtifact clears the "artifact" edge to the BackgroundTaskArtifact entity.
func (_u *BackgroundTaskUpdate) ClearArtifact() *BackgroundTaskUpdate {
	_u.mutation.ClearArtifact()
	return _u
}

// ClearRuns clears all "runs" edges to the BackgroundTaskRun entity.
func (_u *BackgroundTaskUpdate) ClearRuns() *BackgroundTaskUpdate {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to BackgroundTaskRun entities by IDs.
func (_u *BackgroundTaskUpdate) RemoveRunIDs(ids ...uuid.UUID) *BackgroundTaskUpdate {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to BackgroundTaskRun entities.
func (_u *BackgroundTaskUpdate) RemoveRuns(v ...*BackgroundTaskRun) *BackgroundTaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// ClearRunEvents clears all "run_events" edges to the BackgroundTaskRunEvent entity.
func (_u *BackgroundTaskUpdate) ClearRunEvents() *BackgroundTaskUpdate {
	_u.mutation.ClearRunEvents()
	return _u
}

// RemoveRunEventIDs removes the "run_events" edge to BackgroundTaskRunEvent entities by IDs.
func (_u *BackgroundTaskUpdate) RemoveRunEventIDs(ids ...uuid.UUID) *BackgroundTaskUpdate {
	_u.mutation.RemoveRunEventIDs(ids...)
	return _u
}

// RemoveRunEvents removes "run_events" edges to BackgroundTaskRunEvent entities.
func (_u *BackgroundTaskUpdate) RemoveRunEvents(v ...*BackgroundTaskRunEvent) *BackgroundTaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunEventIDs(ids...)
}

// ClearScheduleStates clears all "schedule_states" edges to the BackgroundTaskScheduleState entity.
func (_u *BackgroundTaskUpdate) ClearScheduleStates() *BackgroundTaskUpdate {
	_u.mutation.ClearScheduleStates()
	return _u
}

// RemoveScheduleStateIDs removes the "schedule_states" edge to BackgroundTaskScheduleState entities by IDs.
func (_u *BackgroundTaskUpdate) RemoveScheduleStateIDs(ids ...uuid.UUID) *BackgroundTaskUpdate {
	_u.mutation.RemoveScheduleStateIDs(ids...)
	return _u
}

// RemoveScheduleStates removes "schedule_states" edges to BackgroundTaskScheduleState entities.
func (_u *BackgroundTaskUpdate) RemoveScheduleStates(v ...*BackgroundTaskScheduleState) *BackgroundTaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScheduleStateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackgroundTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackgroundTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackgroundTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackgroundTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackgroundTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backgroundtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackgroundTaskUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := backgroundtask.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := backgroundtask.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Instructions(); ok {
		if err := backgroundtask.InstructionsValidator(v); err != nil {
			return &ValidationError{Name: "instructions", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.instructions": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggersJSON(); ok {
		if err := backgroundtask.TriggersJSONValidator(v); err != nil {
			return &ValidationError{Name: "triggers_json", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.triggers_json": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecutionTarget(); ok {
		if err := backgroundtask.ExecutionTargetValidator(v); err != nil {
			return &ValidationError{Name: "execution_target", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.execution_target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := backgroundtask.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.revision": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackgroundTask.user"`)
	}
	return nil
}

func (_u *BackgroundTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backgroundtask.Table, backgroundtask.Columns, sqlgraph.NewFieldSpec(backgroundtask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backgroundtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(backgroundtask.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(backgroundtask.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Instructions(); ok {
		_spec.SetField(backgroundtask.FieldInstructions, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(backgroundtask.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TriggersJSON(); ok {
		_spec.SetField(backgroundtask.FieldTriggersJSON, field.TypeString, value)
	}
	if _u.mutation.TriggersJSONCleared() {
		_spec.ClearField(backgroundtask.FieldTriggersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(backgroundtask.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(backgroundtask.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(backgroundtask.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(backgroundtask.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutionTarget(); ok {
		_spec.SetField(backgroundtask.FieldExecutionTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskCreatedAt(); ok {
		_spec.SetField(backgroundtask.FieldTaskCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TaskCreatedAtCleared() {
		_spec.ClearField(backgroundtask.FieldTaskCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(backgroundtask.FieldLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptAtCleared() {
		_spec.ClearField(backgroundtask.FieldLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRunID(); ok {
		_spec.SetField(backgroundtask.FieldLastRunID, field.TypeString, value)
	}
	if _u.mutation.LastRunIDCleared() {
		_spec.ClearField(backgroundtask.FieldLastRunID, field.TypeString)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(backgroundtask.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(backgroundtask.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRunSummary(); ok {
		_spec.SetField(backgroundtask.FieldLastRunSummary, field.TypeString, value)
	}
	if _u.mutation.LastRunSummaryCleared() {
		_spec.ClearField(backgroundtask.FieldLastRunSummary, field.TypeString)
	}
	if value, ok := _u.mutation.LastRunError(); ok {
		_spec.SetField(backgroundtask.FieldLastRunError, field.TypeString, value)
	}
	if _u.mutation.LastRunErrorCleared() {
		_spec.ClearField(backgroundtask.FieldLastRunError, field.TypeString)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(backgroundtask.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(backgroundtask.FieldRevision, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backgroundtask.UserTable,
			Columns: []string{backgroundtask.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backgroundtask.UserTable,
			Columns: []string{backgroundtask.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtifactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   backgroundtask.ArtifactTable,
			Columns: []string{backgroundtask.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskartifact.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   backgroundtask.ArtifactTable,
			Columns: []string{backgroundtask.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskartifact.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunsTable,
			Columns: []string{backgroundtask.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrun.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunsTable,
			Columns: []string{backgroundtask.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunsTable,
			Columns: []string{backgroundtask.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunEventsTable,
			Columns: []string{backgroundtask.RunEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrunevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunEventsIDs(); len(nodes) > 0 && !_u.mutation.RunEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunEventsTable,
			Columns: []string{backgroundtask.RunEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrunevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunEventsTable,
			Columns: []string{backgroundtask.RunEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrunevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScheduleStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.ScheduleStatesTable,
			Columns: []string{backgroundtask.ScheduleStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskschedulestate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScheduleStatesIDs(); len(nodes) > 0 && !_u.mutation.ScheduleStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.ScheduleStatesTable,
			Columns: []string{backgroundtask.ScheduleStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskschedulestate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScheduleStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.ScheduleStatesTable,
			Columns: []string{backgroundtask.ScheduleStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskschedulestate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backgroundtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackgroundTaskUpdateOne is the builder for updating a single BackgroundTask entity.
type BackgroundTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackgroundTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackgroundTaskUpdateOne) SetUpdatedAt(v time.Time) *BackgroundTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *BackgroundTaskUpdateOne) SetSlug(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableSlug(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *BackgroundTaskUpdateOne) SetName(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableName(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetInstructions sets the "instructions" field.
func (_u *BackgroundTaskUpdateOne) SetInstructions(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetInstructions(v)
	return _u
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableInstructions(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetInstructions(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *BackgroundTaskUpdateOne) SetActive(v bool) *BackgroundTaskUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableActive(v *bool) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetTriggersJSON sets the "triggers_json" field.
func (_u *BackgroundTaskUpdateOne) SetTriggersJSON(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetTriggersJSON(v)
	return _u
}

// SetNillableTriggersJSON sets the "triggers_json" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableTriggersJSON(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetTriggersJSON(*v)
	}
	return _u
}

// ClearTriggersJSON clears the value of the "triggers_json" field.
func (_u *BackgroundTaskUpdateOne) ClearTriggersJSON() *BackgroundTaskUpdateOne {
	_u.mutation.ClearTriggersJSON()
	return _u
}

// SetModel sets the "model" field.
func (_u *BackgroundTaskUpdateOne) SetModel(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableModel(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *BackgroundTaskUpdateOne) ClearModel() *BackgroundTaskUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *BackgroundTaskUpdateOne) SetProvider(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableProvider(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *BackgroundTaskUpdateOne) ClearProvider() *BackgroundTaskUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// SetExecutionTarget sets the "execution_target" field.
func (_u *BackgroundTaskUpdateOne) SetExecutionTarget(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetExecutionTarget(v)
	return _u
}

// SetNillableExecutionTarget sets the "execution_target" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableExecutionTarget(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetExecutionTarget(*v)
	}
	return _u
}

// SetTaskCreatedAt sets the "task_created_at" field.
func (_u *BackgroundTaskUpdateOne) SetTaskCreatedAt(v time.Time) *BackgroundTaskUpdateOne {
	_u.mutation.SetTaskCreatedAt(v)
	return _u
}

// SetNillableTaskCreatedAt sets the "task_created_at" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableTaskCreatedAt(v *time.Time) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetTaskCreatedAt(*v)
	}
	return _u
}

// ClearTaskCreatedAt clears the value of the "task_created_at" field.
func (_u *BackgroundTaskUpdateOne) ClearTaskCreatedAt() *BackgroundTaskUpdateOne {
	_u.mutation.ClearTaskCreatedAt()
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *BackgroundTaskUpdateOne) SetLastAttemptAt(v time.Time) *BackgroundTaskUpdateOne {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableLastAttemptAt(v *time.Time) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// ClearLastAttemptAt clears the value of the "last_attempt_at" field.
func (_u *BackgroundTaskUpdateOne) ClearLastAttemptAt() *BackgroundTaskUpdateOne {
	_u.mutation.ClearLastAttemptAt()
	return _u
}

// SetLastRunID sets the "last_run_id" field.
func (_u *BackgroundTaskUpdateOne) SetLastRunID(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetLastRunID(v)
	return _u
}

// SetNillableLastRunID sets the "last_run_id" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableLastRunID(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetLastRunID(*v)
	}
	return _u
}

// ClearLastRunID clears the value of the "last_run_id" field.
func (_u *BackgroundTaskUpdateOne) ClearLastRunID() *BackgroundTaskUpdateOne {
	_u.mutation.ClearLastRunID()
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *BackgroundTaskUpdateOne) SetLastRunAt(v time.Time) *BackgroundTaskUpdateOne {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableLastRunAt(v *time.Time) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *BackgroundTaskUpdateOne) ClearLastRunAt() *BackgroundTaskUpdateOne {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetLastRunSummary sets the "last_run_summary" field.
func (_u *BackgroundTaskUpdateOne) SetLastRunSummary(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetLastRunSummary(v)
	return _u
}

// SetNillableLastRunSummary sets the "last_run_summary" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableLastRunSummary(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetLastRunSummary(*v)
	}
	return _u
}

// ClearLastRunSummary clears the value of the "last_run_summary" field.
func (_u *BackgroundTaskUpdateOne) ClearLastRunSummary() *BackgroundTaskUpdateOne {
	_u.mutation.ClearLastRunSummary()
	return _u
}

// SetLastRunError sets the "last_run_error" field.
func (_u *BackgroundTaskUpdateOne) SetLastRunError(v string) *BackgroundTaskUpdateOne {
	_u.mutation.SetLastRunError(v)
	return _u
}

// SetNillableLastRunError sets the "last_run_error" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableLastRunError(v *string) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetLastRunError(*v)
	}
	return _u
}

// ClearLastRunError clears the value of the "last_run_error" field.
func (_u *BackgroundTaskUpdateOne) ClearLastRunError() *BackgroundTaskUpdateOne {
	_u.mutation.ClearLastRunError()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *BackgroundTaskUpdateOne) SetRevision(v int) *BackgroundTaskUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableRevision(v *int) *BackgroundTaskUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *BackgroundTaskUpdateOne) AddRevision(v int) *BackgroundTaskUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *BackgroundTaskUpdateOne) SetUserID(id uuid.UUID) *BackgroundTaskUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BackgroundTaskUpdateOne) SetUser(v *User) *BackgroundTaskUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetArtifactID sets the "artifact" edge to the BackgroundTaskArtifact entity by ID.
func (_u *BackgroundTaskUpdateOne) SetArtifactID(id uuid.UUID) *BackgroundTaskUpdateOne {
	_u.mutation.SetArtifactID(id)
	return _u
}

// SetNillableArtifactID sets the "artifact" edge to the BackgroundTaskArtifact entity by ID if the given value is not nil.
func (_u *BackgroundTaskUpdateOne) SetNillableArtifactID(id *uuid.UUID) *BackgroundTaskUpdateOne {
	if id != nil {
		_u = _u.SetArtifactID(*id)
	}
	return _u
}

// SetArtifact sets the "artifact" edge to the BackgroundTaskArtifact entity.
func (_u *BackgroundTaskUpdateOne) SetArtifact(v *BackgroundTaskArtifact) *BackgroundTaskUpdateOne {
	return _u.SetArtifactID(v.ID)
}

// AddRunIDs adds the "runs" edge to the BackgroundTaskRun entity by IDs.
func (_u *BackgroundTaskUpdateOne) AddRunIDs(ids ...uuid.UUID) *BackgroundTaskUpdateOne {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the BackgroundTaskRun entity.
func (_u *BackgroundTaskUpdateOne) AddRuns(v ...*BackgroundTaskRun) *BackgroundTaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// AddRunEventIDs adds the "run_events" edge to the BackgroundTaskRunEvent entity by IDs.
func (_u *BackgroundTaskUpdateOne) AddRunEventIDs(ids ...uuid.UUID) *BackgroundTaskUpdateOne {
	_u.mutation.AddRunEventIDs(ids...)
	return _u
}

// AddRunEvents adds the "run_events" edges to the BackgroundTaskRunEvent entity.
func (_u *BackgroundTaskUpdateOne) AddRunEvents(v ...*BackgroundTaskRunEvent) *BackgroundTaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunEventIDs(ids...)
}

// AddScheduleStateIDs adds the "schedule_states" edge to the BackgroundTaskScheduleState entity by IDs.
func (_u *BackgroundTaskUpdateOne) AddScheduleStateIDs(ids ...uuid.UUID) *BackgroundTaskUpdateOne {
	_u.mutation.AddScheduleStateIDs(ids...)
	return _u
}

// AddScheduleStates adds the "schedule_states" edges to the BackgroundTaskScheduleState entity.
func (_u *BackgroundTaskUpdateOne) AddScheduleStates(v ...*BackgroundTaskScheduleState) *BackgroundTaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScheduleStateIDs(ids...)
}

// Mutation returns the BackgroundTaskMutation object of the builder.
func (_u *BackgroundTaskUpdateOne) Mutation() *BackgroundTaskMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BackgroundTaskUpdateOne) ClearUser() *BackgroundTaskUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearArtifact clears the "artifact" edge to the BackgroundTaskArtifact entity.
func (_u *BackgroundTaskUpdateOne) ClearArtifact() *BackgroundTaskUpdateOne {
	_u.mutation.ClearArtifact()
	return _u
}

// ClearRuns clears all "runs" edges to the BackgroundTaskRun entity.
func (_u *BackgroundTaskUpdateOne) ClearRuns() *BackgroundTaskUpdateOne {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to BackgroundTaskRun entities by IDs.
func (_u *BackgroundTaskUpdateOne) RemoveRunIDs(ids ...uuid.UUID) *BackgroundTaskUpdateOne {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to BackgroundTaskRun entities.
func (_u *BackgroundTaskUpdateOne) RemoveRuns(v ...*BackgroundTaskRun) *BackgroundTaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// ClearRunEvents clears all "run_events" edges to the BackgroundTaskRunEvent entity.
func (_u *BackgroundTaskUpdateOne) ClearRunEvents() *BackgroundTaskUpdateOne {
	_u.mutation.ClearRunEvents()
	return _u
}

// RemoveRunEventIDs removes the "run_events" edge to BackgroundTaskRunEvent entities by IDs.
func (_u *BackgroundTaskUpdateOne) RemoveRunEventIDs(ids ...uuid.UUID) *BackgroundTaskUpdateOne {
	_u.mutation.RemoveRunEventIDs(ids...)
	return _u
}

// RemoveRunEvents removes "run_events" edges to BackgroundTaskRunEvent entities.
func (_u *BackgroundTaskUpdateOne) RemoveRunEvents(v ...*BackgroundTaskRunEvent) *BackgroundTaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunEventIDs(ids...)
}

// ClearScheduleStates clears all "schedule_states" edges to the BackgroundTaskScheduleState entity.
func (_u *BackgroundTaskUpdateOne) ClearScheduleStates() *BackgroundTaskUpdateOne {
	_u.mutation.ClearScheduleStates()
	return _u
}

// RemoveScheduleStateIDs removes the "schedule_states" edge to BackgroundTaskScheduleState entities by IDs.
func (_u *BackgroundTaskUpdateOne) RemoveScheduleStateIDs(ids ...uuid.UUID) *BackgroundTaskUpdateOne {
	_u.mutation.RemoveScheduleStateIDs(ids...)
	return _u
}

// RemoveScheduleStates removes "schedule_states" edges to BackgroundTaskScheduleState entities.
func (_u *BackgroundTaskUpdateOne) RemoveScheduleStates(v ...*BackgroundTaskScheduleState) *BackgroundTaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScheduleStateIDs(ids...)
}

// Where appends a list predicates to the BackgroundTaskUpdate builder.
func (_u *BackgroundTaskUpdateOne) Where(ps ...predicate.BackgroundTask) *BackgroundTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackgroundTaskUpdateOne) Select(field string, fields ...string) *BackgroundTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BackgroundTask entity.
func (_u *BackgroundTaskUpdateOne) Save(ctx context.Context) (*BackgroundTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackgroundTaskUpdateOne) SaveX(ctx context.Context) *BackgroundTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackgroundTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackgroundTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackgroundTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backgroundtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackgroundTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := backgroundtask.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := backgroundtask.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Instructions(); ok {
		if err := backgroundtask.InstructionsValidator(v); err != nil {
			return &ValidationError{Name: "instructions", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.instructions": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggersJSON(); ok {
		if err := backgroundtask.TriggersJSONValidator(v); err != nil {
			return &ValidationError{Name: "triggers_json", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.triggers_json": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecutionTarget(); ok {
		if err := backgroundtask.ExecutionTargetValidator(v); err != nil {
			return &ValidationError{Name: "execution_target", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.execution_target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := backgroundtask.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "BackgroundTask.revision": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackgroundTask.user"`)
	}
	return nil
}

func (_u *BackgroundTaskUpdateOne) sqlSave(ctx context.Context) (_node *BackgroundTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backgroundtask.Table, backgroundtask.Columns, sqlgraph.NewFieldSpec(backgroundtask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackgroundTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backgroundtask.FieldID)
		for _, f := range fields {
			if !backgroundtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backgroundtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backgroundtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(backgroundtask.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(backgroundtask.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Instructions(); ok {
		_spec.SetField(backgroundtask.FieldInstructions, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(backgroundtask.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TriggersJSON(); ok {
		_spec.SetField(backgroundtask.FieldTriggersJSON, field.TypeString, value)
	}
	if _u.mutation.TriggersJSONCleared() {
		_spec.ClearField(backgroundtask.FieldTriggersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(backgroundtask.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(backgroundtask.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(backgroundtask.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(backgroundtask.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutionTarget(); ok {
		_spec.SetField(backgroundtask.FieldExecutionTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskCreatedAt(); ok {
		_spec.SetField(backgroundtask.FieldTaskCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TaskCreatedAtCleared() {
		_spec.ClearField(backgroundtask.FieldTaskCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(backgroundtask.FieldLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptAtCleared() {
		_spec.ClearField(backgroundtask.FieldLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRunID(); ok {
		_spec.SetField(backgroundtask.FieldLastRunID, field.TypeString, value)
	}
	if _u.mutation.LastRunIDCleared() {
		_spec.ClearField(backgroundtask.FieldLastRunID, field.TypeString)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(backgroundtask.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(backgroundtask.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRunSummary(); ok {
		_spec.SetField(backgroundtask.FieldLastRunSummary, field.TypeString, value)
	}
	if _u.mutation.LastRunSummaryCleared() {
		_spec.ClearField(backgroundtask.FieldLastRunSummary, field.TypeString)
	}
	if value, ok := _u.mutation.LastRunError(); ok {
		_spec.SetField(backgroundtask.FieldLastRunError, field.TypeString, value)
	}
	if _u.mutation.LastRunErrorCleared() {
		_spec.ClearField(backgroundtask.FieldLastRunError, field.TypeString)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(backgroundtask.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(backgroundtask.FieldRevision, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backgroundtask.UserTable,
			Columns: []string{backgroundtask.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backgroundtask.UserTable,
			Columns: []string{backgroundtask.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtifactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   backgroundtask.ArtifactTable,
			Columns: []string{backgroundtask.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskartifact.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   backgroundtask.ArtifactTable,
			Columns: []string{backgroundtask.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskartifact.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunsTable,
			Columns: []string{backgroundtask.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrun.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunsTable,
			Columns: []string{backgroundtask.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunsTable,
			Columns: []string{backgroundtask.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunEventsTable,
			Columns: []string{backgroundtask.RunEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrunevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunEventsIDs(); len(nodes) > 0 && !_u.mutation.RunEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunEventsTable,
			Columns: []string{backgroundtask.RunEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrunevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.RunEventsTable,
			Columns: []string{backgroundtask.RunEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskrunevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScheduleStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.ScheduleStatesTable,
			Columns: []string{backgroundtask.ScheduleStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskschedulestate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScheduleStatesIDs(); len(nodes) > 0 && !_u.mutation.ScheduleStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.ScheduleStatesTable,
			Columns: []string{backgroundtask.ScheduleStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskschedulestate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScheduleStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backgroundtask.ScheduleStatesTable,
			Columns: []string{backgroundtask.ScheduleStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backgroundtaskschedulestate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BackgroundTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backgroundtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
