// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/communicationprivacypolicy"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
)

// CommunicationPrivacyPolicyUpdate is the builder for updating CommunicationPrivacyPolicy entities.
type CommunicationPrivacyPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *CommunicationPrivacyPolicyMutation
}

// Where appends a list predicates to the CommunicationPrivacyPolicyUpdate builder.
func (_u *CommunicationPrivacyPolicyUpdate) Where(ps ...predicate.CommunicationPrivacyPolicy) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetUpdatedAt(v time.Time) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSourceAccountID sets the "source_account_id" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetSourceAccountID(v string) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.SetSourceAccountID(v)
	return _u
}

// SetNillableSourceAccountID sets the "source_account_id" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdate) SetNillableSourceAccountID(v *string) *CommunicationPrivacyPolicyUpdate {
	if v != nil {
		_u.SetSourceAccountID(*v)
	}
	return _u
}

// SetMetadataVisibility sets the "metadata_visibility" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetMetadataVisibility(v string) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.SetMetadataVisibility(v)
	return _u
}

// SetNillableMetadataVisibility sets the "metadata_visibility" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdate) SetNillableMetadataVisibility(v *string) *CommunicationPrivacyPolicyUpdate {
	if v != nil {
		_u.SetMetadataVisibility(*v)
	}
	return _u
}

// SetShareSubject sets the "share_subject" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetShareSubject(v bool) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.SetShareSubject(v)
	return _u
}

// SetNillableShareSubject sets the "share_subject" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdate) SetNillableShareSubject(v *bool) *CommunicationPrivacyPolicyUpdate {
	if v != nil {
		_u.SetShareSubject(*v)
	}
	return _u
}

// SetShareBody sets the "share_body" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetShareBody(v bool) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.SetShareBody(v)
	return _u
}

// SetNillableShareBody sets the "share_body" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdate) SetNillableShareBody(v *bool) *CommunicationPrivacyPolicyUpdate {
	if v != nil {
		_u.SetShareBody(*v)
	}
	return _u
}

// SetShareAttachments sets the "share_attachments" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetShareAttachments(v bool) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.SetShareAttachments(v)
	return _u
}

// SetNillableShareAttachments sets the "share_attachments" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdate) SetNillableShareAttachments(v *bool) *CommunicationPrivacyPolicyUpdate {
	if v != nil {
		_u.SetShareAttachments(*v)
	}
	return _u
}

// SetSignatureEnrichment sets the "signature_enrichment" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetSignatureEnrichment(v bool) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.SetSignatureEnrichment(v)
	return _u
}

// SetNillableSignatureEnrichment sets the "signature_enrichment" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdate) SetNillableSignatureEnrichment(v *bool) *CommunicationPrivacyPolicyUpdate {
	if v != nil {
		_u.SetSignatureEnrichment(*v)
	}
	return _u
}

// SetModelContactExtraction sets the "model_contact_extraction" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetModelContactExtraction(v bool) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.SetModelContactExtraction(v)
	return _u
}

// SetNillableModelContactExtraction sets the "model_contact_extraction" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdate) SetNillableModelContactExtraction(v *bool) *CommunicationPrivacyPolicyUpdate {
	if v != nil {
		_u.SetModelContactExtraction(*v)
	}
	return _u
}

// SetRetentionDays sets the "retention_days" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetRetentionDays(v int) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.ResetRetentionDays()
	_u.mutation.SetRetentionDays(v)
	return _u
}

// SetNillableRetentionDays sets the "retention_days" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdate) SetNillableRetentionDays(v *int) *CommunicationPrivacyPolicyUpdate {
	if v != nil {
		_u.SetRetentionDays(*v)
	}
	return _u
}

// AddRetentionDays adds value to the "retention_days" field.
func (_u *CommunicationPrivacyPolicyUpdate) AddRetentionDays(v int) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.AddRetentionDays(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *CommunicationPrivacyPolicyUpdate) SetVersion(v int) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdate) SetNillableVersion(v *int) *CommunicationPrivacyPolicyUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CommunicationPrivacyPolicyUpdate) AddVersion(v int) *CommunicationPrivacyPolicyUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the CommunicationPrivacyPolicyMutation object of the builder.
func (_u *CommunicationPrivacyPolicyUpdate) Mutation() *CommunicationPrivacyPolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommunicationPrivacyPolicyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommunicationPrivacyPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommunicationPrivacyPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommunicationPrivacyPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommunicationPrivacyPolicyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if communicationprivacypolicy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized communicationprivacypolicy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := communicationprivacypolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommunicationPrivacyPolicyUpdate) check() error {
	if v, ok := _u.mutation.SourceAccountID(); ok {
		if err := communicationprivacypolicy.SourceAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "source_account_id", err: fmt.Errorf(`ent: validator failed for field "CommunicationPrivacyPolicy.source_account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetadataVisibility(); ok {
		if err := communicationprivacypolicy.MetadataVisibilityValidator(v); err != nil {
			return &ValidationError{Name: "metadata_visibility", err: fmt.Errorf(`ent: validator failed for field "CommunicationPrivacyPolicy.metadata_visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetentionDays(); ok {
		if err := communicationprivacypolicy.RetentionDaysValidator(v); err != nil {
			return &ValidationError{Name: "retention_days", err: fmt.Errorf(`ent: validator failed for field "CommunicationPrivacyPolicy.retention_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := communicationprivacypolicy.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "CommunicationPrivacyPolicy.version": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommunicationPrivacyPolicy.workspace"`)
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommunicationPrivacyPolicy.owner"`)
	}
	return nil
}

func (_u *CommunicationPrivacyPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(communicationprivacypolicy.Table, communicationprivacypolicy.Columns, sqlgraph.NewFieldSpec(communicationprivacypolicy.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(communicationprivacypolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceAccountID(); ok {
		_spec.SetField(communicationprivacypolicy.FieldSourceAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataVisibility(); ok {
		_spec.SetField(communicationprivacypolicy.FieldMetadataVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShareSubject(); ok {
		_spec.SetField(communicationprivacypolicy.FieldShareSubject, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShareBody(); ok {
		_spec.SetField(communicationprivacypolicy.FieldShareBody, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShareAttachments(); ok {
		_spec.SetField(communicationprivacypolicy.FieldShareAttachments, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SignatureEnrichment(); ok {
		_spec.SetField(communicationprivacypolicy.FieldSignatureEnrichment, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ModelContactExtraction(); ok {
		_spec.SetField(communicationprivacypolicy.FieldModelContactExtraction, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RetentionDays(); ok {
		_spec.SetField(communicationprivacypolicy.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetentionDays(); ok {
		_spec.AddField(communicationprivacypolicy.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(communicationprivacypolicy.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(communicationprivacypolicy.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{communicationprivacypolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommunicationPrivacyPolicyUpdateOne is the builder for updating a single CommunicationPrivacyPolicy entity.
type CommunicationPrivacyPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommunicationPrivacyPolicyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetUpdatedAt(v time.Time) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSourceAccountID sets the "source_account_id" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetSourceAccountID(v string) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.SetSourceAccountID(v)
	return _u
}

// SetNillableSourceAccountID sets the "source_account_id" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetNillableSourceAccountID(v *string) *CommunicationPrivacyPolicyUpdateOne {
	if v != nil {
		_u.SetSourceAccountID(*v)
	}
	return _u
}

// SetMetadataVisibility sets the "metadata_visibility" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetMetadataVisibility(v string) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.SetMetadataVisibility(v)
	return _u
}

// SetNillableMetadataVisibility sets the "metadata_visibility" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetNillableMetadataVisibility(v *string) *CommunicationPrivacyPolicyUpdateOne {
	if v != nil {
		_u.SetMetadataVisibility(*v)
	}
	return _u
}

// SetShareSubject sets the "share_subject" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetShareSubject(v bool) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.SetShareSubject(v)
	return _u
}

// SetNillableShareSubject sets the "share_subject" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetNillableShareSubject(v *bool) *CommunicationPrivacyPolicyUpdateOne {
	if v != nil {
		_u.SetShareSubject(*v)
	}
	return _u
}

// SetShareBody sets the "share_body" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetShareBody(v bool) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.SetShareBody(v)
	return _u
}

// SetNillableShareBody sets the "share_body" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetNillableShareBody(v *bool) *CommunicationPrivacyPolicyUpdateOne {
	if v != nil {
		_u.SetShareBody(*v)
	}
	return _u
}

// SetShareAttachments sets the "share_attachments" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetShareAttachments(v bool) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.SetShareAttachments(v)
	return _u
}

// SetNillableShareAttachments sets the "share_attachments" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetNillableShareAttachments(v *bool) *CommunicationPrivacyPolicyUpdateOne {
	if v != nil {
		_u.SetShareAttachments(*v)
	}
	return _u
}

// SetSignatureEnrichment sets the "signature_enrichment" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetSignatureEnrichment(v bool) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.SetSignatureEnrichment(v)
	return _u
}

// SetNillableSignatureEnrichment sets the "signature_enrichment" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetNillableSignatureEnrichment(v *bool) *CommunicationPrivacyPolicyUpdateOne {
	if v != nil {
		_u.SetSignatureEnrichment(*v)
	}
	return _u
}

// SetModelContactExtraction sets the "model_contact_extraction" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetModelContactExtraction(v bool) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.SetModelContactExtraction(v)
	return _u
}

// SetNillableModelContactExtraction sets the "model_contact_extraction" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetNillableModelContactExtraction(v *bool) *CommunicationPrivacyPolicyUpdateOne {
	if v != nil {
		_u.SetModelContactExtraction(*v)
	}
	return _u
}

// SetRetentionDays sets the "retention_days" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetRetentionDays(v int) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.ResetRetentionDays()
	_u.mutation.SetRetentionDays(v)
	return _u
}

// SetNillableRetentionDays sets the "retention_days" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetNillableRetentionDays(v *int) *CommunicationPrivacyPolicyUpdateOne {
	if v != nil {
		_u.SetRetentionDays(*v)
	}
	return _u
}

// AddRetentionDays adds value to the "retention_days" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) AddRetentionDays(v int) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.AddRetentionDays(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetVersion(v int) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CommunicationPrivacyPolicyUpdateOne) SetNillableVersion(v *int) *CommunicationPrivacyPolicyUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CommunicationPrivacyPolicyUpdateOne) AddVersion(v int) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the CommunicationPrivacyPolicyMutation object of the builder.
func (_u *CommunicationPrivacyPolicyUpdateOne) Mutation() *CommunicationPrivacyPolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommunicationPrivacyPolicyUpdate builder.
func (_u *CommunicationPrivacyPolicyUpdateOne) Where(ps ...predicate.CommunicationPrivacyPolicy) *CommunicationPrivacyPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommunicationPrivacyPolicyUpdateOne) Select(field string, fields ...string) *CommunicationPrivacyPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CommunicationPrivacyPolicy entity.
func (_u *CommunicationPrivacyPolicyUpdateOne) Save(ctx context.Context) (*CommunicationPrivacyPolicy, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommunicationPrivacyPolicyUpdateOne) SaveX(ctx context.Context) *CommunicationPrivacyPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommunicationPrivacyPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommunicationPrivacyPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommunicationPrivacyPolicyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if communicationprivacypolicy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized communicationprivacypolicy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := communicationprivacypolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommunicationPrivacyPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.SourceAccountID(); ok {
		if err := communicationprivacypolicy.SourceAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "source_account_id", err: fmt.Errorf(`ent: validator failed for field "CommunicationPrivacyPolicy.source_account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetadataVisibility(); ok {
		if err := communicationprivacypolicy.MetadataVisibilityValidator(v); err != nil {
			return &ValidationError{Name: "metadata_visibility", err: fmt.Errorf(`ent: validator failed for field "CommunicationPrivacyPolicy.metadata_visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetentionDays(); ok {
		if err := communicationprivacypolicy.RetentionDaysValidator(v); err != nil {
			return &ValidationError{Name: "retention_days", err: fmt.Errorf(`ent: validator failed for field "CommunicationPrivacyPolicy.retention_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := communicationprivacypolicy.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "CommunicationPrivacyPolicy.version": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommunicationPrivacyPolicy.workspace"`)
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommunicationPrivacyPolicy.owner"`)
	}
	return nil
}

func (_u *CommunicationPrivacyPolicyUpdateOne) sqlSave(ctx context.Context) (_node *CommunicationPrivacyPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(communicationprivacypolicy.Table, communicationprivacypolicy.Columns, sqlgraph.NewFieldSpec(communicationprivacypolicy.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CommunicationPrivacyPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, communicationprivacypolicy.FieldID)
		for _, f := range fields {
			if !communicationprivacypolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != communicationprivacypolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(communicationprivacypolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceAccountID(); ok {
		_spec.SetField(communicationprivacypolicy.FieldSourceAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataVisibility(); ok {
		_spec.SetField(communicationprivacypolicy.FieldMetadataVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShareSubject(); ok {
		_spec.SetField(communicationprivacypolicy.FieldShareSubject, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShareBody(); ok {
		_spec.SetField(communicationprivacypolicy.FieldShareBody, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShareAttachments(); ok {
		_spec.SetField(communicationprivacypolicy.FieldShareAttachments, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SignatureEnrichment(); ok {
		_spec.SetField(communicationprivacypolicy.FieldSignatureEnrichment, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ModelContactExtraction(); ok {
		_spec.SetField(communicationprivacypolicy.FieldModelContactExtraction, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RetentionDays(); ok {
		_spec.SetField(communicationprivacypolicy.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetentionDays(); ok {
		_spec.AddField(communicationprivacypolicy.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(communicationprivacypolicy.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(communicationprivacypolicy.FieldVersion, field.TypeInt, value)
	}
	_node = &CommunicationPrivacyPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{communicationprivacypolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
