// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtask"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskartifact"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskrun"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskrunevent"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskschedulestate"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/cloudevent"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/creditledger"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/googlewatch"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/llmusage"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/mcpconnection"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/meetingminuteusage"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/oauthconnection"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/oauthpending"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/subscription"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/user"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *BackgroundTaskQuery) CollectFields(ctx context.Context, satisfies ...string) (*BackgroundTaskQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *BackgroundTaskQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(backgroundtask.Columns))
		selectedFields = []string{backgroundtask.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query

		case "artifact":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskArtifactClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskartifactImplementors)...); err != nil {
				return err
			}
			_q.withArtifact = query

		case "runs":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskRunClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskrunImplementors)...); err != nil {
				return err
			}
			_q.WithNamedRuns(alias, func(wq *BackgroundTaskRunQuery) {
				*wq = *query
			})

		case "runEvents":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskRunEventClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskruneventImplementors)...); err != nil {
				return err
			}
			_q.WithNamedRunEvents(alias, func(wq *BackgroundTaskRunEventQuery) {
				*wq = *query
			})

		case "scheduleStates":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskScheduleStateClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskschedulestateImplementors)...); err != nil {
				return err
			}
			_q.WithNamedScheduleStates(alias, func(wq *BackgroundTaskScheduleStateQuery) {
				*wq = *query
			})
		case "createdAt":
			if _, ok := fieldSeen[backgroundtask.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldCreatedAt)
				fieldSeen[backgroundtask.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[backgroundtask.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldUpdatedAt)
				fieldSeen[backgroundtask.FieldUpdatedAt] = struct{}{}
			}
		case "slug":
			if _, ok := fieldSeen[backgroundtask.FieldSlug]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldSlug)
				fieldSeen[backgroundtask.FieldSlug] = struct{}{}
			}
		case "name":
			if _, ok := fieldSeen[backgroundtask.FieldName]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldName)
				fieldSeen[backgroundtask.FieldName] = struct{}{}
			}
		case "instructions":
			if _, ok := fieldSeen[backgroundtask.FieldInstructions]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldInstructions)
				fieldSeen[backgroundtask.FieldInstructions] = struct{}{}
			}
		case "active":
			if _, ok := fieldSeen[backgroundtask.FieldActive]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldActive)
				fieldSeen[backgroundtask.FieldActive] = struct{}{}
			}
		case "triggersJSON":
			if _, ok := fieldSeen[backgroundtask.FieldTriggersJSON]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldTriggersJSON)
				fieldSeen[backgroundtask.FieldTriggersJSON] = struct{}{}
			}
		case "model":
			if _, ok := fieldSeen[backgroundtask.FieldModel]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldModel)
				fieldSeen[backgroundtask.FieldModel] = struct{}{}
			}
		case "provider":
			if _, ok := fieldSeen[backgroundtask.FieldProvider]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldProvider)
				fieldSeen[backgroundtask.FieldProvider] = struct{}{}
			}
		case "executionTarget":
			if _, ok := fieldSeen[backgroundtask.FieldExecutionTarget]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldExecutionTarget)
				fieldSeen[backgroundtask.FieldExecutionTarget] = struct{}{}
			}
		case "taskCreatedAt":
			if _, ok := fieldSeen[backgroundtask.FieldTaskCreatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldTaskCreatedAt)
				fieldSeen[backgroundtask.FieldTaskCreatedAt] = struct{}{}
			}
		case "lastAttemptAt":
			if _, ok := fieldSeen[backgroundtask.FieldLastAttemptAt]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldLastAttemptAt)
				fieldSeen[backgroundtask.FieldLastAttemptAt] = struct{}{}
			}
		case "lastRunID":
			if _, ok := fieldSeen[backgroundtask.FieldLastRunID]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldLastRunID)
				fieldSeen[backgroundtask.FieldLastRunID] = struct{}{}
			}
		case "lastRunAt":
			if _, ok := fieldSeen[backgroundtask.FieldLastRunAt]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldLastRunAt)
				fieldSeen[backgroundtask.FieldLastRunAt] = struct{}{}
			}
		case "lastRunSummary":
			if _, ok := fieldSeen[backgroundtask.FieldLastRunSummary]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldLastRunSummary)
				fieldSeen[backgroundtask.FieldLastRunSummary] = struct{}{}
			}
		case "lastRunError":
			if _, ok := fieldSeen[backgroundtask.FieldLastRunError]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldLastRunError)
				fieldSeen[backgroundtask.FieldLastRunError] = struct{}{}
			}
		case "revision":
			if _, ok := fieldSeen[backgroundtask.FieldRevision]; !ok {
				selectedFields = append(selectedFields, backgroundtask.FieldRevision)
				fieldSeen[backgroundtask.FieldRevision] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type backgroundtaskPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []BackgroundTaskPaginateOption
}

func newBackgroundTaskPaginateArgs(rv map[string]any) *backgroundtaskPaginateArgs {
	args := &backgroundtaskPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*BackgroundTaskWhereInput); ok {
		args.opts = append(args.opts, WithBackgroundTaskFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *BackgroundTaskArtifactQuery) CollectFields(ctx context.Context, satisfies ...string) (*BackgroundTaskArtifactQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *BackgroundTaskArtifactQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(backgroundtaskartifact.Columns))
		selectedFields = []string{backgroundtaskartifact.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query

		case "task":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskImplementors)...); err != nil {
				return err
			}
			_q.withTask = query
		case "createdAt":
			if _, ok := fieldSeen[backgroundtaskartifact.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskartifact.FieldCreatedAt)
				fieldSeen[backgroundtaskartifact.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[backgroundtaskartifact.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskartifact.FieldUpdatedAt)
				fieldSeen[backgroundtaskartifact.FieldUpdatedAt] = struct{}{}
			}
		case "body":
			if _, ok := fieldSeen[backgroundtaskartifact.FieldBody]; !ok {
				selectedFields = append(selectedFields, backgroundtaskartifact.FieldBody)
				fieldSeen[backgroundtaskartifact.FieldBody] = struct{}{}
			}
		case "revision":
			if _, ok := fieldSeen[backgroundtaskartifact.FieldRevision]; !ok {
				selectedFields = append(selectedFields, backgroundtaskartifact.FieldRevision)
				fieldSeen[backgroundtaskartifact.FieldRevision] = struct{}{}
			}
		case "updatedByRunID":
			if _, ok := fieldSeen[backgroundtaskartifact.FieldUpdatedByRunID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskartifact.FieldUpdatedByRunID)
				fieldSeen[backgroundtaskartifact.FieldUpdatedByRunID] = struct{}{}
			}
		case "contentType":
			if _, ok := fieldSeen[backgroundtaskartifact.FieldContentType]; !ok {
				selectedFields = append(selectedFields, backgroundtaskartifact.FieldContentType)
				fieldSeen[backgroundtaskartifact.FieldContentType] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type backgroundtaskartifactPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []BackgroundTaskArtifactPaginateOption
}

func newBackgroundTaskArtifactPaginateArgs(rv map[string]any) *backgroundtaskartifactPaginateArgs {
	args := &backgroundtaskartifactPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*BackgroundTaskArtifactWhereInput); ok {
		args.opts = append(args.opts, WithBackgroundTaskArtifactFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *BackgroundTaskRunQuery) CollectFields(ctx context.Context, satisfies ...string) (*BackgroundTaskRunQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *BackgroundTaskRunQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(backgroundtaskrun.Columns))
		selectedFields = []string{backgroundtaskrun.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query

		case "task":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskImplementors)...); err != nil {
				return err
			}
			_q.withTask = query

		case "cloudEvent":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CloudEventClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, cloudeventImplementors)...); err != nil {
				return err
			}
			_q.withCloudEvent = query
			if _, ok := fieldSeen[backgroundtaskrun.FieldCloudEventID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldCloudEventID)
				fieldSeen[backgroundtaskrun.FieldCloudEventID] = struct{}{}
			}

		case "events":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskRunEventClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskruneventImplementors)...); err != nil {
				return err
			}
			_q.WithNamedEvents(alias, func(wq *BackgroundTaskRunEventQuery) {
				*wq = *query
			})
		case "createdAt":
			if _, ok := fieldSeen[backgroundtaskrun.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldCreatedAt)
				fieldSeen[backgroundtaskrun.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[backgroundtaskrun.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldUpdatedAt)
				fieldSeen[backgroundtaskrun.FieldUpdatedAt] = struct{}{}
			}
		case "runID":
			if _, ok := fieldSeen[backgroundtaskrun.FieldRunID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldRunID)
				fieldSeen[backgroundtaskrun.FieldRunID] = struct{}{}
			}
		case "trigger":
			if _, ok := fieldSeen[backgroundtaskrun.FieldTrigger]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldTrigger)
				fieldSeen[backgroundtaskrun.FieldTrigger] = struct{}{}
			}
		case "status":
			if _, ok := fieldSeen[backgroundtaskrun.FieldStatus]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldStatus)
				fieldSeen[backgroundtaskrun.FieldStatus] = struct{}{}
			}
		case "executor":
			if _, ok := fieldSeen[backgroundtaskrun.FieldExecutor]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldExecutor)
				fieldSeen[backgroundtaskrun.FieldExecutor] = struct{}{}
			}
		case "attempt":
			if _, ok := fieldSeen[backgroundtaskrun.FieldAttempt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldAttempt)
				fieldSeen[backgroundtaskrun.FieldAttempt] = struct{}{}
			}
		case "model":
			if _, ok := fieldSeen[backgroundtaskrun.FieldModel]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldModel)
				fieldSeen[backgroundtaskrun.FieldModel] = struct{}{}
			}
		case "provider":
			if _, ok := fieldSeen[backgroundtaskrun.FieldProvider]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldProvider)
				fieldSeen[backgroundtaskrun.FieldProvider] = struct{}{}
			}
		case "useCase":
			if _, ok := fieldSeen[backgroundtaskrun.FieldUseCase]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldUseCase)
				fieldSeen[backgroundtaskrun.FieldUseCase] = struct{}{}
			}
		case "subUseCase":
			if _, ok := fieldSeen[backgroundtaskrun.FieldSubUseCase]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldSubUseCase)
				fieldSeen[backgroundtaskrun.FieldSubUseCase] = struct{}{}
			}
		case "previousRunID":
			if _, ok := fieldSeen[backgroundtaskrun.FieldPreviousRunID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldPreviousRunID)
				fieldSeen[backgroundtaskrun.FieldPreviousRunID] = struct{}{}
			}
		case "retryOfRunID":
			if _, ok := fieldSeen[backgroundtaskrun.FieldRetryOfRunID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldRetryOfRunID)
				fieldSeen[backgroundtaskrun.FieldRetryOfRunID] = struct{}{}
			}
		case "localRunID":
			if _, ok := fieldSeen[backgroundtaskrun.FieldLocalRunID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldLocalRunID)
				fieldSeen[backgroundtaskrun.FieldLocalRunID] = struct{}{}
			}
		case "requestedContext":
			if _, ok := fieldSeen[backgroundtaskrun.FieldRequestedContext]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldRequestedContext)
				fieldSeen[backgroundtaskrun.FieldRequestedContext] = struct{}{}
			}
		case "summary":
			if _, ok := fieldSeen[backgroundtaskrun.FieldSummary]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldSummary)
				fieldSeen[backgroundtaskrun.FieldSummary] = struct{}{}
			}
		case "error":
			if _, ok := fieldSeen[backgroundtaskrun.FieldError]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldError)
				fieldSeen[backgroundtaskrun.FieldError] = struct{}{}
			}
		case "errorCode":
			if _, ok := fieldSeen[backgroundtaskrun.FieldErrorCode]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldErrorCode)
				fieldSeen[backgroundtaskrun.FieldErrorCode] = struct{}{}
			}
		case "errorDetails":
			if _, ok := fieldSeen[backgroundtaskrun.FieldErrorDetails]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldErrorDetails)
				fieldSeen[backgroundtaskrun.FieldErrorDetails] = struct{}{}
			}
		case "temporalWorkflowID":
			if _, ok := fieldSeen[backgroundtaskrun.FieldTemporalWorkflowID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldTemporalWorkflowID)
				fieldSeen[backgroundtaskrun.FieldTemporalWorkflowID] = struct{}{}
			}
		case "temporalRunID":
			if _, ok := fieldSeen[backgroundtaskrun.FieldTemporalRunID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldTemporalRunID)
				fieldSeen[backgroundtaskrun.FieldTemporalRunID] = struct{}{}
			}
		case "temporalStatus":
			if _, ok := fieldSeen[backgroundtaskrun.FieldTemporalStatus]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldTemporalStatus)
				fieldSeen[backgroundtaskrun.FieldTemporalStatus] = struct{}{}
			}
		case "temporalStartedAt":
			if _, ok := fieldSeen[backgroundtaskrun.FieldTemporalStartedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldTemporalStartedAt)
				fieldSeen[backgroundtaskrun.FieldTemporalStartedAt] = struct{}{}
			}
		case "temporalClosedAt":
			if _, ok := fieldSeen[backgroundtaskrun.FieldTemporalClosedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldTemporalClosedAt)
				fieldSeen[backgroundtaskrun.FieldTemporalClosedAt] = struct{}{}
			}
		case "cancelRequestedAt":
			if _, ok := fieldSeen[backgroundtaskrun.FieldCancelRequestedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldCancelRequestedAt)
				fieldSeen[backgroundtaskrun.FieldCancelRequestedAt] = struct{}{}
			}
		case "progressPercent":
			if _, ok := fieldSeen[backgroundtaskrun.FieldProgressPercent]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldProgressPercent)
				fieldSeen[backgroundtaskrun.FieldProgressPercent] = struct{}{}
			}
		case "progressMessage":
			if _, ok := fieldSeen[backgroundtaskrun.FieldProgressMessage]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldProgressMessage)
				fieldSeen[backgroundtaskrun.FieldProgressMessage] = struct{}{}
			}
		case "lastHeartbeatAt":
			if _, ok := fieldSeen[backgroundtaskrun.FieldLastHeartbeatAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldLastHeartbeatAt)
				fieldSeen[backgroundtaskrun.FieldLastHeartbeatAt] = struct{}{}
			}
		case "startedAt":
			if _, ok := fieldSeen[backgroundtaskrun.FieldStartedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldStartedAt)
				fieldSeen[backgroundtaskrun.FieldStartedAt] = struct{}{}
			}
		case "completedAt":
			if _, ok := fieldSeen[backgroundtaskrun.FieldCompletedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldCompletedAt)
				fieldSeen[backgroundtaskrun.FieldCompletedAt] = struct{}{}
			}
		case "cloudEventID":
			if _, ok := fieldSeen[backgroundtaskrun.FieldCloudEventID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldCloudEventID)
				fieldSeen[backgroundtaskrun.FieldCloudEventID] = struct{}{}
			}
		case "revision":
			if _, ok := fieldSeen[backgroundtaskrun.FieldRevision]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrun.FieldRevision)
				fieldSeen[backgroundtaskrun.FieldRevision] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type backgroundtaskrunPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []BackgroundTaskRunPaginateOption
}

func newBackgroundTaskRunPaginateArgs(rv map[string]any) *backgroundtaskrunPaginateArgs {
	args := &backgroundtaskrunPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*BackgroundTaskRunWhereInput); ok {
		args.opts = append(args.opts, WithBackgroundTaskRunFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *BackgroundTaskRunEventQuery) CollectFields(ctx context.Context, satisfies ...string) (*BackgroundTaskRunEventQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *BackgroundTaskRunEventQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(backgroundtaskrunevent.Columns))
		selectedFields = []string{backgroundtaskrunevent.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query

		case "task":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskImplementors)...); err != nil {
				return err
			}
			_q.withTask = query

		case "run":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskRunClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskrunImplementors)...); err != nil {
				return err
			}
			_q.withRun = query
		case "createdAt":
			if _, ok := fieldSeen[backgroundtaskrunevent.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrunevent.FieldCreatedAt)
				fieldSeen[backgroundtaskrunevent.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[backgroundtaskrunevent.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrunevent.FieldUpdatedAt)
				fieldSeen[backgroundtaskrunevent.FieldUpdatedAt] = struct{}{}
			}
		case "seq":
			if _, ok := fieldSeen[backgroundtaskrunevent.FieldSeq]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrunevent.FieldSeq)
				fieldSeen[backgroundtaskrunevent.FieldSeq] = struct{}{}
			}
		case "eventType":
			if _, ok := fieldSeen[backgroundtaskrunevent.FieldEventType]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrunevent.FieldEventType)
				fieldSeen[backgroundtaskrunevent.FieldEventType] = struct{}{}
			}
		case "eventJSON":
			if _, ok := fieldSeen[backgroundtaskrunevent.FieldEventJSON]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrunevent.FieldEventJSON)
				fieldSeen[backgroundtaskrunevent.FieldEventJSON] = struct{}{}
			}
		case "receivedAt":
			if _, ok := fieldSeen[backgroundtaskrunevent.FieldReceivedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskrunevent.FieldReceivedAt)
				fieldSeen[backgroundtaskrunevent.FieldReceivedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type backgroundtaskruneventPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []BackgroundTaskRunEventPaginateOption
}

func newBackgroundTaskRunEventPaginateArgs(rv map[string]any) *backgroundtaskruneventPaginateArgs {
	args := &backgroundtaskruneventPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*BackgroundTaskRunEventWhereInput); ok {
		args.opts = append(args.opts, WithBackgroundTaskRunEventFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *BackgroundTaskScheduleStateQuery) CollectFields(ctx context.Context, satisfies ...string) (*BackgroundTaskScheduleStateQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *BackgroundTaskScheduleStateQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(backgroundtaskschedulestate.Columns))
		selectedFields = []string{backgroundtaskschedulestate.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query

		case "task":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskImplementors)...); err != nil {
				return err
			}
			_q.withTask = query
		case "createdAt":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldCreatedAt)
				fieldSeen[backgroundtaskschedulestate.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldUpdatedAt)
				fieldSeen[backgroundtaskschedulestate.FieldUpdatedAt] = struct{}{}
			}
		case "triggerType":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldTriggerType]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldTriggerType)
				fieldSeen[backgroundtaskschedulestate.FieldTriggerType] = struct{}{}
			}
		case "scheduleKey":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldScheduleKey]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldScheduleKey)
				fieldSeen[backgroundtaskschedulestate.FieldScheduleKey] = struct{}{}
			}
		case "lastEvaluatedAt":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldLastEvaluatedAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldLastEvaluatedAt)
				fieldSeen[backgroundtaskschedulestate.FieldLastEvaluatedAt] = struct{}{}
			}
		case "lastDueAt":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldLastDueAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldLastDueAt)
				fieldSeen[backgroundtaskschedulestate.FieldLastDueAt] = struct{}{}
			}
		case "lastTriggeredAt":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldLastTriggeredAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldLastTriggeredAt)
				fieldSeen[backgroundtaskschedulestate.FieldLastTriggeredAt] = struct{}{}
			}
		case "lastRunID":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldLastRunID]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldLastRunID)
				fieldSeen[backgroundtaskschedulestate.FieldLastRunID] = struct{}{}
			}
		case "leaseOwner":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldLeaseOwner]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldLeaseOwner)
				fieldSeen[backgroundtaskschedulestate.FieldLeaseOwner] = struct{}{}
			}
		case "leaseExpiresAt":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldLeaseExpiresAt]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldLeaseExpiresAt)
				fieldSeen[backgroundtaskschedulestate.FieldLeaseExpiresAt] = struct{}{}
			}
		case "revision":
			if _, ok := fieldSeen[backgroundtaskschedulestate.FieldRevision]; !ok {
				selectedFields = append(selectedFields, backgroundtaskschedulestate.FieldRevision)
				fieldSeen[backgroundtaskschedulestate.FieldRevision] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type backgroundtaskschedulestatePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []BackgroundTaskScheduleStatePaginateOption
}

func newBackgroundTaskScheduleStatePaginateArgs(rv map[string]any) *backgroundtaskschedulestatePaginateArgs {
	args := &backgroundtaskschedulestatePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*BackgroundTaskScheduleStateWhereInput); ok {
		args.opts = append(args.opts, WithBackgroundTaskScheduleStateFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *CloudEventQuery) CollectFields(ctx context.Context, satisfies ...string) (*CloudEventQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *CloudEventQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(cloudevent.Columns))
		selectedFields = []string{cloudevent.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query

		case "runs":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskRunClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskrunImplementors)...); err != nil {
				return err
			}
			_q.WithNamedRuns(alias, func(wq *BackgroundTaskRunQuery) {
				*wq = *query
			})
		case "createdAt":
			if _, ok := fieldSeen[cloudevent.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldCreatedAt)
				fieldSeen[cloudevent.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[cloudevent.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldUpdatedAt)
				fieldSeen[cloudevent.FieldUpdatedAt] = struct{}{}
			}
		case "source":
			if _, ok := fieldSeen[cloudevent.FieldSource]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldSource)
				fieldSeen[cloudevent.FieldSource] = struct{}{}
			}
		case "sourceEventID":
			if _, ok := fieldSeen[cloudevent.FieldSourceEventID]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldSourceEventID)
				fieldSeen[cloudevent.FieldSourceEventID] = struct{}{}
			}
		case "sourceAccountID":
			if _, ok := fieldSeen[cloudevent.FieldSourceAccountID]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldSourceAccountID)
				fieldSeen[cloudevent.FieldSourceAccountID] = struct{}{}
			}
		case "eventType":
			if _, ok := fieldSeen[cloudevent.FieldEventType]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldEventType)
				fieldSeen[cloudevent.FieldEventType] = struct{}{}
			}
		case "subject":
			if _, ok := fieldSeen[cloudevent.FieldSubject]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldSubject)
				fieldSeen[cloudevent.FieldSubject] = struct{}{}
			}
		case "text":
			if _, ok := fieldSeen[cloudevent.FieldText]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldText)
				fieldSeen[cloudevent.FieldText] = struct{}{}
			}
		case "routingJSON":
			if _, ok := fieldSeen[cloudevent.FieldRoutingJSON]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldRoutingJSON)
				fieldSeen[cloudevent.FieldRoutingJSON] = struct{}{}
			}
		case "dedupeKey":
			if _, ok := fieldSeen[cloudevent.FieldDedupeKey]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldDedupeKey)
				fieldSeen[cloudevent.FieldDedupeKey] = struct{}{}
			}
		case "routingStatus":
			if _, ok := fieldSeen[cloudevent.FieldRoutingStatus]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldRoutingStatus)
				fieldSeen[cloudevent.FieldRoutingStatus] = struct{}{}
			}
		case "matchedTaskCount":
			if _, ok := fieldSeen[cloudevent.FieldMatchedTaskCount]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldMatchedTaskCount)
				fieldSeen[cloudevent.FieldMatchedTaskCount] = struct{}{}
			}
		case "occurredAt":
			if _, ok := fieldSeen[cloudevent.FieldOccurredAt]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldOccurredAt)
				fieldSeen[cloudevent.FieldOccurredAt] = struct{}{}
			}
		case "receivedAt":
			if _, ok := fieldSeen[cloudevent.FieldReceivedAt]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldReceivedAt)
				fieldSeen[cloudevent.FieldReceivedAt] = struct{}{}
			}
		case "routedAt":
			if _, ok := fieldSeen[cloudevent.FieldRoutedAt]; !ok {
				selectedFields = append(selectedFields, cloudevent.FieldRoutedAt)
				fieldSeen[cloudevent.FieldRoutedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type cloudeventPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []CloudEventPaginateOption
}

func newCloudEventPaginateArgs(rv map[string]any) *cloudeventPaginateArgs {
	args := &cloudeventPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*CloudEventWhereInput); ok {
		args.opts = append(args.opts, WithCloudEventFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *CreditLedgerQuery) CollectFields(ctx context.Context, satisfies ...string) (*CreditLedgerQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *CreditLedgerQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(creditledger.Columns))
		selectedFields = []string{creditledger.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query
		case "delta":
			if _, ok := fieldSeen[creditledger.FieldDelta]; !ok {
				selectedFields = append(selectedFields, creditledger.FieldDelta)
				fieldSeen[creditledger.FieldDelta] = struct{}{}
			}
		case "reason":
			if _, ok := fieldSeen[creditledger.FieldReason]; !ok {
				selectedFields = append(selectedFields, creditledger.FieldReason)
				fieldSeen[creditledger.FieldReason] = struct{}{}
			}
		case "requestID":
			if _, ok := fieldSeen[creditledger.FieldRequestID]; !ok {
				selectedFields = append(selectedFields, creditledger.FieldRequestID)
				fieldSeen[creditledger.FieldRequestID] = struct{}{}
			}
		case "ts":
			if _, ok := fieldSeen[creditledger.FieldTs]; !ok {
				selectedFields = append(selectedFields, creditledger.FieldTs)
				fieldSeen[creditledger.FieldTs] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type creditledgerPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []CreditLedgerPaginateOption
}

func newCreditLedgerPaginateArgs(rv map[string]any) *creditledgerPaginateArgs {
	args := &creditledgerPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*CreditLedgerWhereInput); ok {
		args.opts = append(args.opts, WithCreditLedgerFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *GoogleWatchQuery) CollectFields(ctx context.Context, satisfies ...string) (*GoogleWatchQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *GoogleWatchQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(googlewatch.Columns))
		selectedFields = []string{googlewatch.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query
		case "createdAt":
			if _, ok := fieldSeen[googlewatch.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldCreatedAt)
				fieldSeen[googlewatch.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[googlewatch.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldUpdatedAt)
				fieldSeen[googlewatch.FieldUpdatedAt] = struct{}{}
			}
		case "kind":
			if _, ok := fieldSeen[googlewatch.FieldKind]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldKind)
				fieldSeen[googlewatch.FieldKind] = struct{}{}
			}
		case "accountEmail":
			if _, ok := fieldSeen[googlewatch.FieldAccountEmail]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldAccountEmail)
				fieldSeen[googlewatch.FieldAccountEmail] = struct{}{}
			}
		case "channelID":
			if _, ok := fieldSeen[googlewatch.FieldChannelID]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldChannelID)
				fieldSeen[googlewatch.FieldChannelID] = struct{}{}
			}
		case "resourceID":
			if _, ok := fieldSeen[googlewatch.FieldResourceID]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldResourceID)
				fieldSeen[googlewatch.FieldResourceID] = struct{}{}
			}
		case "historyID":
			if _, ok := fieldSeen[googlewatch.FieldHistoryID]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldHistoryID)
				fieldSeen[googlewatch.FieldHistoryID] = struct{}{}
			}
		case "expiresAt":
			if _, ok := fieldSeen[googlewatch.FieldExpiresAt]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldExpiresAt)
				fieldSeen[googlewatch.FieldExpiresAt] = struct{}{}
			}
		case "renewClaimedAt":
			if _, ok := fieldSeen[googlewatch.FieldRenewClaimedAt]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldRenewClaimedAt)
				fieldSeen[googlewatch.FieldRenewClaimedAt] = struct{}{}
			}
		case "lastError":
			if _, ok := fieldSeen[googlewatch.FieldLastError]; !ok {
				selectedFields = append(selectedFields, googlewatch.FieldLastError)
				fieldSeen[googlewatch.FieldLastError] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type googlewatchPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []GoogleWatchPaginateOption
}

func newGoogleWatchPaginateArgs(rv map[string]any) *googlewatchPaginateArgs {
	args := &googlewatchPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*GoogleWatchWhereInput); ok {
		args.opts = append(args.opts, WithGoogleWatchFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *LLMUsageQuery) CollectFields(ctx context.Context, satisfies ...string) (*LLMUsageQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *LLMUsageQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(llmusage.Columns))
		selectedFields = []string{llmusage.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query
		case "model":
			if _, ok := fieldSeen[llmusage.FieldModel]; !ok {
				selectedFields = append(selectedFields, llmusage.FieldModel)
				fieldSeen[llmusage.FieldModel] = struct{}{}
			}
		case "useCase":
			if _, ok := fieldSeen[llmusage.FieldUseCase]; !ok {
				selectedFields = append(selectedFields, llmusage.FieldUseCase)
				fieldSeen[llmusage.FieldUseCase] = struct{}{}
			}
		case "subUseCase":
			if _, ok := fieldSeen[llmusage.FieldSubUseCase]; !ok {
				selectedFields = append(selectedFields, llmusage.FieldSubUseCase)
				fieldSeen[llmusage.FieldSubUseCase] = struct{}{}
			}
		case "agentName":
			if _, ok := fieldSeen[llmusage.FieldAgentName]; !ok {
				selectedFields = append(selectedFields, llmusage.FieldAgentName)
				fieldSeen[llmusage.FieldAgentName] = struct{}{}
			}
		case "inputTokens":
			if _, ok := fieldSeen[llmusage.FieldInputTokens]; !ok {
				selectedFields = append(selectedFields, llmusage.FieldInputTokens)
				fieldSeen[llmusage.FieldInputTokens] = struct{}{}
			}
		case "outputTokens":
			if _, ok := fieldSeen[llmusage.FieldOutputTokens]; !ok {
				selectedFields = append(selectedFields, llmusage.FieldOutputTokens)
				fieldSeen[llmusage.FieldOutputTokens] = struct{}{}
			}
		case "costUnits":
			if _, ok := fieldSeen[llmusage.FieldCostUnits]; !ok {
				selectedFields = append(selectedFields, llmusage.FieldCostUnits)
				fieldSeen[llmusage.FieldCostUnits] = struct{}{}
			}
		case "requestID":
			if _, ok := fieldSeen[llmusage.FieldRequestID]; !ok {
				selectedFields = append(selectedFields, llmusage.FieldRequestID)
				fieldSeen[llmusage.FieldRequestID] = struct{}{}
			}
		case "ts":
			if _, ok := fieldSeen[llmusage.FieldTs]; !ok {
				selectedFields = append(selectedFields, llmusage.FieldTs)
				fieldSeen[llmusage.FieldTs] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type llmusagePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []LLMUsagePaginateOption
}

func newLLMUsagePaginateArgs(rv map[string]any) *llmusagePaginateArgs {
	args := &llmusagePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*LLMUsageWhereInput); ok {
		args.opts = append(args.opts, WithLLMUsageFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *MCPConnectionQuery) CollectFields(ctx context.Context, satisfies ...string) (*MCPConnectionQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *MCPConnectionQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(mcpconnection.Columns))
		selectedFields = []string{mcpconnection.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query
		case "createdAt":
			if _, ok := fieldSeen[mcpconnection.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, mcpconnection.FieldCreatedAt)
				fieldSeen[mcpconnection.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[mcpconnection.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, mcpconnection.FieldUpdatedAt)
				fieldSeen[mcpconnection.FieldUpdatedAt] = struct{}{}
			}
		case "connector":
			if _, ok := fieldSeen[mcpconnection.FieldConnector]; !ok {
				selectedFields = append(selectedFields, mcpconnection.FieldConnector)
				fieldSeen[mcpconnection.FieldConnector] = struct{}{}
			}
		case "audience":
			if _, ok := fieldSeen[mcpconnection.FieldAudience]; !ok {
				selectedFields = append(selectedFields, mcpconnection.FieldAudience)
				fieldSeen[mcpconnection.FieldAudience] = struct{}{}
			}
		case "scopes":
			if _, ok := fieldSeen[mcpconnection.FieldScopes]; !ok {
				selectedFields = append(selectedFields, mcpconnection.FieldScopes)
				fieldSeen[mcpconnection.FieldScopes] = struct{}{}
			}
		case "connectedAt":
			if _, ok := fieldSeen[mcpconnection.FieldConnectedAt]; !ok {
				selectedFields = append(selectedFields, mcpconnection.FieldConnectedAt)
				fieldSeen[mcpconnection.FieldConnectedAt] = struct{}{}
			}
		case "lastUsedAt":
			if _, ok := fieldSeen[mcpconnection.FieldLastUsedAt]; !ok {
				selectedFields = append(selectedFields, mcpconnection.FieldLastUsedAt)
				fieldSeen[mcpconnection.FieldLastUsedAt] = struct{}{}
			}
		case "expiresAt":
			if _, ok := fieldSeen[mcpconnection.FieldExpiresAt]; !ok {
				selectedFields = append(selectedFields, mcpconnection.FieldExpiresAt)
				fieldSeen[mcpconnection.FieldExpiresAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type mcpconnectionPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []MCPConnectionPaginateOption
}

func newMCPConnectionPaginateArgs(rv map[string]any) *mcpconnectionPaginateArgs {
	args := &mcpconnectionPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*MCPConnectionWhereInput); ok {
		args.opts = append(args.opts, WithMCPConnectionFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *MeetingMinuteUsageQuery) CollectFields(ctx context.Context, satisfies ...string) (*MeetingMinuteUsageQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *MeetingMinuteUsageQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(meetingminuteusage.Columns))
		selectedFields = []string{meetingminuteusage.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query
		case "createdAt":
			if _, ok := fieldSeen[meetingminuteusage.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, meetingminuteusage.FieldCreatedAt)
				fieldSeen[meetingminuteusage.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[meetingminuteusage.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, meetingminuteusage.FieldUpdatedAt)
				fieldSeen[meetingminuteusage.FieldUpdatedAt] = struct{}{}
			}
		case "period":
			if _, ok := fieldSeen[meetingminuteusage.FieldPeriod]; !ok {
				selectedFields = append(selectedFields, meetingminuteusage.FieldPeriod)
				fieldSeen[meetingminuteusage.FieldPeriod] = struct{}{}
			}
		case "usedSeconds":
			if _, ok := fieldSeen[meetingminuteusage.FieldUsedSeconds]; !ok {
				selectedFields = append(selectedFields, meetingminuteusage.FieldUsedSeconds)
				fieldSeen[meetingminuteusage.FieldUsedSeconds] = struct{}{}
			}
		case "reservedSeconds":
			if _, ok := fieldSeen[meetingminuteusage.FieldReservedSeconds]; !ok {
				selectedFields = append(selectedFields, meetingminuteusage.FieldReservedSeconds)
				fieldSeen[meetingminuteusage.FieldReservedSeconds] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type meetingminuteusagePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []MeetingMinuteUsagePaginateOption
}

func newMeetingMinuteUsagePaginateArgs(rv map[string]any) *meetingminuteusagePaginateArgs {
	args := &meetingminuteusagePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*MeetingMinuteUsageWhereInput); ok {
		args.opts = append(args.opts, WithMeetingMinuteUsageFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *OAuthConnectionQuery) CollectFields(ctx context.Context, satisfies ...string) (*OAuthConnectionQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *OAuthConnectionQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(oauthconnection.Columns))
		selectedFields = []string{oauthconnection.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query
		case "createdAt":
			if _, ok := fieldSeen[oauthconnection.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, oauthconnection.FieldCreatedAt)
				fieldSeen[oauthconnection.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[oauthconnection.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, oauthconnection.FieldUpdatedAt)
				fieldSeen[oauthconnection.FieldUpdatedAt] = struct{}{}
			}
		case "provider":
			if _, ok := fieldSeen[oauthconnection.FieldProvider]; !ok {
				selectedFields = append(selectedFields, oauthconnection.FieldProvider)
				fieldSeen[oauthconnection.FieldProvider] = struct{}{}
			}
		case "scopes":
			if _, ok := fieldSeen[oauthconnection.FieldScopes]; !ok {
				selectedFields = append(selectedFields, oauthconnection.FieldScopes)
				fieldSeen[oauthconnection.FieldScopes] = struct{}{}
			}
		case "externalAccountID":
			if _, ok := fieldSeen[oauthconnection.FieldExternalAccountID]; !ok {
				selectedFields = append(selectedFields, oauthconnection.FieldExternalAccountID)
				fieldSeen[oauthconnection.FieldExternalAccountID] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type oauthconnectionPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []OAuthConnectionPaginateOption
}

func newOAuthConnectionPaginateArgs(rv map[string]any) *oauthconnectionPaginateArgs {
	args := &oauthconnectionPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*OAuthConnectionWhereInput); ok {
		args.opts = append(args.opts, WithOAuthConnectionFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *OAuthPendingQuery) CollectFields(ctx context.Context, satisfies ...string) (*OAuthPendingQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *OAuthPendingQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(oauthpending.Columns))
		selectedFields = []string{oauthpending.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "createdAt":
			if _, ok := fieldSeen[oauthpending.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, oauthpending.FieldCreatedAt)
				fieldSeen[oauthpending.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[oauthpending.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, oauthpending.FieldUpdatedAt)
				fieldSeen[oauthpending.FieldUpdatedAt] = struct{}{}
			}
		case "state":
			if _, ok := fieldSeen[oauthpending.FieldState]; !ok {
				selectedFields = append(selectedFields, oauthpending.FieldState)
				fieldSeen[oauthpending.FieldState] = struct{}{}
			}
		case "provider":
			if _, ok := fieldSeen[oauthpending.FieldProvider]; !ok {
				selectedFields = append(selectedFields, oauthpending.FieldProvider)
				fieldSeen[oauthpending.FieldProvider] = struct{}{}
			}
		case "expiresAt":
			if _, ok := fieldSeen[oauthpending.FieldExpiresAt]; !ok {
				selectedFields = append(selectedFields, oauthpending.FieldExpiresAt)
				fieldSeen[oauthpending.FieldExpiresAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type oauthpendingPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []OAuthPendingPaginateOption
}

func newOAuthPendingPaginateArgs(rv map[string]any) *oauthpendingPaginateArgs {
	args := &oauthpendingPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*OAuthPendingWhereInput); ok {
		args.opts = append(args.opts, WithOAuthPendingFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *SubscriptionQuery) CollectFields(ctx context.Context, satisfies ...string) (*SubscriptionQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *SubscriptionQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(subscription.Columns))
		selectedFields = []string{subscription.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.withUser = query
		case "createdAt":
			if _, ok := fieldSeen[subscription.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, subscription.FieldCreatedAt)
				fieldSeen[subscription.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[subscription.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, subscription.FieldUpdatedAt)
				fieldSeen[subscription.FieldUpdatedAt] = struct{}{}
			}
		case "plan":
			if _, ok := fieldSeen[subscription.FieldPlan]; !ok {
				selectedFields = append(selectedFields, subscription.FieldPlan)
				fieldSeen[subscription.FieldPlan] = struct{}{}
			}
		case "status":
			if _, ok := fieldSeen[subscription.FieldStatus]; !ok {
				selectedFields = append(selectedFields, subscription.FieldStatus)
				fieldSeen[subscription.FieldStatus] = struct{}{}
			}
		case "trialExpiresAt":
			if _, ok := fieldSeen[subscription.FieldTrialExpiresAt]; !ok {
				selectedFields = append(selectedFields, subscription.FieldTrialExpiresAt)
				fieldSeen[subscription.FieldTrialExpiresAt] = struct{}{}
			}
		case "sanctionedCredits":
			if _, ok := fieldSeen[subscription.FieldSanctionedCredits]; !ok {
				selectedFields = append(selectedFields, subscription.FieldSanctionedCredits)
				fieldSeen[subscription.FieldSanctionedCredits] = struct{}{}
			}
		case "stripeCustomerID":
			if _, ok := fieldSeen[subscription.FieldStripeCustomerID]; !ok {
				selectedFields = append(selectedFields, subscription.FieldStripeCustomerID)
				fieldSeen[subscription.FieldStripeCustomerID] = struct{}{}
			}
		case "stripeSubscriptionID":
			if _, ok := fieldSeen[subscription.FieldStripeSubscriptionID]; !ok {
				selectedFields = append(selectedFields, subscription.FieldStripeSubscriptionID)
				fieldSeen[subscription.FieldStripeSubscriptionID] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type billingsubscriptionPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []BillingSubscriptionPaginateOption
}

func newBillingSubscriptionPaginateArgs(rv map[string]any) *billingsubscriptionPaginateArgs {
	args := &billingsubscriptionPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*BillingSubscriptionWhereInput); ok {
		args.opts = append(args.opts, WithBillingSubscriptionFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *UserQuery) CollectFields(ctx context.Context, satisfies ...string) (*UserQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *UserQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(user.Columns))
		selectedFields = []string{user.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "subscription":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&SubscriptionClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, subscriptionImplementors)...); err != nil {
				return err
			}
			_q.withSubscription = query

		case "ledgerEntries":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CreditLedgerClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, creditledgerImplementors)...); err != nil {
				return err
			}
			_q.WithNamedLedgerEntries(alias, func(wq *CreditLedgerQuery) {
				*wq = *query
			})

		case "meetingMinuteUsages":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&MeetingMinuteUsageClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, meetingminuteusageImplementors)...); err != nil {
				return err
			}
			_q.WithNamedMeetingMinuteUsages(alias, func(wq *MeetingMinuteUsageQuery) {
				*wq = *query
			})

		case "llmUsages":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&LLMUsageClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, llmusageImplementors)...); err != nil {
				return err
			}
			_q.WithNamedLlmUsages(alias, func(wq *LLMUsageQuery) {
				*wq = *query
			})

		case "oauthConnections":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OAuthConnectionClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, oauthconnectionImplementors)...); err != nil {
				return err
			}
			_q.WithNamedOauthConnections(alias, func(wq *OAuthConnectionQuery) {
				*wq = *query
			})

		case "mcpConnections":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&MCPConnectionClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, mcpconnectionImplementors)...); err != nil {
				return err
			}
			_q.WithNamedMcpConnections(alias, func(wq *MCPConnectionQuery) {
				*wq = *query
			})

		case "backgroundTasks":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskImplementors)...); err != nil {
				return err
			}
			_q.WithNamedBackgroundTasks(alias, func(wq *BackgroundTaskQuery) {
				*wq = *query
			})

		case "backgroundTaskArtifacts":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskArtifactClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskartifactImplementors)...); err != nil {
				return err
			}
			_q.WithNamedBackgroundTaskArtifacts(alias, func(wq *BackgroundTaskArtifactQuery) {
				*wq = *query
			})

		case "backgroundTaskRuns":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskRunClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskrunImplementors)...); err != nil {
				return err
			}
			_q.WithNamedBackgroundTaskRuns(alias, func(wq *BackgroundTaskRunQuery) {
				*wq = *query
			})

		case "backgroundTaskRunEvents":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskRunEventClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskruneventImplementors)...); err != nil {
				return err
			}
			_q.WithNamedBackgroundTaskRunEvents(alias, func(wq *BackgroundTaskRunEventQuery) {
				*wq = *query
			})

		case "backgroundTaskScheduleStates":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&BackgroundTaskScheduleStateClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, backgroundtaskschedulestateImplementors)...); err != nil {
				return err
			}
			_q.WithNamedBackgroundTaskScheduleStates(alias, func(wq *BackgroundTaskScheduleStateQuery) {
				*wq = *query
			})

		case "cloudEvents":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CloudEventClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, cloudeventImplementors)...); err != nil {
				return err
			}
			_q.WithNamedCloudEvents(alias, func(wq *CloudEventQuery) {
				*wq = *query
			})

		case "googleWatches":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&GoogleWatchClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, googlewatchImplementors)...); err != nil {
				return err
			}
			_q.WithNamedGoogleWatches(alias, func(wq *GoogleWatchQuery) {
				*wq = *query
			})
		case "createdAt":
			if _, ok := fieldSeen[user.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, user.FieldCreatedAt)
				fieldSeen[user.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[user.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, user.FieldUpdatedAt)
				fieldSeen[user.FieldUpdatedAt] = struct{}{}
			}
		case "email":
			if _, ok := fieldSeen[user.FieldEmail]; !ok {
				selectedFields = append(selectedFields, user.FieldEmail)
				fieldSeen[user.FieldEmail] = struct{}{}
			}
		case "workosUserID":
			if _, ok := fieldSeen[user.FieldWorkosUserID]; !ok {
				selectedFields = append(selectedFields, user.FieldWorkosUserID)
				fieldSeen[user.FieldWorkosUserID] = struct{}{}
			}
		case "workosOrgID":
			if _, ok := fieldSeen[user.FieldWorkosOrgID]; !ok {
				selectedFields = append(selectedFields, user.FieldWorkosOrgID)
				fieldSeen[user.FieldWorkosOrgID] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type userPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []UserPaginateOption
}

func newUserPaginateArgs(rv map[string]any) *userPaginateArgs {
	args := &userPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*UserWhereInput); ok {
		args.opts = append(args.opts, WithUserFilter(v.Filter))
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok || v == nil {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
