// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agentapproval"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agentdefinition"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agentdefinitionhistory"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agentsession"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agentsessionevent"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agenttoolcall"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agenttoolresultblob"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/agentturn"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtask"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskartifact"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskrun"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskrunevent"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/backgroundtaskschedulestate"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/cloudevent"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/creditledger"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/googlewatch"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/llmusage"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/llmusagehistory"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/mcpconnection"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/mcpconnectionhistory"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/meetingminuteusage"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/oauthconnection"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/oauthconnectionhistory"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/oauthpending"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/schema"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/subscription"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/subscriptionhistory"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/user"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/userhistory"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentapprovalMixin := schema.AgentApproval{}.Mixin()
	agentapprovalMixinFields0 := agentapprovalMixin[0].Fields()
	_ = agentapprovalMixinFields0
	agentapprovalFields := schema.AgentApproval{}.Fields()
	_ = agentapprovalFields
	// agentapprovalDescCreatedAt is the schema descriptor for created_at field.
	agentapprovalDescCreatedAt := agentapprovalMixinFields0[1].Descriptor()
	// agentapproval.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentapproval.DefaultCreatedAt = agentapprovalDescCreatedAt.Default.(func() time.Time)
	// agentapprovalDescUpdatedAt is the schema descriptor for updated_at field.
	agentapprovalDescUpdatedAt := agentapprovalMixinFields0[2].Descriptor()
	// agentapproval.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentapproval.DefaultUpdatedAt = agentapprovalDescUpdatedAt.Default.(func() time.Time)
	// agentapproval.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentapproval.UpdateDefaultUpdatedAt = agentapprovalDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentapprovalDescApprovalID is the schema descriptor for approval_id field.
	agentapprovalDescApprovalID := agentapprovalFields[0].Descriptor()
	// agentapproval.ApprovalIDValidator is a validator for the "approval_id" field. It is called by the builders before save.
	agentapproval.ApprovalIDValidator = agentapprovalDescApprovalID.Validators[0].(func(string) error)
	// agentapprovalDescTurnSeq is the schema descriptor for turn_seq field.
	agentapprovalDescTurnSeq := agentapprovalFields[1].Descriptor()
	// agentapproval.TurnSeqValidator is a validator for the "turn_seq" field. It is called by the builders before save.
	agentapproval.TurnSeqValidator = agentapprovalDescTurnSeq.Validators[0].(func(int) error)
	// agentapprovalDescToolCallIndex is the schema descriptor for tool_call_index field.
	agentapprovalDescToolCallIndex := agentapprovalFields[2].Descriptor()
	// agentapproval.DefaultToolCallIndex holds the default value on creation for the tool_call_index field.
	agentapproval.DefaultToolCallIndex = agentapprovalDescToolCallIndex.Default.(int)
	// agentapproval.ToolCallIndexValidator is a validator for the "tool_call_index" field. It is called by the builders before save.
	agentapproval.ToolCallIndexValidator = agentapprovalDescToolCallIndex.Validators[0].(func(int) error)
	// agentapprovalDescToolName is the schema descriptor for tool_name field.
	agentapprovalDescToolName := agentapprovalFields[3].Descriptor()
	// agentapproval.ToolNameValidator is a validator for the "tool_name" field. It is called by the builders before save.
	agentapproval.ToolNameValidator = agentapprovalDescToolName.Validators[0].(func(string) error)
	// agentapprovalDescStatus is the schema descriptor for status field.
	agentapprovalDescStatus := agentapprovalFields[5].Descriptor()
	// agentapproval.DefaultStatus holds the default value on creation for the status field.
	agentapproval.DefaultStatus = agentapprovalDescStatus.Default.(string)
	// agentapproval.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	agentapproval.StatusValidator = agentapprovalDescStatus.Validators[0].(func(string) error)
	// agentapprovalDescArgsRedactedJSON is the schema descriptor for args_redacted_json field.
	agentapprovalDescArgsRedactedJSON := agentapprovalFields[6].Descriptor()
	// agentapproval.ArgsRedactedJSONValidator is a validator for the "args_redacted_json" field. It is called by the builders before save.
	agentapproval.ArgsRedactedJSONValidator = agentapprovalDescArgsRedactedJSON.Validators[0].(func(string) error)
	// agentapprovalDescRequestedAt is the schema descriptor for requested_at field.
	agentapprovalDescRequestedAt := agentapprovalFields[10].Descriptor()
	// agentapproval.DefaultRequestedAt holds the default value on creation for the requested_at field.
	agentapproval.DefaultRequestedAt = agentapprovalDescRequestedAt.Default.(func() time.Time)
	// agentapprovalDescID is the schema descriptor for id field.
	agentapprovalDescID := agentapprovalMixinFields0[0].Descriptor()
	// agentapproval.DefaultID holds the default value on creation for the id field.
	agentapproval.DefaultID = agentapprovalDescID.Default.(func() uuid.UUID)
	agentdefinitionMixin := schema.AgentDefinition{}.Mixin()
	agentdefinitionMixinFields0 := agentdefinitionMixin[0].Fields()
	_ = agentdefinitionMixinFields0
	agentdefinitionFields := schema.AgentDefinition{}.Fields()
	_ = agentdefinitionFields
	// agentdefinitionDescCreatedAt is the schema descriptor for created_at field.
	agentdefinitionDescCreatedAt := agentdefinitionMixinFields0[1].Descriptor()
	// agentdefinition.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentdefinition.DefaultCreatedAt = agentdefinitionDescCreatedAt.Default.(func() time.Time)
	// agentdefinitionDescUpdatedAt is the schema descriptor for updated_at field.
	agentdefinitionDescUpdatedAt := agentdefinitionMixinFields0[2].Descriptor()
	// agentdefinition.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentdefinition.DefaultUpdatedAt = agentdefinitionDescUpdatedAt.Default.(func() time.Time)
	// agentdefinition.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentdefinition.UpdateDefaultUpdatedAt = agentdefinitionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentdefinitionDescSlug is the schema descriptor for slug field.
	agentdefinitionDescSlug := agentdefinitionFields[0].Descriptor()
	// agentdefinition.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	agentdefinition.SlugValidator = agentdefinitionDescSlug.Validators[0].(func(string) error)
	// agentdefinitionDescName is the schema descriptor for name field.
	agentdefinitionDescName := agentdefinitionFields[1].Descriptor()
	// agentdefinition.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agentdefinition.NameValidator = agentdefinitionDescName.Validators[0].(func(string) error)
	// agentdefinitionDescLimitsJSON is the schema descriptor for limits_json field.
	agentdefinitionDescLimitsJSON := agentdefinitionFields[5].Descriptor()
	// agentdefinition.LimitsJSONValidator is a validator for the "limits_json" field. It is called by the builders before save.
	agentdefinition.LimitsJSONValidator = agentdefinitionDescLimitsJSON.Validators[0].(func(string) error)
	// agentdefinitionDescToolsJSON is the schema descriptor for tools_json field.
	agentdefinitionDescToolsJSON := agentdefinitionFields[7].Descriptor()
	// agentdefinition.ToolsJSONValidator is a validator for the "tools_json" field. It is called by the builders before save.
	agentdefinition.ToolsJSONValidator = agentdefinitionDescToolsJSON.Validators[0].(func(string) error)
	// agentdefinitionDescChannelBindings is the schema descriptor for channel_bindings field.
	agentdefinitionDescChannelBindings := agentdefinitionFields[9].Descriptor()
	// agentdefinition.ChannelBindingsValidator is a validator for the "channel_bindings" field. It is called by the builders before save.
	agentdefinition.ChannelBindingsValidator = agentdefinitionDescChannelBindings.Validators[0].(func(string) error)
	// agentdefinitionDescSource is the schema descriptor for source field.
	agentdefinitionDescSource := agentdefinitionFields[11].Descriptor()
	// agentdefinition.DefaultSource holds the default value on creation for the source field.
	agentdefinition.DefaultSource = agentdefinitionDescSource.Default.(string)
	// agentdefinition.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	agentdefinition.SourceValidator = agentdefinitionDescSource.Validators[0].(func(string) error)
	// agentdefinitionDescRevision is the schema descriptor for revision field.
	agentdefinitionDescRevision := agentdefinitionFields[13].Descriptor()
	// agentdefinition.DefaultRevision holds the default value on creation for the revision field.
	agentdefinition.DefaultRevision = agentdefinitionDescRevision.Default.(int)
	// agentdefinition.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	agentdefinition.RevisionValidator = agentdefinitionDescRevision.Validators[0].(func(int) error)
	// agentdefinitionDescSourceFormat is the schema descriptor for source_format field.
	agentdefinitionDescSourceFormat := agentdefinitionFields[14].Descriptor()
	// agentdefinition.DefaultSourceFormat holds the default value on creation for the source_format field.
	agentdefinition.DefaultSourceFormat = agentdefinitionDescSourceFormat.Default.(string)
	// agentdefinition.SourceFormatValidator is a validator for the "source_format" field. It is called by the builders before save.
	agentdefinition.SourceFormatValidator = agentdefinitionDescSourceFormat.Validators[0].(func(string) error)
	// agentdefinitionDescManagedBy is the schema descriptor for managed_by field.
	agentdefinitionDescManagedBy := agentdefinitionFields[17].Descriptor()
	// agentdefinition.DefaultManagedBy holds the default value on creation for the managed_by field.
	agentdefinition.DefaultManagedBy = agentdefinitionDescManagedBy.Default.(string)
	// agentdefinition.ManagedByValidator is a validator for the "managed_by" field. It is called by the builders before save.
	agentdefinition.ManagedByValidator = agentdefinitionDescManagedBy.Validators[0].(func(string) error)
	// agentdefinitionDescAgentSyncState is the schema descriptor for agent_sync_state field.
	agentdefinitionDescAgentSyncState := agentdefinitionFields[18].Descriptor()
	// agentdefinition.DefaultAgentSyncState holds the default value on creation for the agent_sync_state field.
	agentdefinition.DefaultAgentSyncState = agentdefinitionDescAgentSyncState.Default.(string)
	// agentdefinition.AgentSyncStateValidator is a validator for the "agent_sync_state" field. It is called by the builders before save.
	agentdefinition.AgentSyncStateValidator = agentdefinitionDescAgentSyncState.Validators[0].(func(string) error)
	// agentdefinitionDescID is the schema descriptor for id field.
	agentdefinitionDescID := agentdefinitionMixinFields0[0].Descriptor()
	// agentdefinition.DefaultID holds the default value on creation for the id field.
	agentdefinition.DefaultID = agentdefinitionDescID.Default.(func() uuid.UUID)
	agentdefinitionhistoryMixin := schema.AgentDefinitionHistory{}.Mixin()
	agentdefinitionhistoryMixinFields0 := agentdefinitionhistoryMixin[0].Fields()
	_ = agentdefinitionhistoryMixinFields0
	agentdefinitionhistoryFields := schema.AgentDefinitionHistory{}.Fields()
	_ = agentdefinitionhistoryFields
	// agentdefinitionhistoryDescCreatedAt is the schema descriptor for created_at field.
	agentdefinitionhistoryDescCreatedAt := agentdefinitionhistoryMixinFields0[1].Descriptor()
	// agentdefinitionhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentdefinitionhistory.DefaultCreatedAt = agentdefinitionhistoryDescCreatedAt.Default.(func() time.Time)
	// agentdefinitionhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	agentdefinitionhistoryDescUpdatedAt := agentdefinitionhistoryMixinFields0[2].Descriptor()
	// agentdefinitionhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentdefinitionhistory.DefaultUpdatedAt = agentdefinitionhistoryDescUpdatedAt.Default.(func() time.Time)
	// agentdefinitionhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentdefinitionhistory.UpdateDefaultUpdatedAt = agentdefinitionhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentdefinitionhistoryDescHistoryTime is the schema descriptor for history_time field.
	agentdefinitionhistoryDescHistoryTime := agentdefinitionhistoryFields[1].Descriptor()
	// agentdefinitionhistory.DefaultHistoryTime holds the default value on creation for the history_time field.
	agentdefinitionhistory.DefaultHistoryTime = agentdefinitionhistoryDescHistoryTime.Default.(func() time.Time)
	// agentdefinitionhistoryDescSource is the schema descriptor for source field.
	agentdefinitionhistoryDescSource := agentdefinitionhistoryFields[15].Descriptor()
	// agentdefinitionhistory.DefaultSource holds the default value on creation for the source field.
	agentdefinitionhistory.DefaultSource = agentdefinitionhistoryDescSource.Default.(string)
	// agentdefinitionhistoryDescRevision is the schema descriptor for revision field.
	agentdefinitionhistoryDescRevision := agentdefinitionhistoryFields[17].Descriptor()
	// agentdefinitionhistory.DefaultRevision holds the default value on creation for the revision field.
	agentdefinitionhistory.DefaultRevision = agentdefinitionhistoryDescRevision.Default.(int)
	// agentdefinitionhistoryDescSourceFormat is the schema descriptor for source_format field.
	agentdefinitionhistoryDescSourceFormat := agentdefinitionhistoryFields[18].Descriptor()
	// agentdefinitionhistory.DefaultSourceFormat holds the default value on creation for the source_format field.
	agentdefinitionhistory.DefaultSourceFormat = agentdefinitionhistoryDescSourceFormat.Default.(string)
	// agentdefinitionhistoryDescManagedBy is the schema descriptor for managed_by field.
	agentdefinitionhistoryDescManagedBy := agentdefinitionhistoryFields[21].Descriptor()
	// agentdefinitionhistory.DefaultManagedBy holds the default value on creation for the managed_by field.
	agentdefinitionhistory.DefaultManagedBy = agentdefinitionhistoryDescManagedBy.Default.(string)
	// agentdefinitionhistoryDescAgentSyncState is the schema descriptor for agent_sync_state field.
	agentdefinitionhistoryDescAgentSyncState := agentdefinitionhistoryFields[22].Descriptor()
	// agentdefinitionhistory.DefaultAgentSyncState holds the default value on creation for the agent_sync_state field.
	agentdefinitionhistory.DefaultAgentSyncState = agentdefinitionhistoryDescAgentSyncState.Default.(string)
	// agentdefinitionhistoryDescID is the schema descriptor for id field.
	agentdefinitionhistoryDescID := agentdefinitionhistoryFields[0].Descriptor()
	// agentdefinitionhistory.DefaultID holds the default value on creation for the id field.
	agentdefinitionhistory.DefaultID = agentdefinitionhistoryDescID.Default.(func() uuid.UUID)
	agentsessionMixin := schema.AgentSession{}.Mixin()
	agentsessionMixinFields0 := agentsessionMixin[0].Fields()
	_ = agentsessionMixinFields0
	agentsessionFields := schema.AgentSession{}.Fields()
	_ = agentsessionFields
	// agentsessionDescCreatedAt is the schema descriptor for created_at field.
	agentsessionDescCreatedAt := agentsessionMixinFields0[1].Descriptor()
	// agentsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentsession.DefaultCreatedAt = agentsessionDescCreatedAt.Default.(func() time.Time)
	// agentsessionDescUpdatedAt is the schema descriptor for updated_at field.
	agentsessionDescUpdatedAt := agentsessionMixinFields0[2].Descriptor()
	// agentsession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentsession.DefaultUpdatedAt = agentsessionDescUpdatedAt.Default.(func() time.Time)
	// agentsession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentsession.UpdateDefaultUpdatedAt = agentsessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentsessionDescSessionID is the schema descriptor for session_id field.
	agentsessionDescSessionID := agentsessionFields[0].Descriptor()
	// agentsession.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	agentsession.SessionIDValidator = agentsessionDescSessionID.Validators[0].(func(string) error)
	// agentsessionDescAgentSlug is the schema descriptor for agent_slug field.
	agentsessionDescAgentSlug := agentsessionFields[1].Descriptor()
	// agentsession.AgentSlugValidator is a validator for the "agent_slug" field. It is called by the builders before save.
	agentsession.AgentSlugValidator = agentsessionDescAgentSlug.Validators[0].(func(string) error)
	// agentsessionDescAgentRevision is the schema descriptor for agent_revision field.
	agentsessionDescAgentRevision := agentsessionFields[3].Descriptor()
	// agentsession.DefaultAgentRevision holds the default value on creation for the agent_revision field.
	agentsession.DefaultAgentRevision = agentsessionDescAgentRevision.Default.(int)
	// agentsession.AgentRevisionValidator is a validator for the "agent_revision" field. It is called by the builders before save.
	agentsession.AgentRevisionValidator = agentsessionDescAgentRevision.Validators[0].(func(int) error)
	// agentsessionDescStatus is the schema descriptor for status field.
	agentsessionDescStatus := agentsessionFields[4].Descriptor()
	// agentsession.DefaultStatus holds the default value on creation for the status field.
	agentsession.DefaultStatus = agentsessionDescStatus.Default.(string)
	// agentsession.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	agentsession.StatusValidator = agentsessionDescStatus.Validators[0].(func(string) error)
	// agentsessionDescChannel is the schema descriptor for channel field.
	agentsessionDescChannel := agentsessionFields[5].Descriptor()
	// agentsession.DefaultChannel holds the default value on creation for the channel field.
	agentsession.DefaultChannel = agentsessionDescChannel.Default.(string)
	// agentsessionDescTurnCount is the schema descriptor for turn_count field.
	agentsessionDescTurnCount := agentsessionFields[10].Descriptor()
	// agentsession.DefaultTurnCount holds the default value on creation for the turn_count field.
	agentsession.DefaultTurnCount = agentsessionDescTurnCount.Default.(int)
	// agentsession.TurnCountValidator is a validator for the "turn_count" field. It is called by the builders before save.
	agentsession.TurnCountValidator = agentsessionDescTurnCount.Validators[0].(func(int) error)
	// agentsessionDescLlmCallCount is the schema descriptor for llm_call_count field.
	agentsessionDescLlmCallCount := agentsessionFields[11].Descriptor()
	// agentsession.DefaultLlmCallCount holds the default value on creation for the llm_call_count field.
	agentsession.DefaultLlmCallCount = agentsessionDescLlmCallCount.Default.(int)
	// agentsession.LlmCallCountValidator is a validator for the "llm_call_count" field. It is called by the builders before save.
	agentsession.LlmCallCountValidator = agentsessionDescLlmCallCount.Validators[0].(func(int) error)
	// agentsessionDescToolCallCount is the schema descriptor for tool_call_count field.
	agentsessionDescToolCallCount := agentsessionFields[12].Descriptor()
	// agentsession.DefaultToolCallCount holds the default value on creation for the tool_call_count field.
	agentsession.DefaultToolCallCount = agentsessionDescToolCallCount.Default.(int)
	// agentsession.ToolCallCountValidator is a validator for the "tool_call_count" field. It is called by the builders before save.
	agentsession.ToolCallCountValidator = agentsessionDescToolCallCount.Validators[0].(func(int) error)
	// agentsessionDescCostUnits is the schema descriptor for cost_units field.
	agentsessionDescCostUnits := agentsessionFields[13].Descriptor()
	// agentsession.DefaultCostUnits holds the default value on creation for the cost_units field.
	agentsession.DefaultCostUnits = agentsessionDescCostUnits.Default.(int)
	// agentsession.CostUnitsValidator is a validator for the "cost_units" field. It is called by the builders before save.
	agentsession.CostUnitsValidator = agentsessionDescCostUnits.Validators[0].(func(int) error)
	// agentsessionDescRevision is the schema descriptor for revision field.
	agentsessionDescRevision := agentsessionFields[19].Descriptor()
	// agentsession.DefaultRevision holds the default value on creation for the revision field.
	agentsession.DefaultRevision = agentsessionDescRevision.Default.(int)
	// agentsession.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	agentsession.RevisionValidator = agentsessionDescRevision.Validators[0].(func(int) error)
	// agentsessionDescID is the schema descriptor for id field.
	agentsessionDescID := agentsessionMixinFields0[0].Descriptor()
	// agentsession.DefaultID holds the default value on creation for the id field.
	agentsession.DefaultID = agentsessionDescID.Default.(func() uuid.UUID)
	agentsessioneventMixin := schema.AgentSessionEvent{}.Mixin()
	agentsessioneventMixinFields0 := agentsessioneventMixin[0].Fields()
	_ = agentsessioneventMixinFields0
	agentsessioneventFields := schema.AgentSessionEvent{}.Fields()
	_ = agentsessioneventFields
	// agentsessioneventDescCreatedAt is the schema descriptor for created_at field.
	agentsessioneventDescCreatedAt := agentsessioneventMixinFields0[1].Descriptor()
	// agentsessionevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentsessionevent.DefaultCreatedAt = agentsessioneventDescCreatedAt.Default.(func() time.Time)
	// agentsessioneventDescUpdatedAt is the schema descriptor for updated_at field.
	agentsessioneventDescUpdatedAt := agentsessioneventMixinFields0[2].Descriptor()
	// agentsessionevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentsessionevent.DefaultUpdatedAt = agentsessioneventDescUpdatedAt.Default.(func() time.Time)
	// agentsessionevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentsessionevent.UpdateDefaultUpdatedAt = agentsessioneventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentsessioneventDescSeq is the schema descriptor for seq field.
	agentsessioneventDescSeq := agentsessioneventFields[0].Descriptor()
	// agentsessionevent.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	agentsessionevent.SeqValidator = agentsessioneventDescSeq.Validators[0].(func(int) error)
	// agentsessioneventDescEventJSON is the schema descriptor for event_json field.
	agentsessioneventDescEventJSON := agentsessioneventFields[3].Descriptor()
	// agentsessionevent.EventJSONValidator is a validator for the "event_json" field. It is called by the builders before save.
	agentsessionevent.EventJSONValidator = func() func(string) error {
		validators := agentsessioneventDescEventJSON.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_json string) error {
			for _, fn := range fns {
				if err := fn(event_json); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// agentsessioneventDescReceivedAt is the schema descriptor for received_at field.
	agentsessioneventDescReceivedAt := agentsessioneventFields[4].Descriptor()
	// agentsessionevent.DefaultReceivedAt holds the default value on creation for the received_at field.
	agentsessionevent.DefaultReceivedAt = agentsessioneventDescReceivedAt.Default.(func() time.Time)
	// agentsessioneventDescID is the schema descriptor for id field.
	agentsessioneventDescID := agentsessioneventMixinFields0[0].Descriptor()
	// agentsessionevent.DefaultID holds the default value on creation for the id field.
	agentsessionevent.DefaultID = agentsessioneventDescID.Default.(func() uuid.UUID)
	agenttoolcallMixin := schema.AgentToolCall{}.Mixin()
	agenttoolcallMixinFields0 := agenttoolcallMixin[0].Fields()
	_ = agenttoolcallMixinFields0
	agenttoolcallFields := schema.AgentToolCall{}.Fields()
	_ = agenttoolcallFields
	// agenttoolcallDescCreatedAt is the schema descriptor for created_at field.
	agenttoolcallDescCreatedAt := agenttoolcallMixinFields0[1].Descriptor()
	// agenttoolcall.DefaultCreatedAt holds the default value on creation for the created_at field.
	agenttoolcall.DefaultCreatedAt = agenttoolcallDescCreatedAt.Default.(func() time.Time)
	// agenttoolcallDescUpdatedAt is the schema descriptor for updated_at field.
	agenttoolcallDescUpdatedAt := agenttoolcallMixinFields0[2].Descriptor()
	// agenttoolcall.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agenttoolcall.DefaultUpdatedAt = agenttoolcallDescUpdatedAt.Default.(func() time.Time)
	// agenttoolcall.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agenttoolcall.UpdateDefaultUpdatedAt = agenttoolcallDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agenttoolcallDescCallIndex is the schema descriptor for call_index field.
	agenttoolcallDescCallIndex := agenttoolcallFields[0].Descriptor()
	// agenttoolcall.CallIndexValidator is a validator for the "call_index" field. It is called by the builders before save.
	agenttoolcall.CallIndexValidator = agenttoolcallDescCallIndex.Validators[0].(func(int) error)
	// agenttoolcallDescToolName is the schema descriptor for tool_name field.
	agenttoolcallDescToolName := agenttoolcallFields[1].Descriptor()
	// agenttoolcall.ToolNameValidator is a validator for the "tool_name" field. It is called by the builders before save.
	agenttoolcall.ToolNameValidator = agenttoolcallDescToolName.Validators[0].(func(string) error)
	// agenttoolcallDescArgsJSON is the schema descriptor for args_json field.
	agenttoolcallDescArgsJSON := agenttoolcallFields[2].Descriptor()
	// agenttoolcall.ArgsJSONValidator is a validator for the "args_json" field. It is called by the builders before save.
	agenttoolcall.ArgsJSONValidator = agenttoolcallDescArgsJSON.Validators[0].(func(string) error)
	// agenttoolcallDescResultBytes is the schema descriptor for result_bytes field.
	agenttoolcallDescResultBytes := agenttoolcallFields[3].Descriptor()
	// agenttoolcall.DefaultResultBytes holds the default value on creation for the result_bytes field.
	agenttoolcall.DefaultResultBytes = agenttoolcallDescResultBytes.Default.(int)
	// agenttoolcall.ResultBytesValidator is a validator for the "result_bytes" field. It is called by the builders before save.
	agenttoolcall.ResultBytesValidator = agenttoolcallDescResultBytes.Validators[0].(func(int) error)
	// agenttoolcallDescStatus is the schema descriptor for status field.
	agenttoolcallDescStatus := agenttoolcallFields[4].Descriptor()
	// agenttoolcall.DefaultStatus holds the default value on creation for the status field.
	agenttoolcall.DefaultStatus = agenttoolcallDescStatus.Default.(string)
	// agenttoolcall.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	agenttoolcall.StatusValidator = agenttoolcallDescStatus.Validators[0].(func(string) error)
	// agenttoolcallDescID is the schema descriptor for id field.
	agenttoolcallDescID := agenttoolcallMixinFields0[0].Descriptor()
	// agenttoolcall.DefaultID holds the default value on creation for the id field.
	agenttoolcall.DefaultID = agenttoolcallDescID.Default.(func() uuid.UUID)
	agenttoolresultblobMixin := schema.AgentToolResultBlob{}.Mixin()
	agenttoolresultblobMixinFields0 := agenttoolresultblobMixin[0].Fields()
	_ = agenttoolresultblobMixinFields0
	agenttoolresultblobFields := schema.AgentToolResultBlob{}.Fields()
	_ = agenttoolresultblobFields
	// agenttoolresultblobDescCreatedAt is the schema descriptor for created_at field.
	agenttoolresultblobDescCreatedAt := agenttoolresultblobMixinFields0[1].Descriptor()
	// agenttoolresultblob.DefaultCreatedAt holds the default value on creation for the created_at field.
	agenttoolresultblob.DefaultCreatedAt = agenttoolresultblobDescCreatedAt.Default.(func() time.Time)
	// agenttoolresultblobDescUpdatedAt is the schema descriptor for updated_at field.
	agenttoolresultblobDescUpdatedAt := agenttoolresultblobMixinFields0[2].Descriptor()
	// agenttoolresultblob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agenttoolresultblob.DefaultUpdatedAt = agenttoolresultblobDescUpdatedAt.Default.(func() time.Time)
	// agenttoolresultblob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agenttoolresultblob.UpdateDefaultUpdatedAt = agenttoolresultblobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agenttoolresultblobDescSessionID is the schema descriptor for session_id field.
	agenttoolresultblobDescSessionID := agenttoolresultblobFields[0].Descriptor()
	// agenttoolresultblob.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	agenttoolresultblob.SessionIDValidator = agenttoolresultblobDescSessionID.Validators[0].(func(string) error)
	// agenttoolresultblobDescTurnSeq is the schema descriptor for turn_seq field.
	agenttoolresultblobDescTurnSeq := agenttoolresultblobFields[1].Descriptor()
	// agenttoolresultblob.TurnSeqValidator is a validator for the "turn_seq" field. It is called by the builders before save.
	agenttoolresultblob.TurnSeqValidator = agenttoolresultblobDescTurnSeq.Validators[0].(func(int) error)
	// agenttoolresultblobDescCallIndex is the schema descriptor for call_index field.
	agenttoolresultblobDescCallIndex := agenttoolresultblobFields[2].Descriptor()
	// agenttoolresultblob.CallIndexValidator is a validator for the "call_index" field. It is called by the builders before save.
	agenttoolresultblob.CallIndexValidator = agenttoolresultblobDescCallIndex.Validators[0].(func(int) error)
	// agenttoolresultblobDescContent is the schema descriptor for content field.
	agenttoolresultblobDescContent := agenttoolresultblobFields[4].Descriptor()
	// agenttoolresultblob.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	agenttoolresultblob.ContentValidator = agenttoolresultblobDescContent.Validators[0].(func(string) error)
	// agenttoolresultblobDescTotalBytes is the schema descriptor for total_bytes field.
	agenttoolresultblobDescTotalBytes := agenttoolresultblobFields[5].Descriptor()
	// agenttoolresultblob.TotalBytesValidator is a validator for the "total_bytes" field. It is called by the builders before save.
	agenttoolresultblob.TotalBytesValidator = agenttoolresultblobDescTotalBytes.Validators[0].(func(int) error)
	// agenttoolresultblobDescID is the schema descriptor for id field.
	agenttoolresultblobDescID := agenttoolresultblobMixinFields0[0].Descriptor()
	// agenttoolresultblob.DefaultID holds the default value on creation for the id field.
	agenttoolresultblob.DefaultID = agenttoolresultblobDescID.Default.(func() uuid.UUID)
	agentturnMixin := schema.AgentTurn{}.Mixin()
	agentturnMixinFields0 := agentturnMixin[0].Fields()
	_ = agentturnMixinFields0
	agentturnFields := schema.AgentTurn{}.Fields()
	_ = agentturnFields
	// agentturnDescCreatedAt is the schema descriptor for created_at field.
	agentturnDescCreatedAt := agentturnMixinFields0[1].Descriptor()
	// agentturn.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentturn.DefaultCreatedAt = agentturnDescCreatedAt.Default.(func() time.Time)
	// agentturnDescUpdatedAt is the schema descriptor for updated_at field.
	agentturnDescUpdatedAt := agentturnMixinFields0[2].Descriptor()
	// agentturn.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentturn.DefaultUpdatedAt = agentturnDescUpdatedAt.Default.(func() time.Time)
	// agentturn.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentturn.UpdateDefaultUpdatedAt = agentturnDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentturnDescSeq is the schema descriptor for seq field.
	agentturnDescSeq := agentturnFields[0].Descriptor()
	// agentturn.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	agentturn.SeqValidator = agentturnDescSeq.Validators[0].(func(int) error)
	// agentturnDescStatus is the schema descriptor for status field.
	agentturnDescStatus := agentturnFields[2].Descriptor()
	// agentturn.DefaultStatus holds the default value on creation for the status field.
	agentturn.DefaultStatus = agentturnDescStatus.Default.(string)
	// agentturn.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	agentturn.StatusValidator = agentturnDescStatus.Validators[0].(func(string) error)
	// agentturnDescLlmCallCount is the schema descriptor for llm_call_count field.
	agentturnDescLlmCallCount := agentturnFields[5].Descriptor()
	// agentturn.DefaultLlmCallCount holds the default value on creation for the llm_call_count field.
	agentturn.DefaultLlmCallCount = agentturnDescLlmCallCount.Default.(int)
	// agentturn.LlmCallCountValidator is a validator for the "llm_call_count" field. It is called by the builders before save.
	agentturn.LlmCallCountValidator = agentturnDescLlmCallCount.Validators[0].(func(int) error)
	// agentturnDescToolCallCount is the schema descriptor for tool_call_count field.
	agentturnDescToolCallCount := agentturnFields[6].Descriptor()
	// agentturn.DefaultToolCallCount holds the default value on creation for the tool_call_count field.
	agentturn.DefaultToolCallCount = agentturnDescToolCallCount.Default.(int)
	// agentturn.ToolCallCountValidator is a validator for the "tool_call_count" field. It is called by the builders before save.
	agentturn.ToolCallCountValidator = agentturnDescToolCallCount.Validators[0].(func(int) error)
	// agentturnDescCostUnits is the schema descriptor for cost_units field.
	agentturnDescCostUnits := agentturnFields[7].Descriptor()
	// agentturn.DefaultCostUnits holds the default value on creation for the cost_units field.
	agentturn.DefaultCostUnits = agentturnDescCostUnits.Default.(int)
	// agentturn.CostUnitsValidator is a validator for the "cost_units" field. It is called by the builders before save.
	agentturn.CostUnitsValidator = agentturnDescCostUnits.Validators[0].(func(int) error)
	// agentturnDescID is the schema descriptor for id field.
	agentturnDescID := agentturnMixinFields0[0].Descriptor()
	// agentturn.DefaultID holds the default value on creation for the id field.
	agentturn.DefaultID = agentturnDescID.Default.(func() uuid.UUID)
	backgroundtaskMixin := schema.BackgroundTask{}.Mixin()
	backgroundtaskMixinFields0 := backgroundtaskMixin[0].Fields()
	_ = backgroundtaskMixinFields0
	backgroundtaskFields := schema.BackgroundTask{}.Fields()
	_ = backgroundtaskFields
	// backgroundtaskDescCreatedAt is the schema descriptor for created_at field.
	backgroundtaskDescCreatedAt := backgroundtaskMixinFields0[1].Descriptor()
	// backgroundtask.DefaultCreatedAt holds the default value on creation for the created_at field.
	backgroundtask.DefaultCreatedAt = backgroundtaskDescCreatedAt.Default.(func() time.Time)
	// backgroundtaskDescUpdatedAt is the schema descriptor for updated_at field.
	backgroundtaskDescUpdatedAt := backgroundtaskMixinFields0[2].Descriptor()
	// backgroundtask.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backgroundtask.DefaultUpdatedAt = backgroundtaskDescUpdatedAt.Default.(func() time.Time)
	// backgroundtask.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backgroundtask.UpdateDefaultUpdatedAt = backgroundtaskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// backgroundtaskDescSlug is the schema descriptor for slug field.
	backgroundtaskDescSlug := backgroundtaskFields[0].Descriptor()
	// backgroundtask.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	backgroundtask.SlugValidator = backgroundtaskDescSlug.Validators[0].(func(string) error)
	// backgroundtaskDescName is the schema descriptor for name field.
	backgroundtaskDescName := backgroundtaskFields[1].Descriptor()
	// backgroundtask.NameValidator is a validator for the "name" field. It is called by the builders before save.
	backgroundtask.NameValidator = backgroundtaskDescName.Validators[0].(func(string) error)
	// backgroundtaskDescInstructions is the schema descriptor for instructions field.
	backgroundtaskDescInstructions := backgroundtaskFields[2].Descriptor()
	// backgroundtask.InstructionsValidator is a validator for the "instructions" field. It is called by the builders before save.
	backgroundtask.InstructionsValidator = backgroundtaskDescInstructions.Validators[0].(func(string) error)
	// backgroundtaskDescActive is the schema descriptor for active field.
	backgroundtaskDescActive := backgroundtaskFields[3].Descriptor()
	// backgroundtask.DefaultActive holds the default value on creation for the active field.
	backgroundtask.DefaultActive = backgroundtaskDescActive.Default.(bool)
	// backgroundtaskDescTriggersJSON is the schema descriptor for triggers_json field.
	backgroundtaskDescTriggersJSON := backgroundtaskFields[4].Descriptor()
	// backgroundtask.TriggersJSONValidator is a validator for the "triggers_json" field. It is called by the builders before save.
	backgroundtask.TriggersJSONValidator = backgroundtaskDescTriggersJSON.Validators[0].(func(string) error)
	// backgroundtaskDescExecutionTarget is the schema descriptor for execution_target field.
	backgroundtaskDescExecutionTarget := backgroundtaskFields[7].Descriptor()
	// backgroundtask.DefaultExecutionTarget holds the default value on creation for the execution_target field.
	backgroundtask.DefaultExecutionTarget = backgroundtaskDescExecutionTarget.Default.(string)
	// backgroundtask.ExecutionTargetValidator is a validator for the "execution_target" field. It is called by the builders before save.
	backgroundtask.ExecutionTargetValidator = backgroundtaskDescExecutionTarget.Validators[0].(func(string) error)
	// backgroundtaskDescScheduleSyncState is the schema descriptor for schedule_sync_state field.
	backgroundtaskDescScheduleSyncState := backgroundtaskFields[14].Descriptor()
	// backgroundtask.DefaultScheduleSyncState holds the default value on creation for the schedule_sync_state field.
	backgroundtask.DefaultScheduleSyncState = backgroundtaskDescScheduleSyncState.Default.(string)
	// backgroundtask.ScheduleSyncStateValidator is a validator for the "schedule_sync_state" field. It is called by the builders before save.
	backgroundtask.ScheduleSyncStateValidator = backgroundtaskDescScheduleSyncState.Validators[0].(func(string) error)
	// backgroundtaskDescRevision is the schema descriptor for revision field.
	backgroundtaskDescRevision := backgroundtaskFields[17].Descriptor()
	// backgroundtask.DefaultRevision holds the default value on creation for the revision field.
	backgroundtask.DefaultRevision = backgroundtaskDescRevision.Default.(int)
	// backgroundtask.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	backgroundtask.RevisionValidator = backgroundtaskDescRevision.Validators[0].(func(int) error)
	// backgroundtaskDescID is the schema descriptor for id field.
	backgroundtaskDescID := backgroundtaskMixinFields0[0].Descriptor()
	// backgroundtask.DefaultID holds the default value on creation for the id field.
	backgroundtask.DefaultID = backgroundtaskDescID.Default.(func() uuid.UUID)
	backgroundtaskartifactMixin := schema.BackgroundTaskArtifact{}.Mixin()
	backgroundtaskartifactMixinFields0 := backgroundtaskartifactMixin[0].Fields()
	_ = backgroundtaskartifactMixinFields0
	backgroundtaskartifactFields := schema.BackgroundTaskArtifact{}.Fields()
	_ = backgroundtaskartifactFields
	// backgroundtaskartifactDescCreatedAt is the schema descriptor for created_at field.
	backgroundtaskartifactDescCreatedAt := backgroundtaskartifactMixinFields0[1].Descriptor()
	// backgroundtaskartifact.DefaultCreatedAt holds the default value on creation for the created_at field.
	backgroundtaskartifact.DefaultCreatedAt = backgroundtaskartifactDescCreatedAt.Default.(func() time.Time)
	// backgroundtaskartifactDescUpdatedAt is the schema descriptor for updated_at field.
	backgroundtaskartifactDescUpdatedAt := backgroundtaskartifactMixinFields0[2].Descriptor()
	// backgroundtaskartifact.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backgroundtaskartifact.DefaultUpdatedAt = backgroundtaskartifactDescUpdatedAt.Default.(func() time.Time)
	// backgroundtaskartifact.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backgroundtaskartifact.UpdateDefaultUpdatedAt = backgroundtaskartifactDescUpdatedAt.UpdateDefault.(func() time.Time)
	// backgroundtaskartifactDescBody is the schema descriptor for body field.
	backgroundtaskartifactDescBody := backgroundtaskartifactFields[0].Descriptor()
	// backgroundtaskartifact.DefaultBody holds the default value on creation for the body field.
	backgroundtaskartifact.DefaultBody = backgroundtaskartifactDescBody.Default.(string)
	// backgroundtaskartifactDescRevision is the schema descriptor for revision field.
	backgroundtaskartifactDescRevision := backgroundtaskartifactFields[1].Descriptor()
	// backgroundtaskartifact.DefaultRevision holds the default value on creation for the revision field.
	backgroundtaskartifact.DefaultRevision = backgroundtaskartifactDescRevision.Default.(int)
	// backgroundtaskartifact.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	backgroundtaskartifact.RevisionValidator = backgroundtaskartifactDescRevision.Validators[0].(func(int) error)
	// backgroundtaskartifactDescContentType is the schema descriptor for content_type field.
	backgroundtaskartifactDescContentType := backgroundtaskartifactFields[3].Descriptor()
	// backgroundtaskartifact.DefaultContentType holds the default value on creation for the content_type field.
	backgroundtaskartifact.DefaultContentType = backgroundtaskartifactDescContentType.Default.(string)
	// backgroundtaskartifactDescID is the schema descriptor for id field.
	backgroundtaskartifactDescID := backgroundtaskartifactMixinFields0[0].Descriptor()
	// backgroundtaskartifact.DefaultID holds the default value on creation for the id field.
	backgroundtaskartifact.DefaultID = backgroundtaskartifactDescID.Default.(func() uuid.UUID)
	backgroundtaskrunMixin := schema.BackgroundTaskRun{}.Mixin()
	backgroundtaskrunMixinFields0 := backgroundtaskrunMixin[0].Fields()
	_ = backgroundtaskrunMixinFields0
	backgroundtaskrunFields := schema.BackgroundTaskRun{}.Fields()
	_ = backgroundtaskrunFields
	// backgroundtaskrunDescCreatedAt is the schema descriptor for created_at field.
	backgroundtaskrunDescCreatedAt := backgroundtaskrunMixinFields0[1].Descriptor()
	// backgroundtaskrun.DefaultCreatedAt holds the default value on creation for the created_at field.
	backgroundtaskrun.DefaultCreatedAt = backgroundtaskrunDescCreatedAt.Default.(func() time.Time)
	// backgroundtaskrunDescUpdatedAt is the schema descriptor for updated_at field.
	backgroundtaskrunDescUpdatedAt := backgroundtaskrunMixinFields0[2].Descriptor()
	// backgroundtaskrun.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backgroundtaskrun.DefaultUpdatedAt = backgroundtaskrunDescUpdatedAt.Default.(func() time.Time)
	// backgroundtaskrun.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backgroundtaskrun.UpdateDefaultUpdatedAt = backgroundtaskrunDescUpdatedAt.UpdateDefault.(func() time.Time)
	// backgroundtaskrunDescRunID is the schema descriptor for run_id field.
	backgroundtaskrunDescRunID := backgroundtaskrunFields[0].Descriptor()
	// backgroundtaskrun.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	backgroundtaskrun.RunIDValidator = backgroundtaskrunDescRunID.Validators[0].(func(string) error)
	// backgroundtaskrunDescTrigger is the schema descriptor for trigger field.
	backgroundtaskrunDescTrigger := backgroundtaskrunFields[1].Descriptor()
	// backgroundtaskrun.DefaultTrigger holds the default value on creation for the trigger field.
	backgroundtaskrun.DefaultTrigger = backgroundtaskrunDescTrigger.Default.(string)
	// backgroundtaskrun.TriggerValidator is a validator for the "trigger" field. It is called by the builders before save.
	backgroundtaskrun.TriggerValidator = backgroundtaskrunDescTrigger.Validators[0].(func(string) error)
	// backgroundtaskrunDescStatus is the schema descriptor for status field.
	backgroundtaskrunDescStatus := backgroundtaskrunFields[2].Descriptor()
	// backgroundtaskrun.DefaultStatus holds the default value on creation for the status field.
	backgroundtaskrun.DefaultStatus = backgroundtaskrunDescStatus.Default.(string)
	// backgroundtaskrun.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	backgroundtaskrun.StatusValidator = backgroundtaskrunDescStatus.Validators[0].(func(string) error)
	// backgroundtaskrunDescExecutor is the schema descriptor for executor field.
	backgroundtaskrunDescExecutor := backgroundtaskrunFields[3].Descriptor()
	// backgroundtaskrun.DefaultExecutor holds the default value on creation for the executor field.
	backgroundtaskrun.DefaultExecutor = backgroundtaskrunDescExecutor.Default.(string)
	// backgroundtaskrun.ExecutorValidator is a validator for the "executor" field. It is called by the builders before save.
	backgroundtaskrun.ExecutorValidator = backgroundtaskrunDescExecutor.Validators[0].(func(string) error)
	// backgroundtaskrunDescAttempt is the schema descriptor for attempt field.
	backgroundtaskrunDescAttempt := backgroundtaskrunFields[4].Descriptor()
	// backgroundtaskrun.DefaultAttempt holds the default value on creation for the attempt field.
	backgroundtaskrun.DefaultAttempt = backgroundtaskrunDescAttempt.Default.(int)
	// backgroundtaskrun.AttemptValidator is a validator for the "attempt" field. It is called by the builders before save.
	backgroundtaskrun.AttemptValidator = backgroundtaskrunDescAttempt.Validators[0].(func(int) error)
	// backgroundtaskrunDescProgressPercent is the schema descriptor for progress_percent field.
	backgroundtaskrunDescProgressPercent := backgroundtaskrunFields[23].Descriptor()
	// backgroundtaskrun.ProgressPercentValidator is a validator for the "progress_percent" field. It is called by the builders before save.
	backgroundtaskrun.ProgressPercentValidator = func() func(int) error {
		validators := backgroundtaskrunDescProgressPercent.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(progress_percent int) error {
			for _, fn := range fns {
				if err := fn(progress_percent); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// backgroundtaskrunDescRevision is the schema descriptor for revision field.
	backgroundtaskrunDescRevision := backgroundtaskrunFields[29].Descriptor()
	// backgroundtaskrun.DefaultRevision holds the default value on creation for the revision field.
	backgroundtaskrun.DefaultRevision = backgroundtaskrunDescRevision.Default.(int)
	// backgroundtaskrun.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	backgroundtaskrun.RevisionValidator = backgroundtaskrunDescRevision.Validators[0].(func(int) error)
	// backgroundtaskrunDescID is the schema descriptor for id field.
	backgroundtaskrunDescID := backgroundtaskrunMixinFields0[0].Descriptor()
	// backgroundtaskrun.DefaultID holds the default value on creation for the id field.
	backgroundtaskrun.DefaultID = backgroundtaskrunDescID.Default.(func() uuid.UUID)
	backgroundtaskruneventMixin := schema.BackgroundTaskRunEvent{}.Mixin()
	backgroundtaskruneventMixinFields0 := backgroundtaskruneventMixin[0].Fields()
	_ = backgroundtaskruneventMixinFields0
	backgroundtaskruneventFields := schema.BackgroundTaskRunEvent{}.Fields()
	_ = backgroundtaskruneventFields
	// backgroundtaskruneventDescCreatedAt is the schema descriptor for created_at field.
	backgroundtaskruneventDescCreatedAt := backgroundtaskruneventMixinFields0[1].Descriptor()
	// backgroundtaskrunevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	backgroundtaskrunevent.DefaultCreatedAt = backgroundtaskruneventDescCreatedAt.Default.(func() time.Time)
	// backgroundtaskruneventDescUpdatedAt is the schema descriptor for updated_at field.
	backgroundtaskruneventDescUpdatedAt := backgroundtaskruneventMixinFields0[2].Descriptor()
	// backgroundtaskrunevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backgroundtaskrunevent.DefaultUpdatedAt = backgroundtaskruneventDescUpdatedAt.Default.(func() time.Time)
	// backgroundtaskrunevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backgroundtaskrunevent.UpdateDefaultUpdatedAt = backgroundtaskruneventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// backgroundtaskruneventDescSeq is the schema descriptor for seq field.
	backgroundtaskruneventDescSeq := backgroundtaskruneventFields[0].Descriptor()
	// backgroundtaskrunevent.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	backgroundtaskrunevent.SeqValidator = backgroundtaskruneventDescSeq.Validators[0].(func(int) error)
	// backgroundtaskruneventDescEventJSON is the schema descriptor for event_json field.
	backgroundtaskruneventDescEventJSON := backgroundtaskruneventFields[2].Descriptor()
	// backgroundtaskrunevent.EventJSONValidator is a validator for the "event_json" field. It is called by the builders before save.
	backgroundtaskrunevent.EventJSONValidator = func() func(string) error {
		validators := backgroundtaskruneventDescEventJSON.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_json string) error {
			for _, fn := range fns {
				if err := fn(event_json); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// backgroundtaskruneventDescReceivedAt is the schema descriptor for received_at field.
	backgroundtaskruneventDescReceivedAt := backgroundtaskruneventFields[3].Descriptor()
	// backgroundtaskrunevent.DefaultReceivedAt holds the default value on creation for the received_at field.
	backgroundtaskrunevent.DefaultReceivedAt = backgroundtaskruneventDescReceivedAt.Default.(func() time.Time)
	// backgroundtaskruneventDescID is the schema descriptor for id field.
	backgroundtaskruneventDescID := backgroundtaskruneventMixinFields0[0].Descriptor()
	// backgroundtaskrunevent.DefaultID holds the default value on creation for the id field.
	backgroundtaskrunevent.DefaultID = backgroundtaskruneventDescID.Default.(func() uuid.UUID)
	backgroundtaskschedulestateMixin := schema.BackgroundTaskScheduleState{}.Mixin()
	backgroundtaskschedulestateMixinFields0 := backgroundtaskschedulestateMixin[0].Fields()
	_ = backgroundtaskschedulestateMixinFields0
	backgroundtaskschedulestateFields := schema.BackgroundTaskScheduleState{}.Fields()
	_ = backgroundtaskschedulestateFields
	// backgroundtaskschedulestateDescCreatedAt is the schema descriptor for created_at field.
	backgroundtaskschedulestateDescCreatedAt := backgroundtaskschedulestateMixinFields0[1].Descriptor()
	// backgroundtaskschedulestate.DefaultCreatedAt holds the default value on creation for the created_at field.
	backgroundtaskschedulestate.DefaultCreatedAt = backgroundtaskschedulestateDescCreatedAt.Default.(func() time.Time)
	// backgroundtaskschedulestateDescUpdatedAt is the schema descriptor for updated_at field.
	backgroundtaskschedulestateDescUpdatedAt := backgroundtaskschedulestateMixinFields0[2].Descriptor()
	// backgroundtaskschedulestate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backgroundtaskschedulestate.DefaultUpdatedAt = backgroundtaskschedulestateDescUpdatedAt.Default.(func() time.Time)
	// backgroundtaskschedulestate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backgroundtaskschedulestate.UpdateDefaultUpdatedAt = backgroundtaskschedulestateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// backgroundtaskschedulestateDescTriggerType is the schema descriptor for trigger_type field.
	backgroundtaskschedulestateDescTriggerType := backgroundtaskschedulestateFields[0].Descriptor()
	// backgroundtaskschedulestate.TriggerTypeValidator is a validator for the "trigger_type" field. It is called by the builders before save.
	backgroundtaskschedulestate.TriggerTypeValidator = backgroundtaskschedulestateDescTriggerType.Validators[0].(func(string) error)
	// backgroundtaskschedulestateDescScheduleKey is the schema descriptor for schedule_key field.
	backgroundtaskschedulestateDescScheduleKey := backgroundtaskschedulestateFields[1].Descriptor()
	// backgroundtaskschedulestate.ScheduleKeyValidator is a validator for the "schedule_key" field. It is called by the builders before save.
	backgroundtaskschedulestate.ScheduleKeyValidator = backgroundtaskschedulestateDescScheduleKey.Validators[0].(func(string) error)
	// backgroundtaskschedulestateDescLastRunID is the schema descriptor for last_run_id field.
	backgroundtaskschedulestateDescLastRunID := backgroundtaskschedulestateFields[5].Descriptor()
	// backgroundtaskschedulestate.DefaultLastRunID holds the default value on creation for the last_run_id field.
	backgroundtaskschedulestate.DefaultLastRunID = backgroundtaskschedulestateDescLastRunID.Default.(string)
	// backgroundtaskschedulestateDescLeaseOwner is the schema descriptor for lease_owner field.
	backgroundtaskschedulestateDescLeaseOwner := backgroundtaskschedulestateFields[6].Descriptor()
	// backgroundtaskschedulestate.DefaultLeaseOwner holds the default value on creation for the lease_owner field.
	backgroundtaskschedulestate.DefaultLeaseOwner = backgroundtaskschedulestateDescLeaseOwner.Default.(string)
	// backgroundtaskschedulestateDescRevision is the schema descriptor for revision field.
	backgroundtaskschedulestateDescRevision := backgroundtaskschedulestateFields[8].Descriptor()
	// backgroundtaskschedulestate.DefaultRevision holds the default value on creation for the revision field.
	backgroundtaskschedulestate.DefaultRevision = backgroundtaskschedulestateDescRevision.Default.(int)
	// backgroundtaskschedulestate.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	backgroundtaskschedulestate.RevisionValidator = backgroundtaskschedulestateDescRevision.Validators[0].(func(int) error)
	// backgroundtaskschedulestateDescID is the schema descriptor for id field.
	backgroundtaskschedulestateDescID := backgroundtaskschedulestateMixinFields0[0].Descriptor()
	// backgroundtaskschedulestate.DefaultID holds the default value on creation for the id field.
	backgroundtaskschedulestate.DefaultID = backgroundtaskschedulestateDescID.Default.(func() uuid.UUID)
	cloudeventMixin := schema.CloudEvent{}.Mixin()
	cloudeventMixinFields0 := cloudeventMixin[0].Fields()
	_ = cloudeventMixinFields0
	cloudeventFields := schema.CloudEvent{}.Fields()
	_ = cloudeventFields
	// cloudeventDescCreatedAt is the schema descriptor for created_at field.
	cloudeventDescCreatedAt := cloudeventMixinFields0[1].Descriptor()
	// cloudevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	cloudevent.DefaultCreatedAt = cloudeventDescCreatedAt.Default.(func() time.Time)
	// cloudeventDescUpdatedAt is the schema descriptor for updated_at field.
	cloudeventDescUpdatedAt := cloudeventMixinFields0[2].Descriptor()
	// cloudevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cloudevent.DefaultUpdatedAt = cloudeventDescUpdatedAt.Default.(func() time.Time)
	// cloudevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cloudevent.UpdateDefaultUpdatedAt = cloudeventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cloudeventDescSource is the schema descriptor for source field.
	cloudeventDescSource := cloudeventFields[0].Descriptor()
	// cloudevent.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	cloudevent.SourceValidator = cloudeventDescSource.Validators[0].(func(string) error)
	// cloudeventDescRoutingJSON is the schema descriptor for routing_json field.
	cloudeventDescRoutingJSON := cloudeventFields[7].Descriptor()
	// cloudevent.RoutingJSONValidator is a validator for the "routing_json" field. It is called by the builders before save.
	cloudevent.RoutingJSONValidator = cloudeventDescRoutingJSON.Validators[0].(func(string) error)
	// cloudeventDescDedupeKey is the schema descriptor for dedupe_key field.
	cloudeventDescDedupeKey := cloudeventFields[8].Descriptor()
	// cloudevent.DedupeKeyValidator is a validator for the "dedupe_key" field. It is called by the builders before save.
	cloudevent.DedupeKeyValidator = cloudeventDescDedupeKey.Validators[0].(func(string) error)
	// cloudeventDescRoutingStatus is the schema descriptor for routing_status field.
	cloudeventDescRoutingStatus := cloudeventFields[9].Descriptor()
	// cloudevent.DefaultRoutingStatus holds the default value on creation for the routing_status field.
	cloudevent.DefaultRoutingStatus = cloudeventDescRoutingStatus.Default.(string)
	// cloudevent.RoutingStatusValidator is a validator for the "routing_status" field. It is called by the builders before save.
	cloudevent.RoutingStatusValidator = cloudeventDescRoutingStatus.Validators[0].(func(string) error)
	// cloudeventDescMatchedTaskCount is the schema descriptor for matched_task_count field.
	cloudeventDescMatchedTaskCount := cloudeventFields[10].Descriptor()
	// cloudevent.DefaultMatchedTaskCount holds the default value on creation for the matched_task_count field.
	cloudevent.DefaultMatchedTaskCount = cloudeventDescMatchedTaskCount.Default.(int)
	// cloudeventDescReceivedAt is the schema descriptor for received_at field.
	cloudeventDescReceivedAt := cloudeventFields[12].Descriptor()
	// cloudevent.DefaultReceivedAt holds the default value on creation for the received_at field.
	cloudevent.DefaultReceivedAt = cloudeventDescReceivedAt.Default.(func() time.Time)
	// cloudeventDescID is the schema descriptor for id field.
	cloudeventDescID := cloudeventMixinFields0[0].Descriptor()
	// cloudevent.DefaultID holds the default value on creation for the id field.
	cloudevent.DefaultID = cloudeventDescID.Default.(func() uuid.UUID)
	creditledgerFields := schema.CreditLedger{}.Fields()
	_ = creditledgerFields
	// creditledgerDescTs is the schema descriptor for ts field.
	creditledgerDescTs := creditledgerFields[4].Descriptor()
	// creditledger.DefaultTs holds the default value on creation for the ts field.
	creditledger.DefaultTs = creditledgerDescTs.Default.(func() time.Time)
	// creditledgerDescID is the schema descriptor for id field.
	creditledgerDescID := creditledgerFields[0].Descriptor()
	// creditledger.DefaultID holds the default value on creation for the id field.
	creditledger.DefaultID = creditledgerDescID.Default.(func() uuid.UUID)
	googlewatchMixin := schema.GoogleWatch{}.Mixin()
	googlewatchMixinFields0 := googlewatchMixin[0].Fields()
	_ = googlewatchMixinFields0
	googlewatchFields := schema.GoogleWatch{}.Fields()
	_ = googlewatchFields
	// googlewatchDescCreatedAt is the schema descriptor for created_at field.
	googlewatchDescCreatedAt := googlewatchMixinFields0[1].Descriptor()
	// googlewatch.DefaultCreatedAt holds the default value on creation for the created_at field.
	googlewatch.DefaultCreatedAt = googlewatchDescCreatedAt.Default.(func() time.Time)
	// googlewatchDescUpdatedAt is the schema descriptor for updated_at field.
	googlewatchDescUpdatedAt := googlewatchMixinFields0[2].Descriptor()
	// googlewatch.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	googlewatch.DefaultUpdatedAt = googlewatchDescUpdatedAt.Default.(func() time.Time)
	// googlewatch.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	googlewatch.UpdateDefaultUpdatedAt = googlewatchDescUpdatedAt.UpdateDefault.(func() time.Time)
	// googlewatchDescKind is the schema descriptor for kind field.
	googlewatchDescKind := googlewatchFields[0].Descriptor()
	// googlewatch.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	googlewatch.KindValidator = googlewatchDescKind.Validators[0].(func(string) error)
	// googlewatchDescAccountEmail is the schema descriptor for account_email field.
	googlewatchDescAccountEmail := googlewatchFields[1].Descriptor()
	// googlewatch.AccountEmailValidator is a validator for the "account_email" field. It is called by the builders before save.
	googlewatch.AccountEmailValidator = googlewatchDescAccountEmail.Validators[0].(func(string) error)
	// googlewatchDescID is the schema descriptor for id field.
	googlewatchDescID := googlewatchMixinFields0[0].Descriptor()
	// googlewatch.DefaultID holds the default value on creation for the id field.
	googlewatch.DefaultID = googlewatchDescID.Default.(func() uuid.UUID)
	llmusageFields := schema.LLMUsage{}.Fields()
	_ = llmusageFields
	// llmusageDescInputTokens is the schema descriptor for input_tokens field.
	llmusageDescInputTokens := llmusageFields[5].Descriptor()
	// llmusage.DefaultInputTokens holds the default value on creation for the input_tokens field.
	llmusage.DefaultInputTokens = llmusageDescInputTokens.Default.(int)
	// llmusage.InputTokensValidator is a validator for the "input_tokens" field. It is called by the builders before save.
	llmusage.InputTokensValidator = llmusageDescInputTokens.Validators[0].(func(int) error)
	// llmusageDescOutputTokens is the schema descriptor for output_tokens field.
	llmusageDescOutputTokens := llmusageFields[6].Descriptor()
	// llmusage.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	llmusage.DefaultOutputTokens = llmusageDescOutputTokens.Default.(int)
	// llmusage.OutputTokensValidator is a validator for the "output_tokens" field. It is called by the builders before save.
	llmusage.OutputTokensValidator = llmusageDescOutputTokens.Validators[0].(func(int) error)
	// llmusageDescCostUnits is the schema descriptor for cost_units field.
	llmusageDescCostUnits := llmusageFields[7].Descriptor()
	// llmusage.DefaultCostUnits holds the default value on creation for the cost_units field.
	llmusage.DefaultCostUnits = llmusageDescCostUnits.Default.(int)
	// llmusage.CostUnitsValidator is a validator for the "cost_units" field. It is called by the builders before save.
	llmusage.CostUnitsValidator = llmusageDescCostUnits.Validators[0].(func(int) error)
	// llmusageDescTs is the schema descriptor for ts field.
	llmusageDescTs := llmusageFields[9].Descriptor()
	// llmusage.DefaultTs holds the default value on creation for the ts field.
	llmusage.DefaultTs = llmusageDescTs.Default.(func() time.Time)
	// llmusageDescID is the schema descriptor for id field.
	llmusageDescID := llmusageFields[0].Descriptor()
	// llmusage.DefaultID holds the default value on creation for the id field.
	llmusage.DefaultID = llmusageDescID.Default.(func() uuid.UUID)
	llmusagehistoryFields := schema.LLMUsageHistory{}.Fields()
	_ = llmusagehistoryFields
	// llmusagehistoryDescHistoryTime is the schema descriptor for history_time field.
	llmusagehistoryDescHistoryTime := llmusagehistoryFields[1].Descriptor()
	// llmusagehistory.DefaultHistoryTime holds the default value on creation for the history_time field.
	llmusagehistory.DefaultHistoryTime = llmusagehistoryDescHistoryTime.Default.(func() time.Time)
	// llmusagehistoryDescInputTokens is the schema descriptor for input_tokens field.
	llmusagehistoryDescInputTokens := llmusagehistoryFields[8].Descriptor()
	// llmusagehistory.DefaultInputTokens holds the default value on creation for the input_tokens field.
	llmusagehistory.DefaultInputTokens = llmusagehistoryDescInputTokens.Default.(int)
	// llmusagehistoryDescOutputTokens is the schema descriptor for output_tokens field.
	llmusagehistoryDescOutputTokens := llmusagehistoryFields[9].Descriptor()
	// llmusagehistory.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	llmusagehistory.DefaultOutputTokens = llmusagehistoryDescOutputTokens.Default.(int)
	// llmusagehistoryDescCostUnits is the schema descriptor for cost_units field.
	llmusagehistoryDescCostUnits := llmusagehistoryFields[10].Descriptor()
	// llmusagehistory.DefaultCostUnits holds the default value on creation for the cost_units field.
	llmusagehistory.DefaultCostUnits = llmusagehistoryDescCostUnits.Default.(int)
	// llmusagehistoryDescTs is the schema descriptor for ts field.
	llmusagehistoryDescTs := llmusagehistoryFields[12].Descriptor()
	// llmusagehistory.DefaultTs holds the default value on creation for the ts field.
	llmusagehistory.DefaultTs = llmusagehistoryDescTs.Default.(func() time.Time)
	// llmusagehistoryDescID is the schema descriptor for id field.
	llmusagehistoryDescID := llmusagehistoryFields[0].Descriptor()
	// llmusagehistory.DefaultID holds the default value on creation for the id field.
	llmusagehistory.DefaultID = llmusagehistoryDescID.Default.(func() uuid.UUID)
	mcpconnectionMixin := schema.MCPConnection{}.Mixin()
	mcpconnectionMixinFields0 := mcpconnectionMixin[0].Fields()
	_ = mcpconnectionMixinFields0
	mcpconnectionFields := schema.MCPConnection{}.Fields()
	_ = mcpconnectionFields
	// mcpconnectionDescCreatedAt is the schema descriptor for created_at field.
	mcpconnectionDescCreatedAt := mcpconnectionMixinFields0[1].Descriptor()
	// mcpconnection.DefaultCreatedAt holds the default value on creation for the created_at field.
	mcpconnection.DefaultCreatedAt = mcpconnectionDescCreatedAt.Default.(func() time.Time)
	// mcpconnectionDescUpdatedAt is the schema descriptor for updated_at field.
	mcpconnectionDescUpdatedAt := mcpconnectionMixinFields0[2].Descriptor()
	// mcpconnection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mcpconnection.DefaultUpdatedAt = mcpconnectionDescUpdatedAt.Default.(func() time.Time)
	// mcpconnection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mcpconnection.UpdateDefaultUpdatedAt = mcpconnectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mcpconnectionDescID is the schema descriptor for id field.
	mcpconnectionDescID := mcpconnectionMixinFields0[0].Descriptor()
	// mcpconnection.DefaultID holds the default value on creation for the id field.
	mcpconnection.DefaultID = mcpconnectionDescID.Default.(func() uuid.UUID)
	mcpconnectionhistoryMixin := schema.MCPConnectionHistory{}.Mixin()
	mcpconnectionhistoryMixinFields0 := mcpconnectionhistoryMixin[0].Fields()
	_ = mcpconnectionhistoryMixinFields0
	mcpconnectionhistoryFields := schema.MCPConnectionHistory{}.Fields()
	_ = mcpconnectionhistoryFields
	// mcpconnectionhistoryDescCreatedAt is the schema descriptor for created_at field.
	mcpconnectionhistoryDescCreatedAt := mcpconnectionhistoryMixinFields0[1].Descriptor()
	// mcpconnectionhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	mcpconnectionhistory.DefaultCreatedAt = mcpconnectionhistoryDescCreatedAt.Default.(func() time.Time)
	// mcpconnectionhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	mcpconnectionhistoryDescUpdatedAt := mcpconnectionhistoryMixinFields0[2].Descriptor()
	// mcpconnectionhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mcpconnectionhistory.DefaultUpdatedAt = mcpconnectionhistoryDescUpdatedAt.Default.(func() time.Time)
	// mcpconnectionhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mcpconnectionhistory.UpdateDefaultUpdatedAt = mcpconnectionhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mcpconnectionhistoryDescHistoryTime is the schema descriptor for history_time field.
	mcpconnectionhistoryDescHistoryTime := mcpconnectionhistoryFields[1].Descriptor()
	// mcpconnectionhistory.DefaultHistoryTime holds the default value on creation for the history_time field.
	mcpconnectionhistory.DefaultHistoryTime = mcpconnectionhistoryDescHistoryTime.Default.(func() time.Time)
	// mcpconnectionhistoryDescID is the schema descriptor for id field.
	mcpconnectionhistoryDescID := mcpconnectionhistoryFields[0].Descriptor()
	// mcpconnectionhistory.DefaultID holds the default value on creation for the id field.
	mcpconnectionhistory.DefaultID = mcpconnectionhistoryDescID.Default.(func() uuid.UUID)
	meetingminuteusageMixin := schema.MeetingMinuteUsage{}.Mixin()
	meetingminuteusageMixinFields0 := meetingminuteusageMixin[0].Fields()
	_ = meetingminuteusageMixinFields0
	meetingminuteusageFields := schema.MeetingMinuteUsage{}.Fields()
	_ = meetingminuteusageFields
	// meetingminuteusageDescCreatedAt is the schema descriptor for created_at field.
	meetingminuteusageDescCreatedAt := meetingminuteusageMixinFields0[1].Descriptor()
	// meetingminuteusage.DefaultCreatedAt holds the default value on creation for the created_at field.
	meetingminuteusage.DefaultCreatedAt = meetingminuteusageDescCreatedAt.Default.(func() time.Time)
	// meetingminuteusageDescUpdatedAt is the schema descriptor for updated_at field.
	meetingminuteusageDescUpdatedAt := meetingminuteusageMixinFields0[2].Descriptor()
	// meetingminuteusage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	meetingminuteusage.DefaultUpdatedAt = meetingminuteusageDescUpdatedAt.Default.(func() time.Time)
	// meetingminuteusage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	meetingminuteusage.UpdateDefaultUpdatedAt = meetingminuteusageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// meetingminuteusageDescUsedSeconds is the schema descriptor for used_seconds field.
	meetingminuteusageDescUsedSeconds := meetingminuteusageFields[1].Descriptor()
	// meetingminuteusage.DefaultUsedSeconds holds the default value on creation for the used_seconds field.
	meetingminuteusage.DefaultUsedSeconds = meetingminuteusageDescUsedSeconds.Default.(int)
	// meetingminuteusage.UsedSecondsValidator is a validator for the "used_seconds" field. It is called by the builders before save.
	meetingminuteusage.UsedSecondsValidator = meetingminuteusageDescUsedSeconds.Validators[0].(func(int) error)
	// meetingminuteusageDescReservedSeconds is the schema descriptor for reserved_seconds field.
	meetingminuteusageDescReservedSeconds := meetingminuteusageFields[2].Descriptor()
	// meetingminuteusage.DefaultReservedSeconds holds the default value on creation for the reserved_seconds field.
	meetingminuteusage.DefaultReservedSeconds = meetingminuteusageDescReservedSeconds.Default.(int)
	// meetingminuteusage.ReservedSecondsValidator is a validator for the "reserved_seconds" field. It is called by the builders before save.
	meetingminuteusage.ReservedSecondsValidator = meetingminuteusageDescReservedSeconds.Validators[0].(func(int) error)
	// meetingminuteusageDescID is the schema descriptor for id field.
	meetingminuteusageDescID := meetingminuteusageMixinFields0[0].Descriptor()
	// meetingminuteusage.DefaultID holds the default value on creation for the id field.
	meetingminuteusage.DefaultID = meetingminuteusageDescID.Default.(func() uuid.UUID)
	oauthconnectionMixin := schema.OAuthConnection{}.Mixin()
	oauthconnectionMixinFields0 := oauthconnectionMixin[0].Fields()
	_ = oauthconnectionMixinFields0
	oauthconnectionFields := schema.OAuthConnection{}.Fields()
	_ = oauthconnectionFields
	// oauthconnectionDescCreatedAt is the schema descriptor for created_at field.
	oauthconnectionDescCreatedAt := oauthconnectionMixinFields0[1].Descriptor()
	// oauthconnection.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthconnection.DefaultCreatedAt = oauthconnectionDescCreatedAt.Default.(func() time.Time)
	// oauthconnectionDescUpdatedAt is the schema descriptor for updated_at field.
	oauthconnectionDescUpdatedAt := oauthconnectionMixinFields0[2].Descriptor()
	// oauthconnection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthconnection.DefaultUpdatedAt = oauthconnectionDescUpdatedAt.Default.(func() time.Time)
	// oauthconnection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthconnection.UpdateDefaultUpdatedAt = oauthconnectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthconnectionDescID is the schema descriptor for id field.
	oauthconnectionDescID := oauthconnectionMixinFields0[0].Descriptor()
	// oauthconnection.DefaultID holds the default value on creation for the id field.
	oauthconnection.DefaultID = oauthconnectionDescID.Default.(func() uuid.UUID)
	oauthconnectionhistoryMixin := schema.OAuthConnectionHistory{}.Mixin()
	oauthconnectionhistoryMixinFields0 := oauthconnectionhistoryMixin[0].Fields()
	_ = oauthconnectionhistoryMixinFields0
	oauthconnectionhistoryFields := schema.OAuthConnectionHistory{}.Fields()
	_ = oauthconnectionhistoryFields
	// oauthconnectionhistoryDescCreatedAt is the schema descriptor for created_at field.
	oauthconnectionhistoryDescCreatedAt := oauthconnectionhistoryMixinFields0[1].Descriptor()
	// oauthconnectionhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthconnectionhistory.DefaultCreatedAt = oauthconnectionhistoryDescCreatedAt.Default.(func() time.Time)
	// oauthconnectionhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	oauthconnectionhistoryDescUpdatedAt := oauthconnectionhistoryMixinFields0[2].Descriptor()
	// oauthconnectionhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthconnectionhistory.DefaultUpdatedAt = oauthconnectionhistoryDescUpdatedAt.Default.(func() time.Time)
	// oauthconnectionhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthconnectionhistory.UpdateDefaultUpdatedAt = oauthconnectionhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthconnectionhistoryDescHistoryTime is the schema descriptor for history_time field.
	oauthconnectionhistoryDescHistoryTime := oauthconnectionhistoryFields[1].Descriptor()
	// oauthconnectionhistory.DefaultHistoryTime holds the default value on creation for the history_time field.
	oauthconnectionhistory.DefaultHistoryTime = oauthconnectionhistoryDescHistoryTime.Default.(func() time.Time)
	// oauthconnectionhistoryDescID is the schema descriptor for id field.
	oauthconnectionhistoryDescID := oauthconnectionhistoryFields[0].Descriptor()
	// oauthconnectionhistory.DefaultID holds the default value on creation for the id field.
	oauthconnectionhistory.DefaultID = oauthconnectionhistoryDescID.Default.(func() uuid.UUID)
	oauthpendingMixin := schema.OAuthPending{}.Mixin()
	oauthpendingMixinFields0 := oauthpendingMixin[0].Fields()
	_ = oauthpendingMixinFields0
	oauthpendingFields := schema.OAuthPending{}.Fields()
	_ = oauthpendingFields
	// oauthpendingDescCreatedAt is the schema descriptor for created_at field.
	oauthpendingDescCreatedAt := oauthpendingMixinFields0[1].Descriptor()
	// oauthpending.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthpending.DefaultCreatedAt = oauthpendingDescCreatedAt.Default.(func() time.Time)
	// oauthpendingDescUpdatedAt is the schema descriptor for updated_at field.
	oauthpendingDescUpdatedAt := oauthpendingMixinFields0[2].Descriptor()
	// oauthpending.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthpending.DefaultUpdatedAt = oauthpendingDescUpdatedAt.Default.(func() time.Time)
	// oauthpending.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthpending.UpdateDefaultUpdatedAt = oauthpendingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthpendingDescState is the schema descriptor for state field.
	oauthpendingDescState := oauthpendingFields[0].Descriptor()
	// oauthpending.StateValidator is a validator for the "state" field. It is called by the builders before save.
	oauthpending.StateValidator = oauthpendingDescState.Validators[0].(func(string) error)
	// oauthpendingDescID is the schema descriptor for id field.
	oauthpendingDescID := oauthpendingMixinFields0[0].Descriptor()
	// oauthpending.DefaultID holds the default value on creation for the id field.
	oauthpending.DefaultID = oauthpendingDescID.Default.(func() uuid.UUID)
	subscriptionMixin := schema.Subscription{}.Mixin()
	subscriptionMixinFields0 := subscriptionMixin[0].Fields()
	_ = subscriptionMixinFields0
	subscriptionFields := schema.Subscription{}.Fields()
	_ = subscriptionFields
	// subscriptionDescCreatedAt is the schema descriptor for created_at field.
	subscriptionDescCreatedAt := subscriptionMixinFields0[1].Descriptor()
	// subscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscription.DefaultCreatedAt = subscriptionDescCreatedAt.Default.(func() time.Time)
	// subscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	subscriptionDescUpdatedAt := subscriptionMixinFields0[2].Descriptor()
	// subscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscription.DefaultUpdatedAt = subscriptionDescUpdatedAt.Default.(func() time.Time)
	// subscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscription.UpdateDefaultUpdatedAt = subscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// subscriptionDescPlan is the schema descriptor for plan field.
	subscriptionDescPlan := subscriptionFields[0].Descriptor()
	// subscription.DefaultPlan holds the default value on creation for the plan field.
	subscription.DefaultPlan = subscriptionDescPlan.Default.(string)
	// subscription.PlanValidator is a validator for the "plan" field. It is called by the builders before save.
	subscription.PlanValidator = subscriptionDescPlan.Validators[0].(func(string) error)
	// subscriptionDescStatus is the schema descriptor for status field.
	subscriptionDescStatus := subscriptionFields[1].Descriptor()
	// subscription.DefaultStatus holds the default value on creation for the status field.
	subscription.DefaultStatus = subscriptionDescStatus.Default.(string)
	// subscription.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	subscription.StatusValidator = subscriptionDescStatus.Validators[0].(func(string) error)
	// subscriptionDescSanctionedCredits is the schema descriptor for sanctioned_credits field.
	subscriptionDescSanctionedCredits := subscriptionFields[3].Descriptor()
	// subscription.DefaultSanctionedCredits holds the default value on creation for the sanctioned_credits field.
	subscription.DefaultSanctionedCredits = subscriptionDescSanctionedCredits.Default.(int)
	// subscription.SanctionedCreditsValidator is a validator for the "sanctioned_credits" field. It is called by the builders before save.
	subscription.SanctionedCreditsValidator = subscriptionDescSanctionedCredits.Validators[0].(func(int) error)
	// subscriptionDescID is the schema descriptor for id field.
	subscriptionDescID := subscriptionMixinFields0[0].Descriptor()
	// subscription.DefaultID holds the default value on creation for the id field.
	subscription.DefaultID = subscriptionDescID.Default.(func() uuid.UUID)
	subscriptionhistoryMixin := schema.SubscriptionHistory{}.Mixin()
	subscriptionhistoryMixinFields0 := subscriptionhistoryMixin[0].Fields()
	_ = subscriptionhistoryMixinFields0
	subscriptionhistoryFields := schema.SubscriptionHistory{}.Fields()
	_ = subscriptionhistoryFields
	// subscriptionhistoryDescCreatedAt is the schema descriptor for created_at field.
	subscriptionhistoryDescCreatedAt := subscriptionhistoryMixinFields0[1].Descriptor()
	// subscriptionhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscriptionhistory.DefaultCreatedAt = subscriptionhistoryDescCreatedAt.Default.(func() time.Time)
	// subscriptionhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	subscriptionhistoryDescUpdatedAt := subscriptionhistoryMixinFields0[2].Descriptor()
	// subscriptionhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscriptionhistory.DefaultUpdatedAt = subscriptionhistoryDescUpdatedAt.Default.(func() time.Time)
	// subscriptionhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscriptionhistory.UpdateDefaultUpdatedAt = subscriptionhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// subscriptionhistoryDescHistoryTime is the schema descriptor for history_time field.
	subscriptionhistoryDescHistoryTime := subscriptionhistoryFields[1].Descriptor()
	// subscriptionhistory.DefaultHistoryTime holds the default value on creation for the history_time field.
	subscriptionhistory.DefaultHistoryTime = subscriptionhistoryDescHistoryTime.Default.(func() time.Time)
	// subscriptionhistoryDescPlan is the schema descriptor for plan field.
	subscriptionhistoryDescPlan := subscriptionhistoryFields[4].Descriptor()
	// subscriptionhistory.DefaultPlan holds the default value on creation for the plan field.
	subscriptionhistory.DefaultPlan = subscriptionhistoryDescPlan.Default.(string)
	// subscriptionhistoryDescStatus is the schema descriptor for status field.
	subscriptionhistoryDescStatus := subscriptionhistoryFields[5].Descriptor()
	// subscriptionhistory.DefaultStatus holds the default value on creation for the status field.
	subscriptionhistory.DefaultStatus = subscriptionhistoryDescStatus.Default.(string)
	// subscriptionhistoryDescSanctionedCredits is the schema descriptor for sanctioned_credits field.
	subscriptionhistoryDescSanctionedCredits := subscriptionhistoryFields[7].Descriptor()
	// subscriptionhistory.DefaultSanctionedCredits holds the default value on creation for the sanctioned_credits field.
	subscriptionhistory.DefaultSanctionedCredits = subscriptionhistoryDescSanctionedCredits.Default.(int)
	// subscriptionhistoryDescID is the schema descriptor for id field.
	subscriptionhistoryDescID := subscriptionhistoryFields[0].Descriptor()
	// subscriptionhistory.DefaultID holds the default value on creation for the id field.
	subscriptionhistory.DefaultID = subscriptionhistoryDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescWorkosUserID is the schema descriptor for workos_user_id field.
	userDescWorkosUserID := userFields[1].Descriptor()
	// user.WorkosUserIDValidator is a validator for the "workos_user_id" field. It is called by the builders before save.
	user.WorkosUserIDValidator = userDescWorkosUserID.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	userhistoryMixin := schema.UserHistory{}.Mixin()
	userhistoryMixinFields0 := userhistoryMixin[0].Fields()
	_ = userhistoryMixinFields0
	userhistoryFields := schema.UserHistory{}.Fields()
	_ = userhistoryFields
	// userhistoryDescCreatedAt is the schema descriptor for created_at field.
	userhistoryDescCreatedAt := userhistoryMixinFields0[1].Descriptor()
	// userhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	userhistory.DefaultCreatedAt = userhistoryDescCreatedAt.Default.(func() time.Time)
	// userhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	userhistoryDescUpdatedAt := userhistoryMixinFields0[2].Descriptor()
	// userhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userhistory.DefaultUpdatedAt = userhistoryDescUpdatedAt.Default.(func() time.Time)
	// userhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userhistory.UpdateDefaultUpdatedAt = userhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userhistoryDescHistoryTime is the schema descriptor for history_time field.
	userhistoryDescHistoryTime := userhistoryFields[1].Descriptor()
	// userhistory.DefaultHistoryTime holds the default value on creation for the history_time field.
	userhistory.DefaultHistoryTime = userhistoryDescHistoryTime.Default.(func() time.Time)
	// userhistoryDescID is the schema descriptor for id field.
	userhistoryDescID := userhistoryFields[0].Descriptor()
	// userhistory.DefaultID holds the default value on creation for the id field.
	userhistory.DefaultID = userhistoryDescID.Default.(func() uuid.UUID)
}
