// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/subscriptionhistory"
	"github.com/flume/enthistory"
	"github.com/google/uuid"
)

// SubscriptionHistory is the model entity for the SubscriptionHistory schema.
type SubscriptionHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// HistoryTime holds the value of the "history_time" field.
	HistoryTime time.Time `json:"history_time,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation enthistory.OpType `json:"operation,omitempty"`
	// Ref holds the value of the "ref" field.
	Ref uuid.UUID `json:"ref,omitempty"`
	// Plan holds the value of the "plan" field.
	Plan string `json:"plan,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TrialExpiresAt holds the value of the "trial_expires_at" field.
	TrialExpiresAt *time.Time `json:"trial_expires_at,omitempty"`
	// SanctionedCredits holds the value of the "sanctioned_credits" field.
	SanctionedCredits int `json:"sanctioned_credits,omitempty"`
	// StripeCustomerID holds the value of the "stripe_customer_id" field.
	StripeCustomerID string `json:"stripe_customer_id,omitempty"`
	// StripeSubscriptionID holds the value of the "stripe_subscription_id" field.
	StripeSubscriptionID string `json:"stripe_subscription_id,omitempty"`
	selectValues         sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionhistory.FieldSanctionedCredits:
			values[i] = new(sql.NullInt64)
		case subscriptionhistory.FieldOperation, subscriptionhistory.FieldPlan, subscriptionhistory.FieldStatus, subscriptionhistory.FieldStripeCustomerID, subscriptionhistory.FieldStripeSubscriptionID:
			values[i] = new(sql.NullString)
		case subscriptionhistory.FieldCreatedAt, subscriptionhistory.FieldUpdatedAt, subscriptionhistory.FieldHistoryTime, subscriptionhistory.FieldTrialExpiresAt:
			values[i] = new(sql.NullTime)
		case subscriptionhistory.FieldID, subscriptionhistory.FieldRef:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionHistory fields.
func (_m *SubscriptionHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionhistory.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case subscriptionhistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionhistory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscriptionhistory.FieldHistoryTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field history_time", values[i])
			} else if value.Valid {
				_m.HistoryTime = value.Time
			}
		case subscriptionhistory.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = enthistory.OpType(value.String)
			}
		case subscriptionhistory.FieldRef:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field ref", values[i])
			} else if value != nil {
				_m.Ref = *value
			}
		case subscriptionhistory.FieldPlan:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan", values[i])
			} else if value.Valid {
				_m.Plan = value.String
			}
		case subscriptionhistory.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionhistory.FieldTrialExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field trial_expires_at", values[i])
			} else if value.Valid {
				_m.TrialExpiresAt = new(time.Time)
				*_m.TrialExpiresAt = value.Time
			}
		case subscriptionhistory.FieldSanctionedCredits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sanctioned_credits", values[i])
			} else if value.Valid {
				_m.SanctionedCredits = int(value.Int64)
			}
		case subscriptionhistory.FieldStripeCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_customer_id", values[i])
			} else if value.Valid {
				_m.StripeCustomerID = value.String
			}
		case subscriptionhistory.FieldStripeSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_subscription_id", values[i])
			} else if value.Valid {
				_m.StripeSubscriptionID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionHistory.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SubscriptionHistory.
// Note that you need to call SubscriptionHistory.Unwrap() before calling this method if this SubscriptionHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionHistory) Update() *SubscriptionHistoryUpdateOne {
	return NewSubscriptionHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionHistory) Unwrap() *SubscriptionHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionHistory) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("history_time=")
	builder.WriteString(_m.HistoryTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Operation))
	builder.WriteString(", ")
	builder.WriteString("ref=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ref))
	builder.WriteString(", ")
	builder.WriteString("plan=")
	builder.WriteString(_m.Plan)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.TrialExpiresAt; v != nil {
		builder.WriteString("trial_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("sanctioned_credits=")
	builder.WriteString(fmt.Sprintf("%v", _m.SanctionedCredits))
	builder.WriteString(", ")
	builder.WriteString("stripe_customer_id=")
	builder.WriteString(_m.StripeCustomerID)
	builder.WriteString(", ")
	builder.WriteString("stripe_subscription_id=")
	builder.WriteString(_m.StripeSubscriptionID)
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionHistories is a parsable slice of SubscriptionHistory.
type SubscriptionHistories []*SubscriptionHistory
